### ISSUE TITLE
Runs of length 2 and motusFilter == 0 showing up on detection timelines and track maps

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1332] opened 2023-03-07 16:11 UTC
I noticed some seemingly false detections on the map of this tag https://motus.org/data/track?tagDeploymentId=39386 (the one in the Midwest US)

![image](https://user-images.githubusercontent.com/55001144/223476298-cac6039c-610f-4179-a3ed-e76de25fa049.png)

The tags do not however show up in the daily summary (I usually come up with the tag/sensor deploy pair for flagging from det_taghits_daily).

Looking at the suspect runs `where sensor_deploy_id = 9191 and tag_deploy_id = 39386` they all have length 2, as well as motusFilter 0.

There is one other receiver with detections in this case in the timeline but not in the daily summary: id 9192, right beside the other. It also consists only of runs of length two. It doesn't show up on the map, presumably because it was filtered out due to proximity or time.

Both of these are Sigma Eight receivers, whether or not that's relevant (not sure how, but hey)

**Comment by j-sayers** [comment] 2023-03-23 13:07
Another case of this happening, and again, it's a SEI receiver so it does appear that receiver type may be a factor somehow.

This is `where sensor_deploy_id = 9191 and tag_deploy_id = 44081`.

**Comment by Hussell** [comment] 2023-03-30 13:54
Correction: sensor_deploy_id = 9192, at least in the first post. I've been unable to find anything which matches for tag_deploy_id = 44081.

**Comment by j-sayers** [comment] 2023-03-30 13:56
There were some for the first tag at sensor_deploy_id 9192 as well, though I don't think so for the second.

Here is the map for the first one: https://motus.org/data/track?tagDeploymentId=39386

**Comment by Hussell** [comment] 2023-03-30 14:18
After discussion with Josh, closing because the page is working as intended.

**Closed by Hussell** 2023-03-30 14:18 UTC
