### ISSUE TITLE
Misidentified Error? "Detections Outside Receiver Deployment"

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#597] opened 2019-10-30 19:38 UTC
Moved from email.

[One of the data issues in **Project 287**](https://motus.org/data/issues?id=287#v_sensor_hits_out_deploy) says one of the receivers has detections outside of a deployment, even though [there is a deployment during that time span](https://motus.org/data/receiverDeployment?id=5546).  In addition, the 'Device ID' **1491** that's listed in that issue does not exist in our database, neither does a deployment with the same ID. 
1. Where is this 'Device ID' coming from?
2. Is there a way we can verify the detections described in the issue are actually being allocated to the correct receiver **(3396)?**

**Comment by denislepage** [comment] 2019-10-31 03:19
DeviceID relates to the sensors_hash_keys table, not sensors. It’s unique to the device itself.

1491 matches SG-B17ERPI36118.

SensorID is unique to the project (deviceID 1491 can be listed in several projects).

There is a sensorID 3396 under project 287, and another 3397 under project 0.

There is a deployment for sensorID 3396 from June to October 2019, deploymentID = 5546.

I am seeing 5 batches for that deviceID, only one of which has  31 hits.

All these 31 hits are matched to deployment 5546.

Not seeing any issues here.

In fact, the only warning I am seeing for this project is a different receiver for which there hasn’t been any data yet.

**Comment by jsayers-bsc** [comment] 2019-10-31 13:17
That's interesting: the error is indeed gone. Perhaps the error itself was an error! It certainly looked that way since the supposed detections did occur within a deployment. 

But a mistaken error seems no less odd!

Relatedly, do similar errors typically reference the DeviceID in the first place? If so, that seems a little confusing as DeploymentID would _seem_ to be the more obvious choice since it's the deployment that is the relevant bit, not the device in general.

The DeviceID is displayed in the [receiver properties](https://motus.org/data/receivers/edit?projectID=287&id=3396), but it doesn't appear that it can be searched for directly, which would make it hard to find and resolve and error referenced by DeviceID (DeviceID isn't even in the .csv obtained when receivers are Downloaded). (If there is a simple way of searching DeviceID from Motus.org someone please fill me in!)

**Comment by cjardine-bsc** [comment] 2019-10-31 20:46
It's possible the deployment had been updated and the data validations had not been yet been re-run since. The error would disappear when the validations were reprocessed. 

Since these are detections outside a receiver deployment they can only report the deviceID since the hits are not associated with any deploymentID. Reporting sensorID is an option, but would that be better than DeviceID? That might be more confusing because the detections could actually be associated with the sensor registered to a different project (in cases where sensors are transferred between projects). 

DeviceID is included in the R package, where are you referencing it being missing? We might want to consider adding it. 

To find the relevant receiver, users should be able to click on the edit link on the issues page. Hopefully that is working?

**Comment by jsayers-bsc** [comment] 2019-11-01 11:24
Ok I guess that makes sense with the DeviceID vs DeploymentID: the lack of an associated DeploymentID is the problem in the first place!

I agree that SensorID doesn’t simplify things at all.

What I mean is that DeviceID isn’t readily available from the web interface. I assumed that’s where this user noticed the error in the first place. At least, I’m not aware of a simple way of searching for it like I can with a receiver Serno or deployment name. So if the user sees an error with DeviceID X there’s no straightforward way of looking up what DeviceID X actually is. In this case, they only had a few receivers so they could click each one and see bur from projects with more receivers, that would be difficult through the web portal.

The issue is no longer there so I can’t see it, but I don’t recall being able to click it and get that information. Maybe I just missed it, but I recall going through a few steps and not being able to easily figure out what that DeviceID was, other than clicking on the receivers themselves.

Yeah maybe that was the reason for the mistaken error. Interestingly, when I checked recently they also now had 2 tag hits on that receiver deployment, though there was nothing there earlier in the day.

**Closed** 2021-01-31 16:49 UTC
Labels: Bug, Presumed resolved - Old
