### ISSUE TITLE
CTT data in R?

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#813] opened 2020-09-28 23:27 UTC
Collaborator having trouble getting their CTT data through R?

Delayed uploads from CTT, or problem on our end, or the script?

proj.num14 <- 'CTT-5031194D3168' # IndianRidge2-MPG-MT
sql.motus14 <- tagme(proj.num14, new = TRUE, update=TRUE)
#sql.motus14 <- tagme(projRecv = proj.num, update = TRUE)
tbl.alltags14 <- tbl(sql.motus14, "alltags")
df.alltags14 <- tbl.alltags14 %>% 
  collect() %>% 
  as.data.frame() %>%     # for all fields in the df (data frame)
  mutate(ts = as_datetime(ts, tz = "UTC", origin = "1970-01-01"))

**Comment by jsayers-bsc** [comment] 2020-09-30 20:04
When I try to download data for this particular receiver I get the following error: 

> Error: This receiver database does not have a valid deviceID stored in it.
> Try delete or rename the file and use tagme() again?

Thing is this receiver is present in the sensors_hash_keys table, so there definitely is a deviceID associated with it, at least in the DB.

Though once, after getting the error above multiple times I got the following error: 

> Error in if (as.integer(bareno) >= 391) { : 
>   missing value where TRUE/FALSE needed
> In addition: Warning message:
> In getLotekModel(projRecv) : NAs introduced by coercion

They said they have received several errors, though haven't yet elaborated on what errors they are seeing.

I have been accessing CTT data through the R package without any issues. But those were V1 SS, and I've recently had issues [downloading data from 3 of our own V2 SS](https://github.com/MotusDev/Motus-TO-DO/issues/815). So maybe there are still some issues with V2 compatibility with the Motus R package.

**Comment by ajmacdonald3** [comment] 2020-09-30 23:19
I also get those errors. The first time downloading I get the second error message Josh mentions. It seems that the tagme() function somehow leads to calling the [getLotekModel()](https://github.com/MotusWTS/motus/blob/master/R/getLotekModel.R) function, even though this isn't a Lotek receiver. I can't figure out why, but when it does call that function, it tests whether the serial number without the "Lotek-" prefix is >= 391. Since the SS serial number has a letter in it, it's not an integer and returns NA causing the error.

I can't find the connection between tagme() and getLotekModel(), so I don't know why this is happening. But I think this might be where the problem is.

I tried downloading some of the V2 SS I have out here, and was able to download the data for them and did not get these errors. However, the Blackie Spit station data did not include the CTT test tag in R, even though I know it was detected. However, the CTT test tag was there in R for a test deployment of another V2 SS.

**Comment by steffilazerte** [comment] 2020-10-01 13:29
I suspect that this might be an R package issue (or a new data issue that isn't compatible with the R package). However, I'll need access to a receiver that's running into problems, ideally on `beta`. @cjardine-bsc? @denislepage?

**Comment by StuMackenzie** [comment] 2020-10-01 14:21
@steffilazerte I added you to project 213 which has the receiver in question above and others. We really should just give you admin privileges - surprised you don't have them already.

**Comment by jsayers-bsc** [comment] 2020-10-01 14:25
> We really should just give you admin privileges - surprised you don't have them already.

Good point! Just did so no more needing to be added on to particular projects

**Comment by steffilazerte** [comment] 2020-10-06 14:58
Thanks :)

**Comment by StuMackenzie** [comment] 2020-10-14 15:22
Do we have any insight into this problem? resolved? Thank

**Comment by steffilazerte** [comment] 2020-10-15 13:39
I'm sorry, no, I haven't had the chance yet.

**Comment by steffilazerte** [comment] 2020-10-15 14:07
Okay, of course @StuMackenzie gentle question had the effect of prodding me into making this my priority this morning. I think I have found the problem, but to be sure, and to figure out how to fix it, I have some questions regarding receivers.

Right now the motus R code implies that there are two types of receivers: 
1. Sensorgnome receivers that start with "SG"
2. Lotek receivers that do not start with "SG" 

This receiver starts with CTT, therefore the code as it stands goes to the `getLotekModel()` function which causes at least one of the errors.

Can I make the assumption that this is out of date?

- I know that Sensorgnome receivers start with "SG-"
- Do Lotek receivers start with "Lotek-"?
- Do CTT receivers start with "CTT-"?
- What in the CTT receiver number indicates the "model"? For example, in the Sensorgnomes it's the 8-11 characters, in the Loteks it a bit more complicated but also coded in the name. 
- Are there anymore receiver types that I should be aware of?
- I plan to add a catch to this code so that if receivers don't match one of the three options we get an informative error right away.

**Comment by StuMackenzie** [comment] 2020-10-15 14:47
CTT receivers start with CTT then a 12 digit alphanumeric, eg. CTT-18BC3777F716

For the time being there are no other receiver types, but will let you know if/when that happens. There is only one other that might be on the horizon.

**Comment by steffilazerte** [comment] 2020-10-15 14:53
Do you know what the model number is? Or do they not have model numbers?

**Comment by StuMackenzie** [comment] 2020-10-15 15:00
hmmmm. There is a version 1 and version 2 Sensorstation, but I'm not sure if the model number is tracked anywhere in the serial or elsewhere.  I can ask if others aren't sure.

**Comment by StuMackenzie** [comment] 2020-10-15 15:38
V1 should be 15 digits, as they are based on the IMEI number, but CTT said 16. Might just be a mistake.

**Comment by steffilazerte** [comment] 2020-10-15 15:45
Okay, so for the model number field I'll probably use something like "V1" and "V2" based on the number of characters in the serial number. Thanks!

**Comment by denislepage** [comment] 2020-10-15 16:02
In case this is helpful, here's the list of receiver types and regex used to validate their numbers. You may not need to be as precise in R.

receiver_type | receiver_descr | receiver_descr_fr | regex
-- | -- | -- | --
LOTEK | Lotek | Lotek | ^Lotek-\w{3,}$
LOTEKSRX400A | Lotek SRX 400A | Lotek SRX 400A | ^Lotek-9\d{3}A$
LOTEKSRX600 | Lotek SRX 600 | Lotek SRX 600 | ^Lotek-6\d{3}$
LOTEKSRX800 | Lotek SRX 800 | Lotek SRX 800 | ^Lotek-([0-2]\d{2}\|3[0-8]\d\|390)$
LOTEKSRX800D | Lotek SRX 800D | Lotek SRX 800D | ^Lotek-D\d{6}$
LOTEKSRX800M/MD | Lotek SRX 800M/MD | Lotek SRX 800M/MD | ^Lotek-(39[1-9]\|[4-9]\d{2})$
LOTEKSRX-DL | Lotek SRX DL | Lotek SRX DL | ^(Lotek-8\d{3})\|(Lotek-D\d{6})$
SENSORGNOME | SensorGnome | SensorGnome | ^SG-[0-9A-Z]{4}(BBBK\|(BB0[0-9])\|(RPI[23Z]))[0-9A-Z]{4}(_[0-9]){0,1}
SENSORSTATION | CTT SensorStation | CTT SensorStation | ^(CTT\-[0-9A-F]{12,16})
UNKNOWN | Unknown | Inconnu | NULL

**Comment by steffilazerte** [comment] 2020-10-15 16:07
Good to know, thanks

**Comment by denislepage** [comment] 2020-10-15 16:33
In the case of R, the prefix should be enough, as precise regexes may change over time.

**Comment by steffilazerte** [comment] 2020-10-15 16:53
Currently I'm just finalizing the testing of a fix that:

1. uses the prefix to specify the receiver type (currently: SG, CTT or Lotek, case insensitive) This will result in an error if the prefix doesn't match one of these three options. Which might be annoying but I think it's better to get a solid, understandable error, than a weird error down the road.

2. I use the number of characters to determine model number for CTT (15 = V1, 12 = V2), the SG and Lotek receivers already had model specifications relating to other things which I haven't changed. 

So far this has fixed the problems on my end, so as soon as the tests pass I'll upload it to beta4 and get @StuMackenzie to give it a test run.

**Comment by steffilazerte** [comment] 2020-10-15 17:24
Should be ready for a test run now, 

To install v.4.0.1.9999 and test

```
remotes::install_github("MotusWTS/motus", ref = "beta4")

library(motus)
tags <- tagme("CTT-5031194D3168", new = TRUE, update = TRUE)
```

**Comment by leberrigan** [comment] 2020-10-15 17:55
Just tried and downloads have started successfully. 

I'll report back with what I get once that has completed.

**Comment by StuMackenzie** [comment] 2020-10-22 21:44
Project 213 is still having trouble getting their data through R? Are there any unresolved issues?

**Comment by jsayers-bsc** [comment] 2020-10-23 00:05
There seem to be a few different issues going on here, most of it has been resolved. There was an issue with AWS bucket, which is now resolved. And there was another issue Jeremy pointed out that was also resolved yesterday. So nearly all CTT SensorStations seem to be properly syncing data. At least all those I've seen.

~However, the original issue regarding this particular receiver CTT-5031194D3168 seems to still be an issue. I still get the same error reported earlier: 
Error: This receiver database does not have a valid deviceID stored in it.
Try delete or rename the file and use tagme() again?~

**BUT**, I just deleted my local file, restarted and tried again. This time it worked. Whatever the ultimate cause, it seemed to have resulted in a corrupted local database, which was causing persistent issues.

**So this _may_ actually be resolved in v.4.0.1.999** 

@leberrigan You started downloading data from this receiver a few days ago and it seemed to be working. Did that go ok? 

@ajmacdonald3 Can you have another go at downloading this receiver's data when you get a chance?

**Comment by ajmacdonald3** [comment] 2020-10-23 00:34
I downloaded this receiver's data earlier today and I was able to download it from the beta4 branch. I also had to delete a previous attempt at downloading the database and start downloading a new one. I also confirmed that this receiver did have detections of at least one lifetag since project 213 was also having issues getting any CTT data in R. Perhaps we can push this fix to live?

**Comment by steffilazerte** [comment] 2020-10-23 16:14
Just let me know and I'll push to master :)

**Comment by denislepage** [comment] 2020-10-24 00:43
Sorry if I haven't been following. Is there a fix in beta API that needs to be pushed to live, in addition to a fix to the R package? Was your test in beta4 pointing to the beta.motus.org or www.motus.org server?

**Comment by steffilazerte** [comment] 2020-10-26 20:53
I don't think so, I'm pretty sure these are all R package changes (all my tests run fine on the main www.motus.org server).
So should I release this minor series of package fixes?

**Comment by denislepage** [comment] 2020-10-26 23:12
I think so, yes.

**Closed** 2020-10-27 18:28 UTC
