### ISSUE TITLE
metadata() not pulling full metadata

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#171] opened 2018-02-13 19:30 UTC
I've tried running metadata() on a receiver and a project .motus file and I'm not getting full metadata across the network.  Also the number of records I get seems to vary depending on which file I run that function on, I'm always logged in as myself so with admin permissions I wouldn't expect numbers to vary.  

E.g. 
running metadata() on project 111, I get 14757 tagDeps records, running it on project 3 I get 21595 tagDeps, It should be a much higher number of records.

Also, there are repeated entries that shouldn't exist - motusTagID 16741 has no deployments, yet it shows up 5 times in the tagDeps table when metadata is loaded for project 3 (deployIDs 16429, 18139, 19849, 21559, 23629), and it shows up once in thetagDeps table when metadata is loaded for project 111 (deployID 16429), each time with tag deployment IDs that do not exist as far as I can tell in the database. 

Those projects both return 14459 records in the tags table

My code was:
projnum = 3
tmp <- tagme(projnum, update = FALSE)
metadata(tmp)
tmp <- tagme(projnum, update = FALSE)
tags3 <- tbl(tmp, "tags")
tags3 <- tags3 %>% collect %>% as.data.frame

**Comment by zcrysler** [comment] 2018-02-15 17:26
It seems like when you run metadata() more than once, it continues to add records.  I just tried this again with project 45, and looking at the example of tagID 16741, after running metadata() once, I got one record of it in the tagDeps table, when I ran metadata() again I got two records (deployID 16429 and 18137).  This tag doesn't have a deployment, so I'm not sure where these numbers are coming from.  The tags table doesn't seem to change with each run.

**Comment by denislepage** [comment] 2018-02-16 00:11
We have introduced new problems when we started returning null deployment ID's for those metadata tables. The sqlite tables (recvDeps and tagDeps) are using deployID as their primary key, and I am not sure how those are being handled. I would have thought they were just being ignored, but this may be linked to the duplicate issue?

The total number of tagDeps record currently in the database is 14752. 21595 almost certainly stems out of duplicates created by successive calls to tagme and/or metadata?

I'll dig a bit more into this.

**Comment by denislepage** [comment] 2018-02-16 00:17
Ah. What is happening I think is that the null deployment ID's get assigned a new ID by sqlite, rather than being rejected. Until we can address this, I am going to revert the views to exclude any tags or receivers without deployments.

People will need to use the replace=TRUE option to clear their messy metadata with the metadata function.

**Comment by denislepage** [comment] 2018-02-16 00:56
OK, views fixed. The replace option actually doesn't delete any existing data not being re-imported, so I'm adding a new option to delete all records from metadata before re-importing.

It's working for me now, but doesn't resolve what we tried to address by using a left join earlier, and I have not checked every metadata table to make sure they never return null values for sqlite key fields.

`
library(devtools)
install_github("motusWTS/motusClient")
library(motus)
projectID = 1
src = tagme(projectID)
metadata(src, delete=TRUE)
`

**Comment by denislepage** [comment] 2018-02-17 01:47
I'm closing this for now. Remaining issue is that metadata will exclude undeployed tags and receivers from tagDeps and recvDeps, but I can't remember the rationale for why we wanted to add them.

**Closed by denislepage** 2018-02-17 01:47 UTC

**Comment by zcrysler** [comment] 2018-02-19 16:41
We had included a section in the book to check how many registered tags are undeployed - it's section 4.3.3 as part of the metadata checking.  I find it useful to be able to see all registered tags in a project despite their status, so if this can be made possible that would be great.  Otherwise we can direct users to download the tag data from their tagging page and load that into R - but it's obviously easier if it's just included.

**Comment by denislepage** [comment] 2018-02-20 00:34
I believe this only impacts the deployment table, not the tags, so you should still be able to check for tags registered and not deployment. There may be a change needed in the alltags view to use a LEFT JOIN?

The problem may be different for receivers, depending on where the projectID field is being stored (recvs or recvDepl).

I’ll have to look deeper.

**Comment by tcrewe** [comment] 2018-02-20 19:39
Where does this one stand at the moment? Are we looking into it, or does that section need to be removed (hoping not!)?

**Comment by denislepage** [comment] 2018-02-20 21:00
For tags, the undeployed tags should continue to be in the tags table in motus files.

If you wanted to have undeployed tags in R, you would need to do a left join between tags and tagDeps. The anti_join approach already in use should therefore continue to work (actually, it would NOT have worked with the recent changes Catherine made, since the deployment table also included undeployed tags, which seemed unnecessary). You see a list of tags that are not also found in tagDeps. So, as far as I can tell, the fix that I made will ensure that the approach outlined in the book will actually work as intended. Someone should confirm.

Receivers is a different matter. I think this is what Catherine was trying to fix, but her approach didn’t work. For receivers, which are more likely (almost certain) to have multiple deployments, I don’t think it makes sense any to check whether a given receiver is deployed at least once in your project, like we do for tags. It would make more sense to check if any detections or runs do not overlap deployments. In many cases, people will not even see detection data not associated with a deployment (except maybe for receiver files?). I don’t think the book currently deal with this, but it might be useful to add it.

So, I don’t think there’s anything incorrect in the book at the moment, but we may want to at least point out that ways to deal with receivers without deployments, and what are the implications on the data they can see (for tags and/or receiver files). If I recall correctly, if a batch is at least in part associated with a given receiver in a project, the user gets access. Some detections may fall outside of the deployments, but only those within the batches that overlap at least in part.

One implication for instance is that if they change their metadata, some of the earlier batches may suddenly become visible, but they would have to restart the download from scratch to access those. This may only apply to receiver files though.

We need to confirm exactly those details before we can provide instructions.

Denis

**Comment by zcrysler** [comment] 2018-02-21 02:14
metadata() is working as described above, and it still works with the book as is.  We don't look into receiver deployments in the same way, we just look to see how many deployments there are, so no changes to the book needed
