### ISSUE TITLE
Duplicate tags that project 265 wants to deploy

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#536] opened 2019-08-15 02:59 UTC
Project 265 intended to deploy 'old' tags originally purchased for use in fall 2018 - some of which were recently moved from Project 90. Deployment time is ideally 2 weeks.

They were told by Lotek that the ID/intervals of their old tags were resold, so they wouldn't be available for use. The project has asked us to see if there is anything we can do.

I'm suspicious because presumably we wouldn't have let duplicate tags be registered.

Can we:

1) find out if any of the tags in Project 265 are duplicated elsewhere?

Then we can decide if there is any way for us to help.

**Comment by Hussell** [comment] 2019-08-15 14:26
Practically every tag has duplicates, so it would help to have a list of the tags to check.

That said, I see at least 5 undeployed tags in project 265 with date bins in 2018 which are duplicated in project 262. The project 262 tags have already been deployed, and have expected lifetimes into May 2020.

Project 265 Tag IDs: 28715, 28725, 28731, 28755, 28760.

**Comment by cjardine-bsc** [comment] 2019-08-15 20:13
ah, yes there should be an error thrown in the data validation center if this situation occurs. I fixed a bug in that proc and updated it to ignore CTT tags and that should be functioning. 

You can now view the list of potentially ambiguous tags here:

https://motus.org/data/issues?id=265#v_tag_overlap_active

The description as it was, was not particularly helpful. I've added the project that the tag conflicts with. 

All that to say if they deploy these tags they will indeed be detected as ambigs.

**Comment by Hussell** [comment] 2019-08-15 20:43
Still a bit buggy, since it's treating mfg_id 369 == 368.7. Instead of round(cast(b.mfg_id as float), 0) it should be floor(cast(b.mfg_id as float)).

**Comment by cjardine-bsc** [comment] 2019-08-15 20:57
why in the world do we have a prefix of .7?!?!

Fine.

**Comment by StuMackenzie** [comment] 2019-08-16 19:01
Are the 8 tags listed here https://motus.org/data/issues?id=265#v_tag_overlap_active really the only potential conflicts? Just trying to get my story straight before getting back to the project who is willing to deal with all the coordination involved, etc. with deploying overlapping tags.

**Comment by cjardine-bsc** [comment] 2019-08-16 19:02
Yes, as far as I can see.

**Comment by StuMackenzie** [comment] 2019-08-16 19:14
you can close - I know how much it pleases you. That may be all we can do for now.

**Comment by cjardine-bsc** [comment] 2019-08-16 19:21
Kapoo!

**Comment by StuMackenzie** [comment] 2019-08-21 14:14
The conflict tags don't show up anymore - were they removed or moved from this project?

**Comment by StuMackenzie** [comment] 2019-08-21 14:15
NM - sorry. I was looking at the wrong project.

**Comment by StuMackenzie** [comment] 2019-08-21 19:40
Just putting this here for safe keeping: 

List of conflicts from Lotek:

Motus ID | Tag Label | Description & Year | Burst   rate (s) | Researcher bought same ID /   Burst in 2019 | 2019 Intended Species
-- | -- | -- | -- | -- | --
28333 | 380-305 | NTQB-3-2, purchased by Stu Mackenzie, date unknown | 14.1 |   | ? | ?
28335 | 380-307 | NTQB-3-2, purchased by Stu Mackenzie, date unknown | 14.1 |   | ? | ?
24367 | 380-39 | NTQBW-3-2, 2016 cuckoo tag | 19.9 |   | Greg Mitchell (2018 purchase, 594 day tag life) | Common Nighthawk / Whip-poor-will
28346 | 415 12.7 | NTQB2-2, 2018 NOWA tag | 12.7 |   | Bridget Stutchbury | Wood Thrush
28337 | 412 12.7 | NTQB2-2, 2018 NOWA tag | 12.7 |   | Bridget Stutchbury | Wood Thrush
28349 | 416 12.7 | NTQB2-2, 2018 NOWA tag | 12.7 |   | Bridget Stutchbury | Wood Thrush
28342 | 414 12.7 | NTQB2-2, 2018 NOWA tag | 12.7 |   | Bridget Stutchbury | Wood Thrush
28339 | 413 12.7 | NTQB2-2, 2018 NOWA tag | 12.7 |   | Bridget Stutchbury | Wood Thrush
24374 | 024 14.9 | NTQB3-2, 2017 | 14.9 |   | no conflict | n/a
23300 | 047 12.7 | NTQB-2, 2017 | 12.7 |   | Greg Mitchell | Yellow-rumped Warbler
28755 | 368 9.7 | NTQB2-1, purchased by Dave King in 2018 | 9.7 |   | Kevin Fraser | Purple Martin
28731 | 359 9.7 | NTQB2-1, purchased by Dave King in 2018 | 9.7 |   | Kevin Fraser | Purple Martin
28760 | 353 9.7 | NTQB2-1, purchased by Dave King in 2018 | 9.7 |   | Kevin Fraser | Purple Martin
28715 | 339 9.7 | NTQB2-1, purchased by Dave King in 2018 | 9.7 |   | Kevin Fraser | Purple Martin
28725 | 350 9.7 | NTQB2-1, purchased by Dave King in 2018 | 9.7 |   | Kevin Fraser | Purple Martin

Response: (CJ)
Okay, so 5 of the tags on the list of potential conflicts from lotek overlap with our list: 28755,28731,28760,28715,28725

We’re going to say those 5 are for sure problematic. 

Of the other 10, 7 of them have deployments in 265 from 2018. Because those are seen as completed deployments by our database (tag lifespans are over). We are no longer checking for conflicts for those tags. I suspect those deployments are not real (ah-ha!) and should have their start date set to null. They will then get picked up by the checks again. But based on the current metadata provided by 265 those tags are old news. (this is why I don’t think we should be creating a deployment when people register tags…..but that’s another matter)

Tag Ids

28333
28335
28337
28339
28342
28346
28349

Deploy IDs 

15950
15952
15954
15955
15956
15957
15958

The last three tags:

23300: lotek flagged potential ambit with tag ID 34066 in project 20, but that one was deployed this spring with an estimated end date of July 13th. No longer in conflict.  
24367 Lotek has this period listed as 19.9, which would make this tag an ambig with tag_id 29045 from project 201. but it was registered to project 265 with a period of 25.09, so it isn’t showing any conflict. Maybe we need to check the tag registration and see if the BI was recorded properly. 
24374: Lotek lists no conflict. So yay.

SAM - followed up with other projects to see if their metadata was up to date.

**Comment by StuMackenzie** [comment] 2019-08-22 13:35
Project 46 - Stutchbury tags.

Why aren't these tags from 46 being flagged as having duplicate properties to those in 265? Is it also looking for tag model or something like that to assign duplicates?

Stu
Project 46:
MotusID|
34434 | 412 | 12.699199676513672 | 2019-2 | NTQB2-4-2S | 166.38 | 2019-06-07 - ? | Hylocichla mustelina | Edit
-- | -- | -- | -- | -- | -- | -- | -- | --
34435 | 413 | 12.699199676513672 | 2019-2 | NTQB2-4-2S | 166.38 | 2019-06-07 - ? | Hylocichla mustelina | Edit
34436 | 414 | 12.69909954071045 | 2019-2 | NTQB2-4-2S | 166.38 | 2019-06-09 - ? | Hylocichla mustelina | Edit
34437 | 415 | 12.700300216674805 | 2019-2 | NTQB2-4-2S | 166.38 | 2019-06-09 - ? | Hylocichla mustelina | Edit
34438 | 416 | 12.699199676513672 | 2019-2 | NTQB2-4-2S | 166.38 | 2019-06-12 - ? | Hylocichla mustelina | Edit

Project 265:
Motus ID|
28346 | 415 12.7 | NTQB2-2, 2018 NOWA tag | 12.7 |   | Bridget Stutchbury
-- | -- | -- | -- | -- | --
28337 | 412 12.7 | NTQB2-2, 2018 NOWA tag | 12.7 |   | Bridget Stutchbury
28349 | 416 12.7 | NTQB2-2, 2018 NOWA tag | 12.7 |   | Bridget Stutchbury
28342 | 414 12.7 | NTQB2-2, 2018 NOWA tag | 12.7 |   | Bridget Stutchbury
28339 | 413 12.7 | NTQB2-2, 2018 NOWA tag | 12.7 |   | Bridget Stutchbury

**Comment by Hussell** [comment] 2019-08-22 14:43
It's because the tags in project 265 were all deployed in March 2018 and the tags in project 46 were deployed in June 2019, so none of the deployments overlap. We only flag duplicates which might be deployed at the same time.

**Comment by Hussell** [comment] 2019-08-22 14:49
Stu points out (in person) that the deployments for the project 265 tags are just default start times, and he knows them to be inaccurate. So that's the source of the confusion.

**Comment by StuMackenzie** [comment] 2019-08-22 14:53
Yup, my bad.  Stay tuned.

**Comment by Hussell** [comment] 2019-08-22 16:02
After changing the project 265 deployments and rerunning data validation for both projects, the conflicts show up in project 265's data center, but not in project 46's. I think the problem is in the SQL code in prDataValidation_pr which checks whether the two deployments overlap.

The code is (edited for clarity):
where (a.dt_start > b.dt_start and a.dt_start < b.dt_end)
or (a.dt_end > b.dt_start and a.dt_end < b.dt_end)

Dates from a pair of Stu's tags:

| | dt_start | dt_end |
|-|-|-|
| a | 2019-06-07 | 2021-03-30 |
| b | 2019-08-15 | 2020-01-04 |

The code fails to detect the case where deployment a completely overlaps deployment b. I think it should be modified to:
where a.dt_start <= b.dt_end and a.dt_end >= b.dt_start

In prDataValidation_pr there are several other checks for overlapping deployments of tags and receivers. I think they should all be checked for this bug.

**Comment by StuMackenzie** [comment] 2019-08-22 16:08
Phew - crazy, not crazy.

Another example to just to make sure a fix is working is to check is the 5 known conflict/overlapping tags in 265: 28755,28731,28760,28715,28725

Overlap with current deployments in project 262: 35440, 35431, 35426, 35422, 35411

**Comment by Hussell** [comment] 2019-08-22 16:14
The project 265 tags 28755, 28731, 28760, 28715, 28725 don't have deployments, so I think we only give project 265 a warning for those, and project 262 doesn't see anything. That seems to be working correctly.

**Comment by cjardine-bsc** [comment] 2019-08-22 17:34
Morning East-coasters! 

There are two distinct errors. 

One that looks at UNDEPLOYED tags and checks if there are other active tags (deployed or not) that they might overlap with if they were deployed. I think everyone is now on the same page for those, now that we've removed the deployments from spring 2018 from the 265 tags. 

The second check looks at DEPLOYED tags, to see if they overlap with other DEPLOYED tags based on their dates and lifespans. Looks like I need a provision in there for when one deployment falls completely within another. I'll do that now.

**Comment by cjardine-bsc** [comment] 2019-08-22 22:34
I've made a bunch of changes. 

1. updated the data validations for overlapping tag deployments
2. set confirm_dt_start = 1 for all deployments registered through the tagfinder api where the start_date has never been changed. (Note that I found some of these that had been edited through the web interface and therefore had confirm_dt_start = 0 (as opposed to NULL). I excluded those (i,e, left them as confirm_dt_start = 0) to be consistent with the logic used on the web interface. )
3. Added a new error (warning) to the bulk tag upload process that warns the user when the deployment date is staying the same, but the confirm_dt_start field is moving from 1 to 0. 

This is the text I'm using. It's a bit long and detailed. If people want to give feedback we can finalize it and send for translation. 

" The start date for this deployment was provided upon tag registration and needs to be confirmed. Uploading the deployment through this tool will confirm this start date. If this date is NOT correct please either: a) update the date to the correct deployment date, b) remove the date from the deployment, c) set the start date to a future date, or d) remove this deployment from your bulk upload template. "

I've tested the validation in sandbox. Working well. 

4. Updated the descr for the validation center error code v_tag_confirm_dt to the below. It will also need translation once finalized. 

"These tag deployments were created with start dates in the future. The start dates are now in the past, but have not been confirmed. If these tags have not been deployed (particularly if you are saving the tag for a later date) please remove the start date from these deployments so Motus is aware the tags are still undeployed and so that new tags with these properties are not manufactured."

I've made no change to vwTagsActive.

**Comment by Hussell** [comment] 2019-08-23 15:00
The overlapping deployment checks in v_sensor_overlap_deploy and v_tag_overlap_deploy_reg still need to be fixed (change table names to match the respective queries):

(d1.dt_start <= d2.dt_end or d2.dt_end is null) and (d1.dt_end >= d2.dt_start or d1.dt_end is null)

This will evaluate to false if either deployment's dt_start is null, which is reported in different data issues. Replacing a clause with e.g. d1.dt_start <= isnull(d2.dt_end, @dt) would fail to detect overlapping deployments when dt_start is in the future. In v_tag_overlap_deploy_prop dt_end is never null.

**Comment by StuMackenzie** [comment] 2019-10-23 17:26
Please remove these tags from project 265. These tags were reprogrammed by Lotek (now 13.0 BI) and have been registered separately.

(old)   Motus ID | Tag number | (old) pulse rate (s)
-- | -- | --
28346 | 415 12.7 | 12.7
28337 | 412 12.7 | 12.7
28349 | 416 12.7 | 12.7
28342 | 414 12.7 | 12.7
28339 | 413 12.7 | 12.7
23300 | 047 12.7 | 12.7
28755 | 368 9.7 | 9.7
28731 | 359 9.7 | 9.7
28760 | 353 9.7 | 9.7
28715 | 339 9.7 | 9.7
28725 | 350 9.7 | 9.7

**Comment by StuMackenzie** [comment] 2019-10-23 17:34
Trying to mark some tags as deprecated:

Received error: 1571852033079

For Motus ID 28755

**Comment by denislepage** [comment] 2019-10-23 18:12
I think a fix for this is in the works. Am I ready to post to live?

SQL exception: com.microsoft.sqlserver.jdbc.SQLServerException: The conversion from BIT to DATETIMEOFFSET is unsupported.

While attempting: UPDATE tags SET project_id = ?,mfg_id = ?,date_bin = ?,type = ?,codeset = ?,manufacturer = ?,model = ?,nom_freq = ?,offset_freq = ?,period = ?,period_sd = ?,pulse_len = ?,param1 = ?,param2 = ?,param3 = ?,param4 = ?,param5 = ?,param6 = ?,param7 = ?,param8 = ?,param_type = ?,ts_sg = ?,approved = ?,last_edited_dt = ?,last_edited_user_id = ?,clone_tag_id = ?,duty_cycle = ?,deprecated_bit = ?,created = ?,deprecated = ? WHERE id = ?

**Comment by Hussell** [comment] 2019-10-23 20:37
Yes, this fix is in beta9 now and can and should be merged into live.

**Comment by denislepage** [comment] 2019-10-23 21:23
OK, it’s (a)live.

**Closed** 2022-02-24 20:03 UTC
Labels: Bug
