### ISSUE TITLE
tagme command sometimes returns empty tables; forceMeta = T does not seem to work

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#879] opened 2020-12-08 12:33 UTC
While poking around with #878 I figured I should download fresh data just in case my local database was corrupted. So I renamed the old one, which was downloaded the previous day, and downloaded anew. But when looking at the newly downloaded data, I noticed they were not identical. They had the same number of records and appeared the same, until I summarized tags and noticed differences.

As it turns out the more recent download lacked any distinct fullIDs for any of the tag hits. The only tag ID present is `?proj?-0#:0.0.` 

This seems strange for a couple reasons. First, it's the most _recent_ download that lacks the fullID's. It's sort of as if the more recent download occurred after metadata had been updated, but that doesn't really make sense. None of the deployments for the real tags in the data, and the fullIDs have bee stripped, not added. And furthermore, they are all CTT tags so their ID's are  known and they should be no risk of ambiguous tags. 

- Is there any reason to explain how a data download would be modified in this way? I don't believe it's a data corruption on my computer (though that's possible) as I've download this fresh a couple times. 
- [Under what conditions is ?proj?-0#:0.0. assigned as fullID?](https://github.com/MotusDev/Motus-TO-DO/issues/694#issuecomment-646837113)

**Comment by jsayers-bsc** [comment] 2020-12-10 16:23
After posting #883, I went back to the two .motus files I have of this receiver. In the most recent file, the tagDeps table is empty.

**Comment by cjardine-bsc** [comment] 2020-12-10 17:33
So just to be clear: You're downloading using the receiverID and the tagDeps table is not being populated in the SQLite file. But the error is not happening consistently. 

Can you provide the R code you're using, so I can look at the project/receiver and make sure that the R views are returning the correct data? Once we eliminate that possibility it will be over to @pmorrill to look at permissions and the R API.

**Comment by jsayers-bsc** [comment] 2020-12-10 18:21
@cjardine-bsc Yes that's correct. And the inconsistency was demonstrated again just now.

```
library(motus)
library(tidyverse)

d <- 'CTT-5031194D3168'
m <- tagme(d, update = T, forceMeta = T, new = F, dir = 'D:/MotusData')

alltags <- tbl(m, 'alltags') %>% collect() %>% as.data.frame()
# 3,800,000 records in allTags

unique(alltags$fullID)
# only one fullID present in allTags: ?proj?-0#:0.0

tagdeps <- tbl(m, 'tagDeps') %>% collect() %>% as.data.frame()
# tagDeps table is empty
```

So I just ran the above with outcome described in the comments. 

Then I re-ran the code once more, and this time tagDeps seems properly populated along all the fullID's.

**Comment by denislepage** [comment] 2020-12-10 18:29
Almost positive that fullID is just a symptom of missing metadata issue, since this is a field that only exists in the alltags view.

**Comment by jsayers-bsc** [comment] 2020-12-10 18:53
Comparing between newer and older versions of the same db (by a few hours). For this particular receiver, it's flipped a few times. The first `tagme `lacked tagDeps, the next `tagme `had tagDeps and proper fullID's, and then the next `tagme `once again lacked them. Prior to the most recent tagme, I renamed the local db and downloaded anew so I could compare the two.

```
m1 <- DBI::dbConnect(RSQLite::SQLite(), 'D:/MotusData/CTT-867459049297757-old.motus') # downloaded earlier in the day
m2 <- DBI::dbConnect(RSQLite::SQLite(), 'D:/MotusData/CTT-867459049297757-newer.motus') 

alltags1 <- tbl(m1, 'alltags') %>% collect() %>% as.data.frame() 
nrow(alltags1)
# 76565 rows
alltags2 <- tbl(m2, 'alltags') %>% collect() %>% as.data.frame() 
nrow(alltags2)
# 76565 rows

tagdeps1 <- tbl(m1, 'tagDeps') %>% collect() %>% as.data.frame()
# 23 records
tagdeps2 <- tbl(m2, 'tagDeps') %>% collect() %>% as.data.frame()
# 0 records

unique(alltags1$fullID)
# 76 records, all look "normal"
unique(alltags2$fullID)
# [1] "?proj?-0#:0.0"

compare::compare(alltags1$motusTagID, alltags2$motusTagID)
# TRUE
# motusTagID field is the same between the two data sources
```

So for some reason tagDeps table is sometimes populated during tagme, and sometimes not.

**Comment by denislepage** [comment] 2020-12-10 20:21
The main reason that I see would explain this kind of inconsistent behaviour could be tied to the session authentication and permissions, perhaps? I am not sure how Paul has coded the token handling on the API side, but if it relies on cached objects, then perhaps some of these objects are missing and not properly reloaded for this call. Just a speculation.

This would perhaps manifest itself such that calling tagme after a certain period of inactivity with that session (e.g. at least 30 minutes) consistently causes the data to be missing, but then subsequent calls after that are returning all expected data. Not sure if you could test this.

Josh, are you using your own account which has access to all receivers? Is this a receiver where the metadata would be unavailable to the public otherwise (private)?

If we can’t nail this down, we may want to try to add a trace log of some sort in sandbox.

If the API failed to respond in some instances only (e.g. 500 error), they the R tagme function should be reporting errors. I expect these connection errors would not happen silently and would be visible in the printed progress logs, and would likely not consistently only affect always the same table, so I doubt it’s that.

**Comment by pmorrill** [comment] 2020-12-10 20:55
I will look into that suggestion tomorrow, re the token lifespan and caching. It would be great if Josh could test time-sensitive behaviour, as it might help nail it down.

**Comment by jsayers-bsc** [comment] 2020-12-10 21:05
Yes I’m just using my own account. For what it’s worth the most recent example happened within about 1 minute. I ran the code, got no tagDeps then accidentally ran the entire section again rather than just the last line. That time I got the tagDeps.

________________________________

**Comment by jsayers-bsc** [comment] 2021-01-16 15:31
I'm still seeing this regularly, but not yet with any noticeable pattern. Just received an email from Project 123 who had the same issue: no tag metadata in their recently downloaded receiver data. 

While I haven't noticed any pattern of when or why it happens, it does seem that `forceMeta = TRUE` is **not** updating metadata as expected. Calling `metadata()` on the specific Project ID will load all the relevant metadata and resolve the issue. (calling `metadata()` network wide doesn't work at the moment due to [Project 213 failing](https://github.com/MotusDev/Motus-TO-DO/issues/897).)

Below demonstrates this for this receiver of Project 123

```
library(motus)
library(tidyverse)

#  data to be downloaded
d <- 'SG-1116BBBK0C40'

# data directory
dd <- 'D:/MotusData'

# call tagme, ensuring that forceMeta = TRUE
m <- tagme(d, new = T, update = T, forceMeta = T, dir = dd)

# create alltags table
alltags <- tbl(m, 'alltags') %>% collect() %>% as_tibble()

# how many unique ID's are there?
unique(alltags$fullID)
```

> unique(alltags$fullID)
[1] "?proj?-0#:0.0"
  
```
# iterate through the tables and count the rows in each table
for (table in DBI::dbListTables(m$con)){
  rows <- DBI::dbGetQuery(m$con, paste0('select count(*) from ', table))
  print(paste0(rows ,' rows in ', table, ' table'))         
}
```
> [1] "370 rows in activity table"
> [1] "1 rows in admInfo table"
> [1] "0 rows in allambigs table"
> [1] "24733 rows in alltags table"
> [1] "24733 rows in alltagsGPS table"
> [1] "3 rows in antDeps table"
> [1] "928 rows in batchRuns table"
> [1] "14 rows in batches table"
> [1] "0 rows in clarified table"
> [1] "0 rows in filters table"
> [1] "0 rows in gps table"
> [1] "24733 rows in hits table"
> [1] "5 rows in meta table"
> [1] "0 rows in nodeData table"
> [1] "0 rows in nodeDeps table"
> [1] "0 rows in projAmbig table"
> [1] "1 rows in projs table"
> [1] "81388 rows in pulseCounts table"
> [1] "1 rows in recvDeps table"
> [1] "1 rows in recvs table"
> [1] "928 rows in runs table"
> [1] "0 rows in runsFilters table"
> [1] "0 rows in species table"
> [1] "0 rows in tagAmbig table"
> [1] "0 rows in tagDeps table"
> [1] "0 rows in tagProps table"
> [1] "0 rows in tags table"

```
# explicitly call metadata() command
metadata(m, 123)

# create the alltags table again 
alltags <- tbl(m, 'alltags') %>% collect() %>% as_tibble()

# how many unique ID's are there?
unique(alltags$fullID)
```

> [1] "BIRDMOVE_2017#520:10.1@150.1(M.27125)" "?proj?-0#:0.0"                        
>  [3] "BIRDMOVE_2017#92:5.0@150.1(M.27935)"   "BIRDMOVE_2017#109:6.1@150.1(M.28249)" 
>  [5] "BIRDMOVE_2017#98:5.0@150.1(M.27958)"   "BIRDMOVE_2017#185:7.9@150.1(M.28242)" 
>  [7] "BIRDMOVE_2017#144:6.7@150.1(M.28281)"  "BIRDMOVE_2017#91:5.0@150.1(M.27934)"  
>  [9] "BIRDMOVE_2017#200:7.9@150.1(M.28245)"  "BIRDMOVE_2017#97:5.0@150.1(M.27957)"  
> [11] "BIRDMOVE_2017#100:5.0@150.1(M.27939)"  "BIRDMOVE_2017#128:6.7@150.1(M.28228)" 
> [13] "BIRDMOVE_2017#90:5.0@150.1(M.27933)"   "BIRDMOVE_2017#101:5.0@150.1(M.27940)" 
> [15] "BIRDMOVE_2017#16:3.0@150.1(M.27966)"   "BIRDMOVE_2017#184:7.3@150.1(M.28311)" 
> [17] "BIRDMOVE_2017#19:3.0@150.1(M.27969)"   "BIRDMOVE_2017#32:3.5@150.1(M.27979)"  
> [19] "BIRDMOVE_2017#23:2.0@150.1(M.27996)"   "BIRDMOVE_2017#201:7.9@150.1(M.28277)" 
> [21] "BIRDMOVE_2017#8:3.0@150.1(M.27994)"    "BIRDMOVE_2017#147:7.1@150.1(M.28283)" 
> [23] "BIRDMOVE_2017#5:3.0@150.1(M.27980)"    "BIRDMOVE_2017#15:3.0@150.1(M.27965)"  
> [25] "BIRDMOVE_2017#21:3.0@150.1(M.27971)"   "BIRDMOVE_2017#490:9.7@150.1(M.23461)" 
> [27] "BIRDMOVE_2017#512:10.1@150.1(M.23484)" "BIRDMOVE_2017#71:7.1@150.1(M.23391)"  
> [29] "BIRDMOVE_2017#147:8.3@150.1(M.23367)"  "BIRDMOVE_2017#116:7.9@150.1(M.23336)" 
> [31] "BIRDMOVE_2017#99:7.3@150.1(M.23419)"   "BIRDMOVE_2017#49:10.7@150.1(M.27124)" 
> [33] "BIRDMOVE_2017#45:10.7@150.1(M.23454)"  "BIRDMOVE_2017#153:8.9@150.1(M.23373)" 
> [35] "BIRDMOVE_2017#17:10.3@150.1(M.23426)"  "BIRDMOVE_2017#148:8.3@150.1(M.23368)" 
> [37] "BIRDMOVE_2017#105:7.3@150.1(M.23325)"  "BIRDMOVE_2017#103:7.3@150.1(M.23323)" 
> [39] "BIRDMOVE_2017#9:10.1@150.1(M.23516)"   "BIRDMOVE_2017#88:7.1@150.1(M.23408)"  
> [41] "BIRDMOVE_2017#90:7.3@150.1(M.23410)"  

```
# iterate through the tables and count the rows in each table
for (table in DBI::dbListTables(m$con)){
  rows <- DBI::dbGetQuery(m$con, paste0('select count(*) from ', table))
  print(paste0(rows ,' rows in ', table, ' table'))         
}
```

> [1] "370 rows in activity table"
> [1] "1 rows in admInfo table"
> [1] "0 rows in allambigs table"
> [1] "24733 rows in alltags table"
> [1] "24733 rows in alltagsGPS table"
> [1] "148 rows in antDeps table"
> [1] "928 rows in batchRuns table"
> [1] "14 rows in batches table"
> [1] "0 rows in clarified table"
> [1] "0 rows in filters table"
> [1] "0 rows in gps table"
> [1] "24733 rows in hits table"
> [1] "5 rows in meta table"
> [1] "0 rows in nodeData table"
> [1] "0 rows in nodeDeps table"
> [1] "0 rows in projAmbig table"
> [1] "1 rows in projs table"
> [1] "81388 rows in pulseCounts table"
> [1] "47 rows in recvDeps table"
> [1] "42 rows in recvs table"
> [1] "928 rows in runs table"
> [1] "0 rows in runsFilters table"
> [1] "10 rows in species table"
> [1] "0 rows in tagAmbig table"
> [1] "420 rows in tagDeps table"
> [1] "0 rows in tagProps table"
> [1] "396 rows in tags table"

**Comment by jsayers-bsc** [comment] 2021-02-25 16:27
This remains an ongoing issue for me. Sometimes I get the tagDeps and some of the other metadata tables, and sometimes I don't. `forceMeta=T` seems unreliable but I haven't noticed any pattern. I often get both results in the same session, in various order.

**Comment by steffilazerte** [comment] 2021-03-19 21:38
I've been looking into this and have a couple of points which may (or may not!) help narrow in on the problem.

In the example above, where the tagDeps table was empty, it's unusual that the projs table *wasn't* empty, because the tagDeps, tags, species, tagProps and projs metadata is all retrieved through the same API entry point. 

@jsayers-bsc I've added some messages to the tagme() metadata update section in a new branch (which also has the nodeDeps hotfix now).  This gives the following output (Assuming a problem, which I mock created here.):

```
> m <- tagme('SG-1116BBBK0C40', new = F, update = T, forceMeta = T)
Checking for new data for receiver SG-1116BBBK0C40 (deviceID: 1014)
[Metadata Diagnostics]: Requesting 185 tags from server
[Metadata Diagnostics]: Not all tag metadata returned by server:
 - 5230943
[Metadata Diagnostics]: Adding/Replacing
 - 196 'tag' rows
 - 196 'tagDeps' rows
 - 1 'tagProps' rows
 - 18 'species' rows
 - 18 'projs' rows

[Metadata Diagnostics]: Requesting 1 devices from server
[Metadata Diagnostics]: All requested deviceIDs had metadata returned by server
[Metadata Diagnostics]: Adding/Replacing
 - 1 'recvDeps' rows
 - 1 'recvs' rows
 - 3 'antDeps' rows
 - 1 'projs' rows
```

I'm hoping that this will help you see where the problem is occurring i.e. are we not requesting the right tags (perhaps a package issue or a tagme issue), are we not not getting the right tags back (server issue), are the tags not being entered in to the database (package issue). 

If you want to give this a try install this branch (the only change should be more messages when you use tagme())
`remotes::install_github("MotusWTS/motus", ref = "steffi-metadata")`

Let me know if you get any messages that indicate something went wrong (or if something does go wrong and you don't get the message!)

**Comment by jsayers-bsc** [comment] 2021-03-20 20:56
Great, I've installed that and I'll post here as I go along.

**Comment by steffilazerte** [comment] 2021-04-27 21:19
Hi @jsayers-bsc,

I'm not sure this will be much more help, but I think I might have found something related. For some reason, the original function didn't update all tags in the data base, but only tags that had been downloaded in the current session (even when `forceMeta` was TRUE, which I didn't catch). I think that this may have resulted in odd behaviour populating the tables, depending on what the most recent download was.

Would you be interested in testing the hotfix for this? However, I know this is a bit of an intermittent problem, so many not be worth it, as the hotfix will probably be pushed to master soon (I hope!) so you could just wait and update to the newest version when I do so.

If you are interested in testing this now here's the branch to install.

```{r}
remotes::install_github("MotusWTS/motus", ref = "hotfix-JSONbox")
```

**Comment by jsayers-bsc** [comment] 2021-04-28 01:06
Great, seems like there are a bunch of unresolved mysteries related to this particular issue! (Any chance #955 is also related to #929?)

I have installed the hotfix, though I'm on the road for the next day still so don't know when I'll get the chance to test. I'll post anything relevant here and keep watching the other threads.

**Comment by steffilazerte** [comment] 2021-04-30 21:19
The fix has been pushed to master, but I'm going to leave this issue open until we're (reasonably) sure it's been dealt with. Keep me posted once you're back :grin:

**Comment by steffilazerte** [comment] 2021-05-26 18:00
I'm going to get rid of the steffi-metadata branch as I don't think we need that any more, let me know if this issue is still a problem @jsayers-bsc!

**Comment by jsayers-bsc** [comment] 2021-05-26 20:16
I haven't noticed any issues, but I have also been calling `metadata()` explicitly which previously didn't seem to suffer the the problem.

**Comment by steffilazerte** [comment] 2021-05-26 20:55
Well I'll close this issue then, if it happens again, feel free to re-open!

**Closed by steffilazerte** 2021-05-26 20:55 UTC
Labels: R package
