### ISSUE TITLE
Receiver type goes blank after creation

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#66] opened 2017-09-11 21:40 UTC
When making a new deployment, if I fill in all information including receiver type, and click "create new deployment", it removes the receiver type but still seems to create the deployment.

**Comment by pmorrill** [comment] 2017-09-20 14:41
Zoe: I am a little confused about this. The form to create a new recv deployment does not include a field for receiver type.

Can I assume that you are talking about the 'Register a New Receiver' tool?

**Comment by pmorrill** [comment] 2017-09-20 14:44
Ah! Maybe you are talking about the *deployment* type (ie: Dam, Tower, etc). Yes?

**Comment by zcrysler** [comment] 2017-09-20 15:06
Yes, sorry the deployment type, the dropdown menu with dam, tower, pop-tower, etc.

**Comment by pmorrill** [comment] 2017-09-20 18:16
I am unable to reproduce this. Is there a specific deployment type that is not getting saved? I have so far not been able to see this behaviour. Does it only happen on new deployments? Or also when saving existing deployments?

**Comment by zcrysler** [comment] 2017-09-20 18:42
New and existing deployments.  For example, existing deployment ID 4274 in project 2 does not have a "type" selected from the dropdown menu, when I pick a type and save it, it just returns to "--select--".  When I created this deployment it did the same thing, I would enter all the info (including type), click save, and then get a warning that I had not selected the "type".  I would select it and save again, and this time I wouldn't get a warning, but it clearly didn't actually save.

**Comment by pmorrill** [comment] 2017-09-20 18:46
I just checked this (id 4274) in the live system, and was able to save a deployment type (I selected 'Dam'). I was also able to save 'Building'. This is very strange.

**Comment by zcrysler** [comment] 2017-09-20 18:55
Ok, it was still showing up as blank when I refreshed, but logging in and out seemed to work.  I was able to then change it to "existing" while on Chrome, but saving still showed it as blank, checking the deployment in Safari it had actually changed to "existing".  Most other fields will refresh without having to log out and in.  I want it to be "pop-tower" though, and despite which browser I save that in, or how many times I log out/in, it doesn't seem to want to change to that option

**Comment by zcrysler** [comment] 2017-09-20 18:55
I'm on a mac if that makes any difference

**Comment by pmorrill** [comment] 2017-09-20 18:58
Ah! the key is in the value you are after (Pop Tower). When I tried that one, it did not save. The problem with logging in and out can be ignored in this context. At the moment, when person A (me) changes a field, person B (you) will not see the updated version immediately. While this optimizes things in the software, it might become an issue in future. It is NOT related the current bug, though.

I will trace the Pop Tower problem.

**Comment by zcrysler** [comment] 2017-09-20 19:12
Great!

**Comment by pmorrill** [comment] 2017-09-20 19:25
Should be fixed in tomorrow's sandbox and beta3 deployments.

**Closed** 2017-10-25 16:15 UTC
Labels: bug
