### ISSUE TITLE
upload verification not completing with .7z

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#207] opened 2018-04-13 17:26 UTC
A user sent me a .7z file to upload, on both Chrome and Firefox I would get the message "Verify file with identifier:95bdb7f8a24009a58d064682238dec235a4e6407" after verifying, but it would never go past this so I could never complete upload.

I tried opening the .7z file, and compressing as a .zip file and it went through to be processed.

The user hasn't been able to get data from this receiver processed since late August, I don't believe the data was even making it to our server because I don't see any record (user 260, receiver SG-0B38RPI3475B), I'm not sure if it's the same issue or not but he would have been uploading the old way.

As a second issue for the same upload - it appears to have processed with no errors,  but it says:
"File uploaded: 545_2018-04-13T17-15-10.968_whitefish_sept_2017.zip
Will run tag finder on 0 receiver boot sessions
There were no new files in the dataset, so I didn't do anything."

However, I uploaded data for September 2017, there's no data for September in the hourly plots or through tagme() so I don't know why it says there are no new files.

**Comment by Hussell** [comment] 2018-04-14 16:48
I see 20 jobs for user 260 on 2017-12-28, including 4 jobs for receiver SG-0B38RPI3475B. It looks like the file you uploaded is a duplicate of the one uploaded here: https://sgdata.motus.org/status?jobID=111077

That job (and the ones for <a href='https://sgdata.motus.org/status?jobID=111086'>Oct.</a> and <a href='https://sgdata.motus.org/status?jobID=111090'>Nov.</a>) reported no new tag detections, so the new question is "Why not?".

**Comment by Hussell** [comment] 2018-04-14 16:52
Paul may be able to comment on the verification and upload issue.

**Comment by zcrysler** [comment] 2018-04-16 12:38
It didn't report any detections for Sept-Nov, but it also shows no data (ie. no antenna or gps activity or anything at all past August: https://sgdata.motus.org/download/48/SG-0B38RPI3475B-2017_NE-Motus_Whitefish%20Point_hourly_tags.png) in the hourly plot, it looks like no data was ever uploaded for these dates - so was the data actually processed?  If not, can it be re-run?

**Comment by pmorrill** [comment] 2018-04-16 12:44
Zoe: after today's biuld on the beta server, you should again try verifying this file. You
should see the correct message (telling you that the file was already uploaded by
David).

We'll get Denis to push to live once you've tested that.

**Comment by Hussell** [comment] 2018-04-16 14:48
Ready on beta (and sandbox... maybe try there first, just in case?)

I'm investigating the contents of the files uploaded for Sept. - Nov.

**Comment by zcrysler** [comment] 2018-04-16 15:05
Both beta and sandbox are giving the correct message when I try to verify the .7z file:

This file has already been uploaded by David Brinker (2017-11-22 05:18:59; jobID: 130642)

**Comment by Hussell** [comment] 2018-04-17 16:16
Aha! This looks like an instance of https://github.com/jbrzusto/find_tags/issues/48 , which was fixed in early February, so rerunning this receiver should fix everything. Now I just have to figure out how to do that...

**Comment by Hussell** [comment] 2018-04-23 14:07
OK, I've figured out how to rerun jobs, and the hourly plot for this receiver looks correct now.

**Closed by Hussell** 2018-04-23 14:07 UTC
Labels: bug, sgdata
