### ISSUE TITLE
Unable to resolve Unconfirmed Tag Start Date data issue

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#978] opened 2021-05-27 18:15 UTC
Project 372 recently observed while they were trying to resolve data issues that despite their efforts, they couldn't actually fix a "Date Anticipated" error.

The error occurs when an anticipated deployment date is provided, but then that date has passed.

In this case, they created deployments in the past, as have I, and we have both re-run validation. Yet the error persists. https://motus.org/data/issues?id=372#v_tag_confirm_dt

(Likely unrelated, but I'll mention it anyway: Project 372 is one of those who has experienced #970 while trying to test newly registered tags)

**Comment by jsayers-bsc** [comment] 2021-06-29 13:53
Replicated in Project 1. Saving a current or past date for deployment start does not resolve the Issue.

**Comment by cjardine-bsc** [comment] 2021-06-29 17:07
@pmorrill

**Comment by pmorrill** [comment] 2021-06-30 13:06
The field we are considering is confirm_dt_start in tags_deployments table. This is set to 1 if the user must confirm the start date (that is, it was originally entered as a future date). It is set back to zero only after the user has confirmed a current or past start date, AND the species id is not null.

However, it looks like there is a bug so that if a deployment has been terminated (a valid end date exists), the reset never occurs. The three examples of the problem at link shared above are all terminated deployments, so this  bug is preventing the reset, I believe. @jsayers-bsc can you confirm that if a deployment is NOT terminated, the reset DOES occur? I have tested in my dev version and it seems to be ok, but the live version is where we need to check this.

**Comment by jsayers-bsc** [comment] 2021-07-02 17:49
Didn't seem to work for the ones I tried.

But you mentioned where species is not null. All of these mentioned are test deployments, and species is null. Would that be a factor?

**Comment by pmorrill** [comment] 2021-07-02 19:03
Absolutely - if species is null, the deployment stays 'prospective' and the start date is not confirmed.

**Comment by jsayers-bsc** [comment] 2021-07-16 01:05
Can we change this for "Test" deployments, or at least those that don't have a species defined?

**Comment by cjardine-bsc** [comment] 2021-07-22 21:48
I'm slightly confused why test deployments were created in the future (odd), but I have altered the check to ignore the "confirm_dt_start" check when the deployment is a test. 

Go ahead and give it a test and close if you're happy :-)

**Comment by jsayers-bsc** [comment] 2021-07-22 22:48
yeah I'm not sure why they were set that way. Either way, problem solved now. Thanks!

**Comment by jsayers-bsc** [comment] 2021-09-19 14:25
This is still an issue apparently. This is a tag in Project 1 (ID 34441). I've now gone back (yesterday) to update the start date, even modifying it so that it's a day earlier but I still see the error message. 

![image](https://user-images.githubusercontent.com/55001144/133930933-b88fe26a-4442-47c9-bea2-8f621a6db053.png)

It doesn't look like this tag is in the data issues page so maybe there's some other reason this is being triggered and displayed here...

**Comment by pmorrill** [comment] 2021-09-22 19:25
Took a quick look at above example:

https://motus.org/data/tag/deployment/edit?projectID=1&id=22528

But the species is not set, so the behaviour is what I would expect.... (ie: flag will not be cleared by a past start date alone)

**Comment by pmorrill** [comment] 2021-09-22 19:27
Follow-up: I do not recall ever adjusting the code to accommodate 'test' deployments, but I guess you want the flag to clear in all cases where a tag deployment is test? The current logic when the form is saved does not seem to follow that rule.

**Comment by cjardine-bsc** [comment] 2021-09-22 19:32
Yeah, if the deployment is a test and the start date is in the past I would set confrim_dt_start to False. Since a test deployment will never have a species.

**Comment by denislepage** [comment] 2021-09-23 02:14
OK, beta9 merged in live and deployed.

Once the fix is confirmed, issue can be closed.

**Comment by pmorrill** [comment] 2021-09-23 15:29
I checked it on the above tag deployment and a re-save gets rid of the message (since it is a test deployment). @jsayers-bsc  should do a few more checks to verify.

**Closed** 2021-09-23 15:41 UTC
