### ISSUE TITLE
Error with Uploads Page - Project 145

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#399] opened 2018-11-14 15:27 UTC
When navigating tag/receiver upload page (https://motus.org/data/project/sgJobs?projectID=145) there is an error: "An error has occurred while we were processing your request."
Error Ref # = 1542208973876
Exception: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Double

So far, this error only occurs in project 145.

**Comment by Hussell** [comment] 2018-11-14 17:56
Paul, when you're logged in as an administrator you can see the detailed error report at that link. I can confirm that this error doesn't occur on a random selection of other projects.

**Comment by pmorrill** [comment] 2018-11-14 18:10
OK - I will take a look later today, or tomorrow at latest.

**Comment by pmorrill** [comment] 2018-11-14 18:12
Drat - I just closed this issue by mistake! How do we re-open it? My bad, as they say.

**Comment by pmorrill** [comment] 2018-11-15 14:50
I have put a fix in place. This is a rare case where a UNIX timestamp has been interpreted as an Integer, rather than Double, when pulled from the sgServer JSON structure, because it had no 'millisecond' portion probably. I have added a function to deal with this.

**Comment by denislepage** [comment] 2018-11-15 21:02
Seems to work now.

**Closed by denislepage** 2018-11-15 21:02 UTC
Labels: beta, bug
