### ISSUE TITLE
Receivers without activity tables?

### ISSUE THREAD

**Issue by adamdsmith** [MotusDev/Motus-TO-DO#697] opened 2020-03-05 01:41 UTC
Any reason some receivers would not produce `activity` tables?

I'm running `motus@beta3` package, and pulling the data into a new local db.

In particular, the following are not returning any activity table:
- SG-BC3FRPI35A70
- SG-CEB1RPI3C0D0

**Comment by cjardine-bsc** [comment] 2020-03-05 17:35
Interesting. Those receivers do have activity in the database table for batch IDs 

906450,
906453,
906454,
906455,
906456,
906457,
906458,
906459,
932112,
791692,
791693,
791694,
791695,
791696,
791697,
932120

Looks like the issue is that the data is not making it through to you. Can you provide details on what call you're using to pull in the data. 

Note that there are a few batches that have been re-run for these receivers. Those have been deprecated and removed from the activity table.

**Comment by adamdsmith** [comment] 2020-03-05 17:50
Sure, taking the first receiver as an example:

```r
db <- tagme("SG-BC3FRPI35A70", new = TRUE, update = TRUE, forceMeta = TRUE)
```

Returns 14 batch records:
906448,
906449,
906450,
906451,
906452,
906453,
906454,
906455,
906456,
906457,
906458,
906459,
932112,
932113

But indicates `activity:     0 batch records to check`...

Thus, the following returns an empty table...

```r
tbl(db, "activity")
```

**Comment by cjardine-bsc** [comment] 2020-03-05 17:54
Okay, I wonder if we haven't built this into the receiver tagme function. @steffilazerte could you take a look at this? 

The Batches Activity table does return records for the batches Adam lists above: 

SELECT *
  FROM [motus].[dbo].[vwR_Batches_activity]
 where batchID in (906448,
906449,
906450,
906451,
906452,
906453,
906454,
906455,
906456,
906457,
906458,
906459,
932112,
932113
) 

So the problem appears to be in the R package. 

Thanks!

**Comment by adamdsmith** [comment] 2020-03-05 18:06
FYI, I retried with the `motus@master` branch and using admin privileges. No difference. 

And it's only some receivers. I get activity tables for most receivers...

**Comment by steffilazerte** [comment] 2020-03-06 23:30
Sorry for the delay! I think I've fixed this in the beta3 branch. There was a bug that resulted in the `activity` (and `nodeData`) functions stopping if the first batch returned 0 activity/nodeData hits. This is why some receivers had problems but others did not. Is there a project that definitely has `nodeData` that I could get access to, just to make sure the `nodeData` is responding as it should as well?

**Comment by adamdsmith** [comment] 2020-03-07 02:14
Thanks! Don't have any `nodeData` for you, but can confirm that `beta3` branch is grabbing `activity` tables where it wasn't before!

**Comment by cjardine-bsc** [comment] 2020-03-09 19:36
No Node data from vwR_Metadata_for_receivers_nodeDeps yet. 

Project 207 has data in vwR_Node_data_for_tag_project

**Comment by steffilazerte** [comment] 2020-03-11 14:51
Could someone either test the `nodeData` download or give me access to project 207? (On beta at least). Thanks!

**Comment by steffilazerte** [comment] 2020-04-13 15:47
To close this issue, I'd like to test the downloads of `nodeData`. @cjardine-bsc could you give me access to project 207 for beta? Thanks!

**Comment by cjardine-bsc** [comment] 2020-04-13 17:28
Okay, I think you should be able to try now.

**Comment by steffilazerte** [comment] 2020-04-22 21:41
Great thanks, this all looks good now.

**Closed by steffilazerte** 2020-04-22 21:41 UTC
Labels: R package, beta, bug
