### ISSUE TITLE
processing issue SG-2616BBBK1111

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#220] opened 2018-04-25 19:07 UTC
Project 1, jobID 176272 was processed with no errors, but there were no products produced (no hourly plots: https://sgdata.motus.org/download/1/).  There should be data up to April 23rd.

An additional issue with this receiver is that it's one of the ones that has a duplicate serial number in project 14, with both active at the same time.  I'm not sure how this is dealt with in the system, but downloading that receiver through tagme() gets detections between 2017-08-06 and 2018-03-05, most are labelled as the deployment in project 14, but the detections from 2018-03-05 are labelled as the project 1 deployment.  Also, a number of metadata associations are incorrect, for example a bunch of detections on 2017-09-19 have GPS coordinates right where the project 1 deployment is, but all the receiver metadata is for the project 14 deployment.

So two issues: 1) the most recent upload for this receiver in project 1 was not processed correctly and 2) This is a duplicate receiver that is not being dealt with properly, this has been an ongoing issue with a few other pairs that I'm now pretty worried aren't being handled properly.  There's documentation for some of these in various places but this might be a new duplicate:
https://github.com/jbrzusto/TO_DO/issues/176
https://github.com/jbrzusto/TO_DO/issues/126
https://github.com/jbrzusto/TO_DO/issues/120

**Comment by jbrzusto** [comment] 2018-09-12 16:28
I don't think there are really two receivers here.  This looks like a redeployment of a receiver,
but with scrambled start/end dates in the metadata.

There are two deployments for SGs with serial number SG-2616BBBK1111:

```
$ meta -header "select * from recvDeps_ where serno glob 'SG-2616*'"
```
gives 

id|serno|receiverType|deviceID|status|deployID|name|fixtureType|latitude|longitude|isMobile|tsStart|tsEnd|projectID|elevation
---|---|---|---|---|---|---|---|---|---|---|---|---|---|---
2118|SG-2616BBBK1111|SENSORGNOME|1017|active|4004|UWO-SSC|Building|43.0096|-81.2755|0|2017-05-08 10:59:10||1|
2339|SG-2616BBBK1111_1|SENSORGNOME|1077|terminated|4488|BIWF|Existing|41.1257|-71.5075|0|2017-08-03 00:00:00|2018-01-01 00:00:00|14|30.0

The set of all files we have with this serial number (and I verified that this is *all* files by  looking directly at the archives uploaded by users for project 14 and project 1) suggests these deployment records are not accurate:

- from July 11-13, 2017, a unit with serno SG-2616BBBK1111 and funcubes in ports 1,3,5,7 is at compudata.ca (boot sessions 21-38)

- from Aug 3 to Sept. 14, 2017, a unit with serno SG-2616BBBK1111 and funcubes in ports 1,3,5,7 is at 41.1258,-71.5075, which matches the deployment under project 14.  (boot sessions 39-50)

- from Sept. 15, 2017  to April 23, 2018, a unit with serno SG-2616BBBK1111 and funcubes in ports 1,2,3,4 is at 43.009591667,-81.275736 which matches the deployment under project 1. (boot sessions 9 to 14). 

It seems very unlikely that one unit was apparently retired the day before another unit with the same beaglebone serial number was deployed. It seems more likely to me the unit was transferred between users (and re-imaged, causing boot counts to be reset to 1).

So I'm correcting the deployment records like so:

```sql
sqlite> update recvDeps set tsStart=0+ strftime("%s", datetime('2017-09-15 00:00:00')) where id=2118;
sqlite> update recvDeps set serno='SG-2616BBBK1111', deviceID=1017, tsEnd=0+ strftime("%s", datetime('2017-09-14 23:59:59')) where id=2339;
```
so that the deployment records now look like this:
```sql
> select * from recvDeps_ where serno glob "SG-2616*";
id|serno|receiverType|deviceID|status|deployID|name|fixtureType|latitude|longitude|isMobile|tsStart|tsEnd|projectID|elevation
2118|SG-2616BBBK1111|SENSORGNOME|1017|active|4004|UWO-SSC|Building|43.0096|-81.2755|0|2017-09-15 00:00:00||1|
2339|SG-2616BBBK1111|SENSORGNOME|1017|terminated|4488|BIWF|Existing|41.1257|-71.5075|0|2017-08-03 00:00:00|2017-09-14 23:59:59|14|30.0
```
Can someone please make these deployment changes on motus.org?
Also, there is no longer a separate device with ID=1077; i.e. no SG-2616BBBK1111_1

Results:  https://sgdata.motus.org/status?serno=SG-2616BBBK1111

**Comment by denislepage** [comment] 2018-09-12 21:02
Should now be done.

I also modified the batches table to refer to the correct motusDeviceID, etc.

p.s.

There’s an issue here with the summaries that will need addressing:

EXEC prTaghitsSummariesSensorID 2118

Msg 512, Level 16, State 1, Procedure prTaghitsSummariesSensorID, Line 10
Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.

**Comment by jbrzusto** [comment] 2018-09-13 15:31
Now one of the deployment records is for the wrong project:
```sql
> select * from recvDeps_ where serno glob 'SG-2616*';
id          serno            receiverType  deviceID    macAddress  status      deployID    name        fixtureType  latitude    longitude   isMobile    tsStart                  tsEnd       projectID   elevation 
----------  ---------------  ------------  ----------  ----------  ----------  ----------  ----------  -----------  ----------  ----------  ----------  -----------------------  ----------  ----------  ----------
2118        SG-2616BBBK1111  SENSORGNOME   1017        0           active      4004        UWO-SSC     Building     43.0096     -81.2755    0           2017-09-15 00:00:00.000              1                     
2118        SG-2616BBBK1111  SENSORGNOME   1017        0           terminated  4488        BIWF        Existing     41.1257     -71.5075    0           2017-08-03 00:00:00.000  2017-09-15  1           30.0      
```
the record with `deployID=4488` should have projectID=14, not projectID=1 (see the query result from a few comments back)

Also, there's a bogus-looking record for the non-existing `_1` version of the receiver:
```R
> a=motusListSensorDeps(projectID=14)
> subset(a, serno=="SG-2616BBBK1111_1")
      id             serno receiverType deviceID macAddress  status deployID
124 2339 SG-2616BBBK1111_1  SENSORGNOME     1077          0 pending       NA
    name fixtureType latitude longitude isMobile tsStart tsEnd projectID
124 <NA>        <NA>       NA        NA    FALSE      NA    NA        14
    elevation antennas
124        NA     NULL
> 
```

**Comment by jbrzusto** [comment] 2018-09-14 12:31
Thanks!

**Comment by zcrysler** [comment] 2018-09-20 17:37
I'm not sure this has been resolved. The original data upload that sparked this was for jobID 176272 (https://sgdata.motus.org/status?jobID=176272), this was uploaded for a receiver in Ontario as part of project 1 and the raw data files show it's serial number is SG-2616BBBK1111. But now the deployment for that receiver is missing from project 1, was this deleted during the fixes above? It should still be present in project 1

**Comment by leberrigan** [comment] 2018-11-02 13:39
I just got an email from user of Proj 14 who is confused about the deployment 'UWO-SSC' in London ON. They claim it is not one of their deployments and is worried it will interfere with their data set. Deployment dates do not overlap, but suggest they were deployed immediately after each other even though BIWF is on an island ~850 KM away from UWO-SSC.

This is likely an issue with duplicate SG ID's.

BIWF		2017-08-03 00:00 - 2017-09-14 23:59	41.1257	-71.5075
UWO-SSC		2017-09-15 00:00 - 2018-05-15 23:59	43.0096	-81.2755
BIWF		2017-05-16 00:00 - 2018-10-01 23:59	41.1257	-71.5075

**Comment by jbrzusto** [comment] 2018-12-12 18:17
My bad - this is indeed a serial number collision, confirmed by now seeing data from the second SG-2616BBBK1111.

**Comment by Hussell** [comment] 2019-02-12 14:54
Ok, Stu has new data to upload for one of these receivers, and wanted me to make certain this was sorted out, but I find myself confused. We've got three duplicates in sensors_hash_keys:
deviceId   serialNumber
1017	SG-2616BBBK1111
1077	SG-2616BBBK1111_1
1219	SG-2616BBBK1111_2

And two in sensors:
sensorId projectId serialNumber
2118	14	SG-2616BBBK1111
2874	0	SG-2616BBBK1111_2

And as far as I can tell, the changes Denis made to the deployments were never undone.

**Comment by Hussell** [comment] 2019-02-15 20:27
There's an entry in /sgm_local/motus_meta_db.sqlite, table serno_collision_rules:
id 4
serno 'SG-2616BBBK1111'
cond 'bootnum < 3 | prefix == "UWO_SSC"'
suffix '_1'

I _think_ this is still what's being used to disambiguate, and maybe the triggering condition needs to be updated?

**Comment by denislepage** [comment] 2019-02-15 20:44
OK, I think we now have the metadata right.
SG-2616BBBK1111 is Pam's project 14 receiver, which has 2 deployments (2017 and 2018)
SG-2616BBBK1111_1 is Motus's project 1 receiver at UWO, which has 1 deployment (2017-2018)

Jeremy suggested that Stu should upload his file and see what happens.

**Comment by StuMackenzie** [comment] 2019-02-15 21:22
I've added a new deployment to cover the current period and we'll be uploading data hopefully within the next 24h

**Comment by Hussell** [comment] 2019-02-20 15:59
The deployment records and hash keys seem to be correct now. However, on sgdata the files for the project 1 receiver are still in the file repo for the project 14 receiver. I'm not sure whether or not I can just move them to the correct repo and do a full rerun to correct that. John?

Once that's fixed, we're going to have to delete the batches assigned to the project 14 receiver for 2017-09-05 to 2018-04-23. (Or assign them to the project 1 receiver? Are we going to stick to the "don't delete batches" policy in this case?)

**Comment by cjardine-bsc** [comment] 2019-02-21 00:08
I'd like to assign them to the correct device ID and then deprecate any duplicates. 

I'm a data pack-rat. Think there's a reality TV show for that?

**Comment by denislepage** [comment] 2019-02-21 00:38
I am not sure I understand why this matter. My instinct is that we don’t need to delete or re-run the batches, and simply rather change the device ID’s assigned to those batches and relink to the correct deployments. There may be another reason that I am missing?

**Comment by Hussell** [comment] 2019-03-08 15:03
Ok, files are all in the right places, and the receivers have been rerun, so there should be up-to-date batches for both receivers. Last task (I think) is to reassign some batches currently belonging to the receiver in project 14 (no underscore) to the receiver in project 1 (with underscore). The batches are those covering the dates from 2017-09-15 to 2018-04-23, inclusive.

**Comment by cjardine-bsc** [comment] 2019-03-08 17:22
Okay. That means I've updated the following BatchIDs from deviceID 1017 to 1077

185103
158620
264868
264869
158621
185104
185105
158622
264870
264871
158623
185106
185107
158624
264872
264873
158625
185108

**Comment by Hussell** [comment] 2019-03-08 20:50
I think you can hit the Close button on this.

**Comment by cjardine-bsc** [comment] 2019-03-08 20:53
Ha! Thanks for sharing the Close-Button-Satisfaction. 

Muhahaha....closed.

**Closed by cjardine-bsc** 2019-03-08 20:53 UTC
Labels: bug, done, sgdata
