### ISSUE TITLE
Incorrect lat lon format while uploading tag deployment throws no error

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#677] opened 2020-02-12 17:18 UTC
Lat Lon format while doing a bulk tag deployment upload is supposed to be decimal degrees. Recently someone thought they were entering the proper format, but they included the cardinal directions: 

13.238 N	86.0531 W

The records were not updated with the Lat Lon, but neither was there any error or warning message due to the incorrect format. I just tried and got a message saying there were no errors, and no updates were made to the db. Modifying them to remove the direction worked as expected

**Comment by pmorrill** [comment] 2020-02-12 21:36
I took a quick look at this C, ad I don't do much in the way of data validation in the java code.... It is inserted into the import table and then left to your devices. But I do check for interpretation as a double value, for long and lat.

@jsayers-bsc could you send me the file that was imported with the problem values?

**Comment by cjardine-bsc** [comment] 2020-02-12 23:38
Can I also get the projectID so I can look into it on my end?

**Comment by jsayers-bsc** [comment] 2020-02-13 14:59
email sent

**Comment by pmorrill** [comment] 2020-02-13 20:25
I traced this in my dev version, and the java seems to be handling this correctly: the parse-to-double fails, and the code then adds a record into api_errors. The code is `api_dbl_convert`.

Catherine: can you look for those errors in the table? Maybe our error capture is failing somehow.

**Comment by cjardine-bsc** [comment] 2020-02-14 20:09
Looks like there have been three uploads for this project. In the first two batches (which I assume had the "N" and "W") the lat/lon columns are NULL in the DB. So the data is not being written to the api_tags_deployments table (the table accepts nvarchar(Max) for the lat/long fields).

Paul the API for this is writing directly to the table right? Not using an insert proc? I might have to volley this one back to you.

**Comment by pmorrill** [comment] 2020-02-14 20:35
Hmmm. None of those records were written? At all?

**Comment by cjardine-bsc** [comment] 2020-02-14 20:36
The records were written, the lat long fields were not.

**Comment by pmorrill** [comment] 2020-02-14 20:55
aha. OKeedokee. Will sleuth it out.

**Comment by pmorrill** [comment] 2020-02-21 19:23
I have looked at this some and find that when a decimal (or integer) in the uploaded file fails to parse as such, no value is stored in the database table (api_tag_deployments). However, an error record is placed in 'api_errors'. But these error records are later scrubbed out when prAPIValidateTagDeploy is called, and no error is reported to the user.

I feel like we had this discussion many moons ago, and set it up that way on purpose,

However, I experimented with a change, in which the value of the field **is** placed in the api_tag_deployments' table, even though it does not parse as a decimal (eg: 86.0531 W). But I don't see any improvement (except that the bad long and lat values are now in the api_tag_deployments table). There is still no error reported to the user in my system. And, the api_errors records are still gone after the validation proc is run.

Confused by this? Me too. I do not recall precisely how this workflow is set up, but it seems that the data is stored in [api_import_tag_deployments] then only transferred to the live when the user clicks the 'Complete upload' button. That makes sense, it seems that the validation procedure is ignoring the error records in api_errors and also not noticing the bad decimal value in the imported data (when I make sure it is indeed in place).

Catherine, can you help? Before all my hair is gone?

**Comment by pmorrill** [comment] 2020-02-21 19:29
BTW: just to be clear. I have not updated any java code. The bad longitude and latitude values are still not being placed in the [api_import_tag_deployments] table. I guess I could do that on the sandbox if we want to experiment with this issue there, then decide on the best approach. But it seems to me that since the api_errors table is being used to store the error caused by parse failure, the first line of attack here is to see why those api_errors records are being scrubbed, rather than carried through to the user somehow.

**Comment by denislepage** [comment] 2020-02-21 19:48
The proc [prAPIValidateTagDeploy] removes any api_error records associated with the apiBatchID at the start of the code, so I think what you are seeing is the expected behaviour from the point of view of that proc.

Essentially, if we want to insert errors into that table outside of the proc, we need to flag them in a way that prevents them from being scrubbed. Perhaps adding an error source field to track the origin.

I guess I am unclear of the flow though. Is there actually a need to delete any existing records at the top of the proc? Is this proc run only once for any given batch, or multiple times?

**Comment by denislepage** [comment] 2020-02-25 18:21
To reiterate, the validate proc does scrub any previous entries related to that batch as the first step, so anything inserted by the Java will disappear, so that mystery is solved.

Fixing this is easy (removing the delete statement), but my question is whether we ever need to re-run validation on the same batch after it is edited. If we need to keep some sort of deleting of the errors to allow re-processing of the validation, then we need to sort out at which point it needs to happen. The current system obviously needs fixing.

**Comment by cjardine-bsc** [comment] 2020-03-05 23:36
@jsayers-bsc could you test this on the sandbox page and make sure that error is now caught properly?

**Comment by jsayers-bsc** [comment] 2020-03-06 20:13
![image](https://user-images.githubusercontent.com/55001144/76119254-0d035000-5fbd-11ea-84c2-b18098af3f99.png)

That looks about right!

**Comment by cjardine-bsc** [comment] 2020-03-06 20:20
Good. Posted to live.

**Closed by cjardine-bsc** 2020-03-06 20:20 UTC
Labels: Motus website, bug
