### ISSUE TITLE
upload issue project 3

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#295] opened 2018-07-18 01:20 UTC
User got the following message when trying to upload via motus.org:

Le serveur a signalé l'erreur suivante: non-existent file: `NAS:/sgdata//sgm/uploads/partial//2498_2018-07-17T14-23-27.426_SGdata_Pte <e0> la Loupe RNF_20180610 au 20180712.zip`

Additionnally, when I logged out, I receive this one:

Une erreur s'est produite pendant le traitement de votre opération.
Cette erreur a automatiquement généré un courrier électronique envoyé aux employés du support technique de ce site. Nous examinerons ce problème et tenterons de le résoudre dès que possible. Il est possible que cette erreur ait été causée par un problème temporaire et que vous ne receviez pas cette erreur de nouveau. Le cas échéant, l'opération que vous avez tenté d'effectuer devrait réussir si vous essayez encore. Si celle-ci échoue de nouveau, il est probable qu'il y ait un problème que nous devrons résoudre.
Si vous désirez communiquer avec nous à propos de cette erreur, veuillez fournir ce numéro de référence : 1531839918834

What would have caused this?

**Comment by denislepage** [comment] 2018-07-18 01:22
This looks linked to the error that I have been receiving regularly for the last week or so. Paul made a fix today which should be on beta tomorrow. If you are able to replicate the steps, that would be a good one to test the fix once deployed.

Error reference number: 1531839918834
________________________________
Exception:

java.lang.NullPointerException

Stack trace:
File Name

Line Number

Class Name

Method Name

Native Method?

SgJobsServlet.java

62

org.bsc.motus.web.SgJobsServlet

doGet

false

HttpServlet.java

622

javax.servlet.http.HttpServlet

service

false

HttpServlet.java

729

javax.servlet.http.HttpServlet

service

false

ApplicationFilterChain.java

291

org.apache.catalina.core.ApplicationFilterChain

internalDoFilter

false

**Comment by denislepage** [comment] 2018-07-23 19:59
I have deployed the fix to live, if you can figure out how to test it, Zoe.

**Comment by zcrysler** [comment] 2018-07-23 21:15
Ah I just posted this as a second issue: https://github.com/MotusDev/Motus-TO-DO/issues/301! Too much going on last week. But the issue is still going on in live as you can see in issue 301

**Comment by zcrysler** [comment] 2018-07-23 21:17
I had him send me the original file, I logged in as him and uploaded on the English site. After verification I had a message that a partial copy already existed so I clicked "continue upload" and it went through fine.

They then tried to upload another file and they got the same error. I again logged in as them but this time on the french site and got the same results with the same error. I'm not sure if it's related to the French/English sites, and haven't tried uploading the file to the English site this time in case you wanted the file before upload finished properly. I did go through the verification step, and it said it was a new file, I didn't try to re-upload.

Project 3

**Comment by pmorrill** [comment] 2018-07-24 11:36
OK - transfer the file to me, and I'l test.

**Comment by pmorrill** [comment] 2018-07-24 20:11
The following error is generated by the SG server (It can't locate the file after it is uploaded and transferred to the processing folder):

> Le serveur a signalé l'erreur suivante: non-existent file: NAS:/sgdata//sgm/uploads/partial//2498_2018-07-17T14-23-27.426_SGdata_Pte <e0> la Loupe RNF_20180610 au 20180712.zip

Denis: can you look for this file and see if it exists on the NAS drive, and what it's name is there? I can see that the accented letter 'a' is garbled in this message. The filename sent to SG should have been ok, but the SG server was not able to 'see' the file.

The actual file name should be:

688_2018-07-24T19-44-59.201_SGdata_Pte à la Loupe RNF_20180610 au 20180712.zip

**Comment by denislepage** [comment] 2018-07-25 02:21
Yes, it looks correct in the partial folder.

There are several files from various attempts. The one with ** is the one you asked about:

2498_2018-07-23T21-06-47.524_SGdata_Pte à la Loupe RNF_20180610 au 20180712.zip
2498_2018-07-21T14-32-47.214_SGdata_Pte à la Loupe RNF_20180610 au 20180712.zip
2498_2018-07-21T13-51-48.410_SGdata_Pte à la Loupe RNF_20180610 au 20180712.zip
2498_2018-07-17T18-03-16.77_SGdata_Pte à la Loupe RNF_20180610 au 20180712.zip
2498_2018-07-17T14-23-27.426_SGdata_Pte à la Loupe RNF_20180610 au 20180712.zip **
2498_2018-07-16T22-58-00.388_SGdata_Rivière-Ouelle_20180711 au 20180715.zip
2498_2018-07-16T22-25-07.29_SGdata_Rivière-Ouelle_20180706 au 20180710.zip
2498_2018-07-16T19-31-50.938_SGdata_Rivière-Ouelle_20180701 au 20180705.zip
2498_2018-07-16T18-59-01.854_SGdata_Pte à la Loupe RNF_20180610 au 20180712.zip
2498_2018-07-16T16-05-54.826_SGdata_Rivière-Ouelle_20180611 au 20180630.zip
2498_2018-07-16T14-00-49.54_SGdata_Rivière-Ouelle_20180522 au 20180610.zip
2498_2018-07-16T12-56-30.994_SGdata_St-André_20180522 au 20180715.zip
2498_2018-07-13T19-51-02.212_SGdata_Pte à la Loupe RNF_20180610 au 20180712.zip
2498_2018-07-12T22-02-42.839_SGdata_Pte à la Loupe RNF_20180610 au 20180615.zip

**Comment by zcrysler** [comment] 2018-07-26 15:53
I've got a couple more files to upload for this project if testing is needed

**Comment by pmorrill** [comment] 2018-07-26 16:21
Ok. I will take a second look after lunch, and get back to you. I can't see any reason why the language would be an issue, but it is one possibility.
I'll write more shortly.


Sent from my smartishphone.
-------- Original message --------From: zcrysler <notifications@github.com> Date: 2018-07-26  11:53 AM  (GMT-05:00) To: MotusDev/Motus-TO-DO <Motus-TO-DO@noreply.github.com> Cc: pmorrill <paul@ravenforge.ca>, Comment <comment@noreply.github.com> Subject: Re: [MotusDev/Motus-TO-DO] upload issue project 3 (#295) 
I've got a couple more files to upload for this project if testing is needed

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MotusDev/Motus-TO-DO","title":"MotusDev/Motus-TO-DO","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/MotusDev/Motus-TO-DO"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zcrysler in #295: I've got a couple more files to upload for this project if testing is needed"}],"action":{"name":"View Issue","url":"https://github.com/MotusDev/Motus-TO-DO/issues/295#issuecomment-408144999"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MotusDev/Motus-TO-DO/issues/295#issuecomment-408144999",
"url": "https://github.com/MotusDev/Motus-TO-DO/issues/295#issuecomment-408144999",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [MotusDev/Motus-TO-DO] upload issue project 3 (#295)",
"sections": [
{
"text": "",
"activityTitle": "**zcrysler**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@zcrysler",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"MotusDev/Motus-TO-DO\",\n\"issueId\": 295,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"MotusDev/Motus-TO-DO\",\n\"issueId\": 295\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/MotusDev/Motus-TO-DO/issues/295#issuecomment-408144999"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 357510410\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by pmorrill** [comment] 2018-07-26 16:42
My testing, which I did within my development environment, in both EN and FR, looked ok, but it did not include the actual processing of the file on the SG server. My FR environment may also be somewhat cobbled by missing translations, though I tried to get them up to date.

The fact that Denis was able to see the file on the 'partial' folder tells us that the file did upload, but the error msg from the SG server tells us it was unable to locate the file. So either we are garbling the file name in signalling to the SG server, or the SG server is garbling it somehow. I suspect the garbling is related to the accented character in the file name.

But stepping back a bit, what I see as unusual about this failing upload is a) that the file name itself includes FR characters and b) that the user (and yourself) couldn't make it work while within the FR language environment. We need to separate these two things.

First, research: have you seen successful uploads of files with FR characters? Have you seen successful uploads by people using the FR environment?

Since you have a few files to try, I'd suggest this:

If any of the files do not have FR characters in them, try uploading them via the FR environment, preferably as the specific user. If they fail, then try uploading them in the EN environment.

For any files that DO have FR characters, try uploading in the FR environment. If that fails, try renaming the file slightly to remove the FR character, then attempt the same upload. If it still fails, try it in the EN environment.

**Comment by zcrysler** [comment] 2018-07-26 17:18
Ok, logged in as Yves:
- I uploaded file "SGdata_Pte à la Loupe RNF_20180712 au 20180725.zip" to the FR site, it verified fine, and uploaded to 100% then said "Le serveur a signalé l'erreur suivante: non-existent file: `NAS:/sgdata//sgm/uploads/partial//2498_2018-07-26T17-13-01.175_SGdata_Pte <e0> la Loupe RNF_20180712 au 20180725.zip`"
- renamed the file to "SGdata_Pte a la Loupe RNF_20180712 au 20180725" and uploaded to the French site and it processed fine

**Comment by pmorrill** [comment] 2018-07-26 17:30
Excellent result. Now. Let's try another file, but upload via EN environment, without changing the name. That is: leave the accented char in place......

**Comment by zcrysler** [comment] 2018-07-26 17:36
English site with an accent results in the same error
The server has reported the following error: non-existent file: `NAS:/sgdata//sgm/uploads/partial//2498_2018-07-26T17-35-59.999_SGdata_Rivi<e8>re-Ouelle_20180522 au 20180610.zip`

file name was "SGdata_Rivière-Ouelle_20180522 au 20180610.zip"

**Comment by pmorrill** [comment] 2018-07-26 17:38
OK - let's be certain. Change the name slightly to remove the chars and retry on EN side. Thanks for this.

**Comment by zcrysler** [comment] 2018-07-26 17:44
uploading "SGdata_Riviere-Ouelle_20180522 au 20180610.zip" to English site worked fine

**Comment by denislepage** [comment] 2018-07-26 18:04
It looks like the problem is on the SG side with the handling of accents and special chars.

Could we ANSI-encode the file names being uploaded, rather than wait for a fix on SG?

I don’t think the other issues with file names WITHIN the archive is something we can address from this end, but that one possibly can be? Are the data processing ok within those renamed archives? Do they contain files that have themselves accents?

**Comment by pmorrill** [comment] 2018-07-26 18:07
It is also possible that my encoding of the name within the JSON package I send to SG server is at fault (unless you have other reason to suspect the SG server handling?). I want to check that first. Hopefully this afternoon.

**Comment by denislepage** [comment] 2018-07-26 18:08
OK, thanks. That could well be.

**Comment by pmorrill** [comment] 2018-07-26 18:36
The JSON library has never given us issues before, in encoding strings. But I am not sure how far we have tested it.

All the same: do you have a suggestion for a substitution function, to remove / hide those characters? I am not sure if we are just getting rid of anything that is non-ascii? Or should we go further and remove any non-alphanumeric characters as well?

**Comment by zcrysler** [comment] 2018-07-26 18:48
The files look like they process well after you rename, the hourly plots contain all the dates uploaded

**Comment by pmorrill** [comment] 2018-07-26 18:54
Let's sit on those two other files for today, if that is ok. Unless the PI is chomping at the bit?

**Comment by zcrysler** [comment] 2018-07-26 18:58
I don' think so, but he's hoping to do weekly uploads and has just started sending me the files rather than seeing the error, so the sooner it's resolved the sooner he can upload himself

**Comment by pmorrill** [comment] 2018-07-26 20:02
I am working on a fix right now. I just want to have those files to test with, maybe tomorrow (hopefully)

**Comment by zcrysler** [comment] 2018-07-26 20:19
You want me to send you the ones I haven't uploaded yet?

**Comment by pmorrill** [comment] 2018-07-26 20:31
No. Best is for you to test them in beta tomorrow, once I have the change in place. I'll let you know.

**Comment by denislepage** [comment] 2018-07-26 20:37
I don’t know if you are able to deploy to beta yourself, but I can do it when you need.

**Comment by pmorrill** [comment] 2018-07-26 20:47
Denis: I am going to do the following with the file name, just before I copy it to the partial folder (and then signal the SG server):

> String cleanFileName = fileName.replaceAll("[^\\p{ASCII}]", "").replaceAll("\\s+","_");

Note that I am replacing spaces with underscores as well, which is not necessary. But since the SG is unix, it'll make it more 'unix-like'

**Comment by zcrysler** [comment] 2018-07-26 21:01
The data for Rivière Ouelle processed correctly, but I realized I accidentally uploaded Pte à la Loupe to the wrong project (project 15 instead of 3), and there was no output created: https://sgdata.motus.org/status?jobID=195611. There should at least be antenna's showing up in a plot. Was nothing created because it's the wrong project or did something happen with this processing?

**Comment by denislepage** [comment] 2018-07-26 21:11
I think that’s fine. I wasn’t familiar with the \p{ASCII} notation. Cool. To be safer, I might even limit it further, as there are a number of ASCII characters that could still spell trouble across platforms (e.g. : is allowed in Linux, but not windows). \w for instance covers [a-zA-Z_0-9], to which we also need to add the period, and maybe the hyphen. Any other characters we should keep?

I think you may need double escaping here? You can test this, but I think it covers most of the common characters people will use. I’d probably replace the non ascii chars by underscore, too.

String cleanFileName = fileName .replaceAll("\\s+","_").replaceAll("[^\\w\\.\\-]", "_")

A timestamp is also added to the file name to ensure its uniqueness as well, so in theory there is nothing of the original file name that we NEED to preserve, correct? I’m not suggesting we do away with it, simply confirming that it doesn’t matter if we mangle it, other than the user may ideally need to be able to recognize them. The examples today suggest that it will work.

I meant to respond earlier that URL-encoding methods might worth, but there would be a risk, depending how they are dealt with. If we saved the file with %20 instead of spaces, and then send the file name to SG with %20, will it be interpreting this and looking for a file name with a space or %20? I therefore like your approach better.

**Comment by denislepage** [comment] 2018-07-26 23:54
The job associated with the latest upload contains only 2 batches, both of which have 0 detection (10 Jun to 12 Jul and 12 Jul to 25 Jul). 

They have, however, good amounts of pulses on 4 antennas, suggesting that processing is happening. Could they not simply have no tag data? The majority of batches don't.

The fact that is was sent to the wrong project shouldn't matter (I hope).

**Comment by pmorrill** [comment] 2018-07-27 11:18
The latest upload seems to have worked fine. The filename has the accented char replaced, and all spaces were replaced with underscores.

We can deploy this to live. The further refinements to the the regex can wait, I think. I'm fine with replacing everything other than alphanumerics (and period), though I'd use this:

>  String cleanFileName = fileName.replaceAll("[^\\w\\.\\-]", "_").replaceAll("\\s+","_");

(do the space replacement last to get rid of multiple spaces in a row)

**Comment by zcrysler** [comment] 2018-07-27 19:11
Let me know when it's been deployed to live and I can test and let Yves know

**Comment by denislepage** [comment] 2018-07-27 20:05
OK, pushed to live.

**Closed** 2018-07-27 20:15 UTC

**Comment by denislepage** [comment] 2018-07-28 01:20
\w doesn’t cover spaces (but does cover _), so the second part would do nothing?

In the code you sent, all spaces would be replaced by nothing. The first replaceAll would apply before the second, right? I’d also replace invalid characters by _ everywhere, instead of empty spaces.


String cleanFileName = fileName .replaceAll("\\s+","_").replaceAll("[^\\w\\.\\-]", "_")
