### ISSUE TITLE
Error: "Your credentials did not authenticate on the SensorGnome service" when trying to upload detection/registration data

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#649] opened 2020-01-02 14:14 UTC
User on Project 184 notified last week that when he tried to upload detection data, he was met with an error message at the top of the page: "Your credentials did not authenticate on the SensorGnome service.". He was able to log in but when he tried to verify his file, the verification process just hung and never completed. He tried a few times a couple days apart and got the same issue.

Today I tried uploading tag registration data and found I was getting the same issue. No problem logging in and navigating the rest of motus.org but when I clicked on "Upload Detection Data" I found the same error, and had the same verification hanging. 

![image](https://user-images.githubusercontent.com/55001144/71670837-44484d00-2d3f-11ea-95d3-65dfd9c1220f.png)

This error was mentioned in this [issue ](https://github.com/MotusDev/Motus-TO-DO/issues/325).

**Comment by Hussell** [comment] 2020-01-02 17:07
It turns out this is happening because the clock(s) on the Motus website server(s) are out-of-sync with the rest of the world. Sometime on Dec 29/30 the difference exceeded 10 minutes, which is the maximum amount of difference the API is willing to accept. Since then all API queries have been failing unless the calling code retries using the date-time the API sends back in the error message.

I've emailed Denis and Catherine to see if either of them can resynch the clocks.

**Comment by Hussell** [comment] 2020-01-02 17:13
I'm marking this as "important" because it's preventing sgdata updating its metadata cache, which means I'm going to have to rerun everything from Dec 29th until this is fixed. It's also preventing processed data from being transferred to the main Motus database, along with a lot of R package functions.

**Comment by cjardine-bsc** [comment] 2020-01-02 18:19
I tried to change the clock, but don't have the administer permissions required to do so. Over to you D-boss @denislepage

**Comment by Hussell** [comment] 2020-01-02 18:22
Thanks Catherine. I suspected you might not be able to, but I thought it was worth asking.

**Comment by Hussell** [comment] 2020-01-02 19:43
Denis has set the clock to the correct time, so everything mentioned here should be working again.

**Comment by Hussell** [comment] 2020-01-02 20:31
Denis has found that the issue is further upstream: a group of our servers are synchronizing to a source that is slow by ~12 minutes. So after he changed the time, it slowly resynchronized back to the incorrect time. Denis has sent a message about this upstream.

We're about to deploy a change to the API code to accept a larger date-time difference until this is resolved.

**Comment by Hussell** [comment] 2020-01-02 20:56
We've deployed the temporary fix to all servers. Things appear to be running again.

**Closed** 2020-03-16 13:47 UTC
Labels: bug, sgdata

**Comment by Hussell** [comment] 2020-03-16 20:36
The temporary fix was in fact removed once the clocks were put back in sync.
