### ISSUE TITLE
Project 214 receivers re-run

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#364] opened 2018-09-21 16:19 UTC
Can these receivers be re-run? They've been doing testing in the field and will be leaving the stations shortly and want to ensure they're running properly. There were a number of detections uploaded today/yesterday where the hourly plots don't show anything. They created tag deployments on the same day they deployed the tags (but the tags have been registered for a few weeks now), so the lack of detections may be related to https://github.com/jbrzusto/motusServer/issues/419, but I would still expect to see antenna activity on the plots.

**Comment by zcrysler** [comment] 2018-09-21 16:30
An example is receiver SG-50ABRPI3D2FB, they had a tag running at the station for the whole day and could see data being written, but there are no detections through tagme() or on the hourly plot, there should at the very least be antenna activity on the hourly plot: https://sgdata.motus.org/download/214/SG-50ABRPI3D2FB-2018_Wyndham%20Finches%202018_CASA.1_hourly_tags.pdf

**Comment by Hussell** [comment] 2018-11-01 14:04
Seems to be a duplicate of #360

**Closed by Hussell** 2018-11-01 14:04 UTC
Labels: duplicate, sgdata
