### ISSUE TITLE
Jobs stalled on sgdata

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#463] opened 2019-03-27 19:32 UTC
All exportData sub-jobs seem to be waiting indefinitely since sometime this morning. Should we leave things alone while you attempt to diagnose, or go ahead an restart the processes?

**Comment by denislepage** [comment] 2019-03-28 00:37
data are coming in again now. Thanks John(?).

**Comment by jbrzusto** [comment] 2019-03-28 00:38
I didn't see this report until now, but don't see any stalled jobs and didn't do anything.  There are times when the mysql server is a bottleneck, apparently.  I don't think running it over NFS 3 is very efficient, at least with current mount options.  I'll look into whether any of those can be improved.

**Comment by denislepage** [comment] 2019-03-28 02:06
Thanks.

I suspect then that the queue may simply have been transferring the data to MariaDB for very large batches, and the tag finder queue was waiting for that to complete.

The transfer into Motus has also been running for a few hours, and still has about 5 million hits to go. There were about 24 million hits generated in the last 6 hours or so, including 5 million in a single batch, so the delay isn’t all that surprising. I guess that gives us an order of magnitude for processing and transfer speeds (about 100 million per day at that rate). For now, that is still manageable.

I have the same issue with importing into Motus, or probably even worse since we have to maintain more non-clustered indexes for speeding up data access. Those add up to significant overhead on the table writes. We only have a few indexes on the hits table, but given that the table now exceeds 1.1 billion records, things scale up. We potentially have 1 duplicate index that I may be able to remove.

Eventually, we’ll probably want to start considering not maintaining 2 full copies of the data in relational databases (e.g. clearing up MariaDB records once they have been confirmed as transferred, or push data into SQL server directly and move away from using MariaDB), but we’re not likely to try to address this soon, other than making incremental improvements. We’re likely going to upgrade our database server in the coming weeks. That may have an impact.

**Comment by Hussell** [comment] 2019-03-28 14:53
Ok, it looks like job 372411 was the culprit. I apologize for jumping the gun. In future, I'll remember to check the number of hits being transferred and estimate how long it should take based on that instead of on the number of batches being transferred before I open an issue about slowed or stalled jobs.

**Closed** 2019-04-02 15:21 UTC
Labels: sgdata
