### ISSUE TITLE
Default values for fee_id present in the website note tracked in the db

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#872] opened 2020-12-02 20:18 UTC
I just noticed that some projects which have the default fee_code 1 (Institution of the PI) on the web page still have a NULL in the db. Saving them as something else, then back to the default works, but for whatever reason the default only seems to be a placeholder on the website for many of them.

**Comment by StuMackenzie** [comment] 2020-12-02 21:54
Many PIs will not have set this up, or set up projects before this was an option, so I don't know if that may be why.

**Comment by jsayers-bsc** [comment] 2020-12-04 16:35
Indeed, though if there is a default value presented, it should also be associated in the db with the project until it's changed. And some of them are newer too (e.g. Project 311 which is "Institution of the PI" on the website, but NULL in the db).

**Comment by cjardine-bsc** [comment] 2021-02-01 21:35
@pmorrill Can you check that the value is saving to the DB?

**Comment by pmorrill** [comment] 2021-02-04 18:51
I have no idea what this is about, or what it is for. Where is fee_code managed on the website? I can't even find an reference to it in the Java code. So - probably not the one to ask! It is completely new to me.

**Comment by cjardine-bsc** [comment] 2021-02-04 20:44
Hey Paul, It is the last question on the manage project page: https://motus.org/data/project/edit?id=137

Lookup values are coming from lk_project_fees and written to projects.fee_id

**Comment by pmorrill** [comment] 2021-02-04 21:11
OK - I checked the servlet for editing projects, and it is definitely passing a value back to 'fee_id' (Not 'fee_code'). In my dev environment, the values are being saved, and are reflected back in the 'Project edit' tool once saved. Not sure what else needs checking.

FYI: this servlet is all Jeremy's work, so any in-depth debugging is best left to him.

**Comment by cjardine-bsc** [comment] 2021-02-04 21:16
Thanks Paul, I'm not always on top of who built which pages. 

I just tested using project 7 on sandbox and the value updated from NULL to 1 in the DB. @jsayers-bsc can you test again and see if you can replicate your error? 

Actually. I just re-read your error. Maybe you didn't ever try to save the form with the default value? 

As far as I can tell this is all functioning as expected. Closing unless Josh objects.

**Comment by jsayers-bsc** [comment] 2021-02-05 14:24
As an example from two very recently created projets:

Project 369 https://motus.org/data/project/edit?id=369
Project 371 https://motus.org/data/project/edit?id=371

Both have "Institute of the Principal Investigator" pre-populated and seemingly saved. Yet fee_code for both is null in the db. Seems to be the case for many of the other nulls as well.

select id project_id, fee_id from projects
where fee_id is null
order by id desc

**Comment by cjardine-bsc** [comment] 2021-02-05 17:15
The fee_id being null for older projects is expected. That shouldn't be updated until the project is re-saved (i.e. that the value has been confirmed). 

But you're right. The drop down is missing from the create new project page. That's the issue. 

https://sandbox.motus.org/data/project/new

@Hussell Can you add it please?

**Comment by leberrigan** [comment] 2022-03-24 23:13
We still need to add fee_id field, along with a whole bunch of other project parameters (project users, groups, institutions), to the 'create new project' form. This deserves a new issue.

**Closed** 2022-03-24 23:14 UTC
Labels: Metadata management
