### ISSUE TITLE
SGdata returned tag registration erorr, though tags actually did register

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#983] opened 2021-06-16 16:04 UTC
Project 417 recently attempted to register 99 tags (Job id 7191832). All but 4 failed with the following message 

> Query to motus server to register tag 335:13.7 failed
> with this error: database-error: A database error occurred - org.bsc.exceptions.DBException com.microsoft.sqlserver.jdbc.SQLServerException: The value is not set for the parameter number 0. SQL: "dbo.[prAPIImportTagsTransfer](?, ?, ?)"

When they tried again to register, they got "tag already exists" errors for them. But when they checked their [Manage Tags](https://motus.org/data/project/tags?projectID=417#tabs) page, all the tags are there with the proper properties. So they did register.

![image](https://user-images.githubusercontent.com/55001144/122254160-d6440700-ce9a-11eb-8935-5fcb8fd0670c.png)

However they can't be searched for; the results are empty when any of the tab labels is used in the search field.

![image](https://user-images.githubusercontent.com/55001144/122254281-fb387a00-ce9a-11eb-9f80-3f8b6d115b2f.png)

**Comment by Hussell** [comment] 2021-06-16 16:27
We've been aware of this, but tracked it down to the main Motus database, something to do with transferring from a temporary to a permanent table, I think? Anyway, with Catherine on vacation, Denis has been looking into it. It's a horrible user experience, but since the tags do, in fact, get registered correctly, it hasn't been highest priority to fix. Still high priority though, given that it usually causes users to re-upload their tag recordings, which makes them justifiably unhappy for no good reason.

**Comment by denislepage** [comment] 2021-06-16 18:30
I found the cause. The last step of the registration process creates a copy of the tags in the sandbox database, which is necessary to keep the 2 database in sync for the tag ID's. This was the step that was failing and likely creating this error.

There is a constraint that prevents inserting tags that have the same projectID, mfgID and dateBin (those would normally get resolved by the dot notation). However, because the project list is out of date in sandbox, projectID gets converted to 0 for sandbox, and this violates the constraint if the same tag is already registered in project 0 in the same dateBin. Everything else should have worked, except the copy to sandbox, which won't affect the user. I'll disable the constraint in sandbox for now. I'm not even sure it should be strictly enforced in the main database, though having the same MFG ID's could be confusing for users and I can see a value in adding a dot on the tag to help. I also reinserted a couple batches of tags that likely ran into the same error in May and one back from last fall 2020.

@cjardine-bsc  one step we may want to introduce is updating the sandbox tags tag table at least once in a while, so the project ID's are matching those in the live database. I'm not sure if there would be other implications on the sandbox site than a simple update query.

Duplicate tag registration checks will continue to happen as before (with the tag-exists return code). The SQL error is normally not something people will see except when we overlooked something, so I am not sure if anything needs to be changed in what users see, but we can chat briefly on this.

**Comment by denislepage** [comment] 2021-06-16 19:31
The tags not being searchable is almost certainly unrelated. Can someone confirm whether new tag registration typically creates tag deployments? Those are currently missing in the main database for the 99 tags, but are also missing for several other projects, so I expect there is no issue caused by the SQL error here. 

I checked at a couple other projects with tags without deployments, and the search for a tagID or mfgID consistently returns no result when the tag doesn't have a deployment.

I narrowed it down to this statement, but I am not sure where it is being generated (should be TagBean, but I am missing something). The filtering for those 2 fields is done on the fields from the deployment view, rather than the tags table, which explains the missing results. The following change would allow returning the tags on the basis of the tags mfg_id or the id fields

 (b.mfg_id LIKE '%54651%' OR b.id = 54651)

@pmorrill or @Hussell  could you look at whether making this change will break anything, and find out where this change needs to happen?

```
`SELECT ROW_NUMBER() OVER ( ORDER BY b.id asc ) AS RowNum,a.*,b.id,b.mfg_id,b.date_bin,b.period as tagPeriod,
b.model as tagModel,b.deprecated_bit,ROUND(b.nom_freq,2) as nomFreqStr  FROM tags b LEFT JOIN 
vwBase_tags_deployments a ON b.id = a.tagID  WHERE project_id = 395 AND (mfgID LIKE '%54651%' OR tagID = 54651)
```
Should be changed to:
```
SELECT ROW_NUMBER() OVER ( ORDER BY b.id asc ) AS RowNum,a.*,b.id,b.mfg_id,b.date_bin,b.period as tagPeriod,
b.model as tagModel,b.deprecated_bit,ROUND(b.nom_freq,2) as nomFreqStr  FROM tags b LEFT JOIN 
vwBase_tags_deployments a ON b.id = a.tagID  WHERE project_id = 395 AND (b.mfg_id LIKE '%54651%' OR b.id = 54651)
```

**Comment by pmorrill** [comment] 2021-06-16 20:00
We do not automatically create deployments when tags are registered, no.

I will look at the filter mechanism. This is the beta9 code (live server), I can see. Has anyone tested beta10? It has a new filter mechanism. I'll check both over tomorrow morning.

**Comment by denislepage** [comment] 2021-06-16 20:12
Good point. The beta server (presumably still beta10) behaviour is indeed different. Those tags are being found even when there are no deployments, so we’re probably ok here.

It’d be good to commit to deploying beta10 in the next couple of weeks.

@jsayers-bsc @leberrigan are you able to use mainly the beta server for your day-to-day work in the next little while?

I'm going to close this, as the fix is simply to deploy beta10 to live now.

**Closed by denislepage** 2021-06-16 20:12 UTC
Labels: Bug, Database

**Comment by jsayers-bsc** [comment] 2021-06-16 22:00
Huh, so searching for a tab only returns tag with deployments (or with "pending" deployments apparently, which will result in a blank "deployment range" field which suggests no deployment). Guess that search feature isn't used all that often or it would have been noticed and brought up more often!

An important comment on beta10: we need to reconcile stations/receivers before that goes live. Stations are not yet present (and will require review by both us as well as many projects to get everything properly mapped since site names do not always line up with stations), and Receivers can no longer be managed separately.

**Comment by cjardine-bsc** [comment] 2021-06-21 18:30
Stations should be present in most cases in beta10 (look at project 77). 

I've got a script that resolves most of this, I sent a list of metadata problems to Kirby to be addressed, once those are complete I can finish the transition from sites/deployments to stations. I shouldn't need too much input from you guys or users. I've got things grouped by site/location which resolves most questions.
