### ISSUE TITLE
Species names with forward slash

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#793] opened 2020-08-31 17:13 UTC
Some species or subspecies names have a forward slash to represent a combination of multiple taxa that used to be split apart ([_Oenanthe oenanthe oenanthe/libanotica_](#781) is one).

It looks like there may be an issue with displaying these names when editing tag deployments, namely these pages:
https://motus.org/data/tags/edit?projectID=123&id=28317
https://motus.org/data/tag/deployment/edit?projectID=123&id=16718

**Comment by denislepage** [comment] 2020-08-31 17:27
More likely, the deployment is assigned to a species ID that is deprecated. If that’s the case, we should change it. Not deployments should relate to a taxon with species status = 0. @cjardine-bsc

If that’s not the issue, then we can look at why the name isn’t being displayed in full.

**Comment by cjardine-bsc** [comment] 2020-08-31 17:46
Not the issue:

use motus 
go

SELECT * 
  FROM [motus].[dbo].[tags_deployments] a inner join lk_species b on a.species_id =b.species_id 
  where b.species_status = 0 
  
  SELECT * 
  FROM [motus].[dbo].[tags_deployments] a inner join BSCWEB.dendroica.dbo.lk_species b on a.species_id =b.species_id 
  where b.species_status = 0 


The problem is that the species name displayed is stored in the tags_deployment table, not pulled from the lk_species table. The name in the lk_species table has been updated, but the name stored in the tags_deployment table has not. 

SELECT * 
  FROM [motus].[dbo].[tags_deployments] a 
  where id = 16718
  
  select * from lk_species 
  where species_id = 42068

**Comment by pmorrill** [comment] 2020-08-31 18:30
I'll take a look at that.. Why do we store species names in deployment tables at all?

**Comment by cjardine-bsc** [comment] 2020-08-31 18:34
I think because we had some projects that had species tagged that we didn't have pre-defined (insects, weird Australian mammals, etc).

**Comment by denislepage** [comment] 2020-08-31 22:53
I think it’s useful to keep the original name or code used. Whether and how it gets displayed back to the user is a different story. Once a match is made to a species ID, I’m not sure we need to display that value.

**Comment by pmorrill** [comment] 2020-09-02 19:44
I have checked in a fix, so that we will always resolve species name from species id - where  possible, when displaying the tag deployments.

**Comment by leberrigan** [comment] 2020-09-03 16:16
Looks good. I just checked and the full names are now being displayed on those two pages.

**Closed** 2020-10-15 17:32 UTC
