### ISSUE TITLE
User / project associations are being deleted

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#208] opened 2018-04-16 12:32 UTC
I can't access projects 173, 186, or 121.  The last one I tried to access gave me "Error reference number: 1523881664993".

The user can't access those projects either (user 2323) and is no longer listed as a user for any of those projects in the projects_users database, the projects still exist in the database though.

A few weeks ago a number of tags were moved around between these projects, but I don't know if that's related at all.

**Comment by Hussell** [comment] 2018-04-16 13:54
I've deployed a fix for the proximate cause (a NullPointerException) on beta and sandbox, but I don't know why those projects no longer have any users. Looking at my local copy of the database from two weeks ago, projects 23, 30, 69, 115, 176, and 180 had no users at that time. Now 121, 173, and 186 are the only ones without users - a completely different set!

**Comment by Hussell** [comment] 2018-04-16 14:12
Who moved the tags? Also, how? (I looked around for a way to move tags between projects, but if it exists it isn't obvious.)

**Comment by Hussell** [comment] 2018-04-16 14:41
It looks to me like the tag transfers can't have caused the problem.

There seems to be some sort of caching issue when I switch between projects. If I switch to 'Manage Project' first, then I can get to 'Manage Users'.

**Comment by Hussell** [comment] 2018-04-17 16:10
Ok, that looks good. Zoe, can you manage project 121 on beta now?

**Comment by Hussell** [comment] 2018-04-17 18:08
No, we don't. The backup table bt_projects_users only contains entries for user 2323 for these three projects, though.

**Comment by denislepage** [comment] 2018-04-17 19:51
One thing to check for is that calling the update method on MotusUser should run the prMoveUser proc, which deletes a number of records associated with a user in related tables, including project_users.

The expectation is that those will be reinserted from the MotusUser bean. If they are not, then every user that updates its profile will have lost their project info. Those can be recovered from backup tables if necessary.

**Comment by zcrysler** [comment] 2018-04-24 18:45
The same was happening with project 14 - Pam was removed as a user, I believe she used to be the PI - user id 230.  When trying to access the project I kept getting the error "The researcher with ID = 230 is not part of this project, and thus cannot be its primary contact." The only way I could get into the project was going to the manage project page for another project, switching to 14, changing the lead user to someone else (it wasn't even set to Pam because she wasn't listed as a user, so the error is odd), adding Pam, then changing her to the PI.

**Comment by pmorrill** [comment] 2018-05-02 14:56
As far as you can tell, is if true that the user account record (in user_id) is NOT being removed when this strange event occurs? That is, only the projects_users record is lost? Is that accurate?

**Comment by Hussell** [comment] 2018-05-02 17:02
Correct. The entry in the table user_id still exists, as does the entry in user_properties. It's only the rows in projects_users that are being lost.

**Comment by zcrysler** [comment] 2018-05-22 15:35
This seems to have happened again with user 354 - I believe she had access to project 65 and 63. When I'm logged in as myself and I try to access those projects I get:
"The researcher with ID = 354 is not part of this project, and thus cannot be its primary contact.

 No project ID found."
and can't access the project unless I go to the "manage project" page https://motus.org/data/project/edit?id=63, and click save without actually making any changes, I think because the PI used to be user 354, so saving it as whatever user it defaults to next fixes the issue.  But user 354 is still missing from the project.  They uploaded tag registrations this morning, so this must have happened very recently.

**Comment by pmorrill** [comment] 2018-05-22 15:39
Do we know WHICH tool they used to upload the tag registrations? (ie: SG or our own Motus tool).

Should we contact them and ask if they did anything else this AM? Did they recently manage their project users, for example? Did they use the web interface for any other actions?

This is being triggered by some obscure action: I'd like know precisely what they did, to help narrow it down.

**Comment by zcrysler** [comment] 2018-05-22 16:06
Is there a way to see what projects she used to be registered to?  I'll ask her about the rest

**Comment by Hussell** [comment] 2018-05-22 16:41
bt_projects_users keeps a backup of that. User 354 was registered with projects 63, 65, and 146.

**Comment by Hussell** [comment] 2018-05-22 17:12
User 354 is also the primary contact for projects 63, 65, 137, and 146.

**Comment by Hussell** [comment] 2018-05-22 17:18
I'm 90% sure this is caused by the user editing/saving their profile, due to a change to prMoveMotusUser from March 28th. A fix should be in place as soon. The backup table shows that user 354 edited her profile yesterday.

**Comment by cjardine-bsc** [comment] 2018-05-22 17:28
See my comment on #144. 

I went to go re-insert the rows into projects_users from the backup table but it looks like Zoe has already done that. Thanks Zoe!

**Comment by cjardine-bsc** [comment] 2018-05-22 19:20
That's not a problem. :-)

**Comment by Hussell** [comment] 2018-05-22 19:55
I've put together an SQL query to find entries in projects_users which probably shouldn't have been deleted. Would someone check my logic? I get only 9 users still affected.

use motus;
select a.*
from bt_projects_users a
left join projects_users b on b.user_id = a.user_id and b.project_id = a.project_id
where a.user_id in (
select a.user_id
from bt_user_id a
where a.last_edited_dt >= '2018-03-28'
and a.login_name is not null
group by a.user_id
)
and b.user_id is null
order by a.user_id, a.project_id

**Comment by cjardine-bsc** [comment] 2018-06-19 15:45
Digging into this reveals that there have been three projects deleted since the data this bug originated. 

Before I close this, Zoe, can you confirm that these projects should be no-more?

id	project_name
44	Eastern MA NWR Complex - COTE
135	Maggini - Ventotene spring
136	Bahamas PIPL

Otherwise I've returned the users to their rightful projects and this can be closed.

**Comment by zcrysler** [comment] 2018-06-19 16:00
Yes these should all be deleted

**Comment by cjardine-bsc** [comment] 2018-06-19 16:03
Sweet. Closing time!

**Closed by cjardine-bsc** 2018-06-19 16:03 UTC
Labels: bug
