### ISSUE TITLE
Add antenna-type option: "omni"

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#401] opened 2018-11-23 16:18 UTC
Please and thank you.

**Comment by cjardine-bsc** [comment] 2018-11-23 18:59
Need those re-named?

**Comment by leberrigan** [comment] 2018-11-26 19:08
Mast radiator implies the entire tower structure is used as a radiating element. Omni antennas can be rigid or flexible and come in a variety of forms, including J-pole, whip, and monopole. I believe the missing variety of antenna is monopole. See below for more details:
https://en.wikipedia.org/wiki/Monopole_antenna
https://en.wikipedia.org/wiki/Omnidirectional_antenna

**Comment by Hussell** [comment] 2018-11-27 14:34
I must be missing some context here; did someone say they couldn't find the type of antenna they were using in the list?

We have three omni-directional antennas in the list: "J-pole", "mast radiator", and "whip antenna". We could add "monopole antenna: other", we could add "omni-directional antenna: other", we could prefix the existing three so they read "omni-directional antenna: J-pole", etc., we could do some or all of those, or something else. As mentioned above, I don't know what the issue is, so naturally I don't know what the solution should be.

**Comment by StuMackenzie** [comment] 2018-11-27 14:52
Yes, sorry. A number of hsers have incorrectly labeled their antenna because their choice didn't exist, or they didn't understand what the different types mean. A number of J-poles are actually monopoles, etc., There are likely a few others we haven't found yet. I think that adding "monopole" will be the easiest solution for now without confusing anything with the use of the term 'omni'. I think most j-pole or mast radiator (if any) in the DB are likely monopoles. I wouldn't change anything at this point though.

Alternatively, we could add the prefix- 'omni' in front of monopole, j-pole, and mast radiator, but that's not really correct either.

**Comment by cjardine-bsc** [comment] 2018-12-05 15:29
Okay. So I've added Monopole. 

Here is your current list of available antenna's, the 0 and 1s indicate whether they are directional or not. Please let me know if we need to make any further alterations to this list. If not we can close this issue. 

antenna_descr	directional
custom	1
6 element (custom)	1
9 element (custom)	1
J-pole	0
monopole	0
none	1
mast radiator	0
whip antenna	0
3-element Yagi	1
4-element Yagi	1
5-element Yagi	1
6-element Yagi	1
8-element Yagi	1
9-element Yagi Unknown Model	1
9-element Yagi Laird PLC-1669	1
9-element Yagi Maple Leaf 9E166	1

**Comment by StuMackenzie** [comment] 2018-12-05 17:23
Looks good. Thank you.

**Closed** 2019-02-05 15:11 UTC
Labels: done, enhancement
