### ISSUE TITLE
missing receiver metadata

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#264] opened 2018-06-11 21:10 UTC
This has been brought up before: https://github.com/MotusDev/Motus-TO-DO/issues/157

There are detections coming through tagme() that don't have any associated receiver metadata such as recvDeployName, recvDeployLat etc., including serial number. There are theoretically GPS locations, but in the cases I'm looking at they're 0 so these become essentially useless tag detections. I think I've asked before and I forget what the answer is - but how are there detections without even a serial number? If this is a case of a deployment being ended too early and therefore missing detections, I could fix that in the metadata, but without even a serial number I can't figure out what project this might be stemming from.

Some examples:
Project 78, batchID 5598, hitIDs 20394718, 20394719, 20393586, etc
Project 78, batchID 126747, hitIDs 393722513 etc.

**Comment by cjardine-bsc** [comment] 2018-06-12 16:21
You don't have a serial number but do you have a device ID?

**Comment by jbrzusto** [comment] 2018-06-12 16:44
```sql
MariaDB [motus]> select batchID, motusDeviceID from batches where batchID in (5598, 126747);
+---------+---------------+
| batchID | motusDeviceID |
+---------+---------------+
|    5598 |           772 |
|  126747 |           772 |
+---------+---------------+

```

**Comment by cjardine-bsc** [comment] 2018-06-12 16:47
Yes, thanks John, but I know how to pull that data. I was asking Zoe if it's viable to her in the alltags view in R. 

Zoe, if you can let me know, I'll look into the issue. 

Cheers

**Comment by denislepage** [comment] 2018-06-12 16:58
The sg_taghits_deploy_id resolves the deployment assigned to each detection. Real-time resolution is way too slow, so this is the only option we have for now, without changing the whole relationships of the various pieces. E.g., somehow ensure that each batch was uniquely assigned to a deployment. That sort of approach would require some fundamental changes to the system. Anyway, that discussion is for another day.

There are a few tables that are acting the same way, primarily to speed up data queries.

Those records get created (usually) during the import from sg data, or when the metadata changes. This happens through the queue. If the data is out of sync, this suggests that some of the queue may have failed. We may need to build some failsafe against that. Either a way to test and fix the discrepancies, or recover from failed queues.

**Comment by zcrysler** [comment] 2018-06-12 17:43
No device ID, there's nothing I can use in the alltags table to figure out what receiver or project this might belong to, other than GPS locations, which in this case are all 0 so not useful.

**Comment by denislepage** [comment] 2018-06-13 00:36
There were 9 batches that weren’t in sg_taghits_deploy_id, for some reason or another. What’s interesting is that these records are appended immediately after the data itself during the upload (not a queue issue), so I am not sure how it happened, but there were all values in the same neighborhood. Those weren’t related to Lotek-D000426, in any case.

select * from sg_taghits_deploy_id where
batchID in (155419,155417,155415,155416,155386,155414,155396,155418,155395)

I am not sure there’s an easy way to check if the deployment ID’s assigned to each hit is out of synch without actually testing them all. That’s a process that would take several hours to run, I think. An alternative would be to look for queue steps that failed.

In any case, I checked for hitID 20394718, 20394719 and 20393586 for instance. There are currently no deployment ID’s assigned to those hits.

The receiver Lotek-D000426 has no deployments at all, so this is expected. Therefore, as far as I can tell so far, the issue is not related to any problem with the sg_taghits_deploy_id table.

We need to look elsewhere, and the issues is almost certainly related to the discrepancies between the sensors_hash_keys and the sensors table, something I thought we had addressed. Fixing this may possibly require changing the source of the deviceID field in alltags, but I am loading the project data now, and I’ll look into this.

**Comment by denislepage** [comment] 2018-06-13 02:04
As I expected, the issue here is related to the metadata. The easiest fix would be to use the deviceID field from batches rather than recvs. 

I have updated the hook functions. You can try to reload the motus package (staging branch), and see if you can at least see the deviceID values now for those:

install_github("motusWTS/motus@staging")

If that works, I'll push the new version to the master branch.

**Comment by zcrysler** [comment] 2018-06-14 20:58
Downloading through motus@staging now fills in the deviceID in the alltags view

**Comment by denislepage** [comment] 2018-06-14 23:46
I have made the changes to the live branch as well, if you want to try.

I see that you have made several changes in master also. I am presuming those changes should be brought over in staging also. If you do work in master directly, the staging branch needs to be “synched” before any new work is done in staging.

I can do that now, unless there was a reason why staging is now behind master.

**Comment by zcrysler** [comment] 2018-06-14 23:52
Yes, sorry they look like there were all just name changes to keep up with the alltags table variable names. Master can be synched with staging

**Closed** 2019-02-04 16:20 UTC
Labels: bug, sgdata
