### ISSUE TITLE
Connected Receivers (originally, Connected School Receivers)

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#583] opened 2019-10-22 20:18 UTC
From Liza:

>  Just thought about the existing school towers. Some of them don’t seem to have any new detections. How do I know if they are connected, or need to be downloaded? This might affect the static reports on the school dashboards…

Station | Last detection
-- | --
Moosonee | August 20, 2018 (although profile says May 22, 2019 – but no data, which   is a little strange?)
Kentville | 22-Oct-19
Brantford | 27-Sep-18
Sackville | 24-Jun-19
Chilliwack | 8-Oct-19

**Comment by Hussell** [comment] 2019-10-23 15:12
I think I've tracked down the receivers and deployments for these:
SG-FFDERPI34246, unnamed deployment, ID# 5497 (Chilliwack)
SG-4001BBBK2330, Tantramar School (Sackville)
SG-5113BBBK3162, Russel Reid PS (Brantford)
SG-F783RPI36B63, HortonHigh (near-ish to Kentville; this one may be wrong)
SG-5113BBBK2829, Moosonee (Moosonee, obviously)

Sackville, Brantford, and Moosonee only have manual uploads so far. Moosonee does have detections and data right up to May 22nd, 2019.

Kentville is connecting hourly.

Chilliwack was connecting hourly up to Oct. 8th, but nothing since then, so someone should check that receiver's condition.

**Comment by leberrigan** [comment] 2019-10-23 15:59
Thanks Jeremy. I'll let Liza know about Chilliwack.

**Comment by StuMackenzie** [comment] 2019-10-24 14:32
Moving this from email: There have been some issues with several of the local connected gnomes as well. I visited a few local ones last week that weren’t syncing data. A reboot and/or reimage helped, though one also had a fried power adapter. There are a couple other local ones that need to be checked, so Brantford is now on that list as well.

There have been some recent changes to the sensorgnome.org/status that have inadvertently resulted in gnomes that should be connected but aren’t being absent in the list. The change was intended to filter out gnomes that had only been connected once say a couple years ago as part of a diagnostic from showing up in that list. (Another change was to add the year to the last data sync date.) But unfortunately now some connected gnomes that just aren’t connecting aren’t showing up anymore either. Brantford apparently is one. Zorard is another local one.

**Comment by Hussell** [comment] 2019-10-24 16:06
Galeta was only ever connected twice, back in Feb. 2018. Since then we have received 2 manual uploads.

For Canopy Tower we have no record of it ever successfully connecting. We have received manual uploads on 3 occasions.

**Closed** 2021-01-31 16:53 UTC
Labels: Bug, Discussion, Presumed resolved - Old, Question
