### ISSUE TITLE
SensorStation Trouble Shooting Round 2: February 2020

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#687] opened 2020-02-27 16:46 UTC
Setup February 27:

19769 - At Josh’s house, plugged into the internet (port 7). FCD in Port 2. 1 LifeTag and 1 NanoTag as of morning on the 28th. [Test deployment 5929](https://motus.org/data/receiverDeployment?id=5929).

97369 - At BSC Motus Workshop, plugged into internet (Port 7; SG and another SS have connected through this). FCD in Port 2. Life tags and Nanotag present. [Deployment 5930](https://motus.org/data/receiverDeployment?id=5930).

71018 - At Stu’s house, plugged into the internet. FCD in Port 2, Ethernet Port 7. Life tag and Nanotag present. [Deployment 5928.
](https://motus.org/data/receiverDeployment?id=5928
)
[16513 ](https://motus.org/data/receiver/deployment/detections/timeline?year=2020&id=5880) - At Luc's house. No FCD plugged in (I think). Ethernet in Port ???. 2 Life Tags present, no NanoTags present at this time. Last data from Jan 15.? Will return on Mar 02 and double-check.

**Comment by jsayers-bsc** [comment] 2020-02-28 16:29
Removed RTL-SDR from 97369 on the 27th. LifeTag and Nanotag placed near 71018 on morning of the 28th

**Comment by StuMackenzie** [comment] 2020-02-29 12:05
71018 - inky display 'beeps' stuck at 11810 for about 48 hours now. Not connecting to CTT server.

**Comment by jsayers-bsc** [comment] 2020-03-02 19:11
19769 at my house has been operating normally for the past few days, checking in regularly with CTT. The one LifeTag in front of it is showing up in the [detections table](https://motus.org/data/receiverDeploymentDetections?id=5929). 

16513 at Lucas's is now associated with the online account. It has not checked in since Jan 15, the last date for which we have detections data. Uncertain at this time whether or not it's been recording this past 1.5 months or whether it just isn't connecting. 

71018 at Stu's checked 2 days ago, looks like after Stu posted that it hadn't checked in for 2 days. But it now has been 2 days again since last check-in. @StuMackenzie did you reboot it when it was frozen or did it spontaneously "thaw"?

97369 finally checked in a few days ago, after several days plugged in and multiple restarts. But the display is frozen from 2 days ago and it hasn't checked in since then either. Unknown yet whether it was recording data during the days when it wasn't connecting.

No Nanotags showing up in the detections data for any of the 3 stations that have them.

There may be an issue with CTT's page as detailed info for the stations does not load.

**Comment by StuMackenzie** [comment] 2020-03-02 20:03
I've just been leaving 71018 as is to see if it connects on it's own. The last connection was the result of a reboot. 

What do you mean by the display has been stuck?

The display on 71018 has been stuck at 11810 beeps for a few days now, but still refreshes and the clock is still accurate.

It would be good to make test deployments for all of these, upload the data, and take a proper look at it to assess. If it gets stuck with CTT I can prompt them to clear their cache.

let me know when you're ready to do that.

**Comment by jsayers-bsc** [comment] 2020-03-02 20:12
> The display on 71018 has been stuck at 11810 beeps for a few days now, but still refreshes and the clock is still accurate.

That's similar to what had been happening previously, where the receiver _looked_ like it was working, but in fact it wasn't recording data. In many cases it was still recording Nanotag data, but not LifeTag data. 

There are test deployments created for them. Detections of LifeTags seem to be getting passed back from CTT in a fairly timely manner. No Nanotags showing up though.

**Comment by StuMackenzie** [comment] 2020-03-02 20:30
71018 display now stuck on welcome screen for most if not all of March 1-2.

**Comment by StuMackenzie** [comment] 2020-03-02 20:55
Ability to view CTT Sensor Station Overview from online interface would be helpful.

**Comment by leberrigan** [comment] 2020-03-04 19:59
**16513**  (mine): has been frozen since the 2019-01-31 @ 07:59 UTC, shortly after I left to head to ON. I checked the device before I left and confirmed it was still working.

- No FCD plugged in.
- Ethernet cable for internet.
- Lights still blinking on board.

**Comment by mmwebb** [comment] 2020-03-12 21:30
FYI
I am able to connect my stations to WiFi using small USB WiFi dongles (Specifically, I've used both the TP-LINK TLWN725N dongle($7.99USD) and a very cheap Zibo Mini USB dongle($4.99USD)).  

To use these, I plugged them into USB5 on the SS, plugged my USB ethernet port/cable into USB6, then:
ssh into the pi using: ssh pi@your.ip.address password: raspberry
then type: sudo raspi-config 
Navigate to Network Options (Then from there its pretty self explanatory)
For SSH, I use Putty.  Windows 10 comes with OpenSSH as an option, which when installed allows you to use Command Prompt or Windows Powershell.

There isn't a very clear way to verify that a SS connects but my stations have eventually checked in when I've done this at my office.  I have also tethered it from my phone's hotspot, and it connects, but never did check in after being connected for 6 hours.  I'll keep giving this a try.

**Comment by mmwebb** [comment] 2020-03-30 18:29
**97468**up and running Mar 24 with Lotek test tag (4.2), LifeTag, and CTT Node running nearby.  Everything ran nicely with both tags and node detected until 04:24:42 on 3-28-2020, when the station reset.  Since then LifeTag and node are detected, but not Lotek test tag.  On SensorGnome Interface, funcube plugged into port 1 has been reset to being tuned to 0MHz.  I am unable to set the frequency back to 166.380MHz.  When everything was functioning correctly, the interface said that the funcube was tuned to 166.376MHz, and detections were showing up in the Live Pulses window.

![SGinterface3-30 (2)](https://user-images.githubusercontent.com/61557021/77948117-1ca34b00-7282-11ea-914e-8b0a5fd8493a.png)

**Comment by jsayers-bsc** [comment] 2020-07-13 18:38
In the end, it was found that all issues were somehow related to the onboard GSM 2G modem on these. We now have newer Version 2 SS and are experiencing none of these issues.

**Closed by jsayers-bsc** 2020-07-13 18:38 UTC
Labels: receiver
