### ISSUE TITLE
"Invalid receiver id" error 

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#823] opened 2020-10-07 15:21 UTC
After registering a new receiver, this error often (always?) appears:

![image](https://user-images.githubusercontent.com/55001144/95350692-723e5d00-088e-11eb-9930-915b6788310f.png)

The error isn't actually relevant since the receiver was successfully registered. But it seems that there is a call made to pull up information for that receiver ID _before_ the receiver is actually registered into the DB.

**Comment by Hussell** [comment] 2020-10-07 17:19
Duplicate of #824

**Closed by Hussell** 2020-10-07 17:19 UTC

**Comment by denislepage** [comment] 2020-10-07 22:19
The number looks odd.

Is the 927509 number meant to be the sensorID, the receiverID or the serial number? That numbers doesn’t seem to match any of them.
