### ISSUE TITLE
unregistered deployed tags project 47

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#287] opened 2018-07-06 18:24 UTC
There are 150 tags that were not registered but have now been deployed. The user said she registered but I can't find a record of it. I've got the registration package and I tried uploading but of 150 tags, only 4 registered with the correct BI, 5 other tags registered but with the wrong BI, it was jobID 191507

The tags were recorded with a funcube, and they look fine to me. What's the process to try to manually register these tags?

**Comment by StuMackenzie** [comment] 2018-07-06 18:30
Does she still have the audio files?

Why don’t people check before deploying!

S

____________________

**Comment by zcrysler** [comment] 2018-07-06 18:46
Yes, she sent me the audio files which is what I tried to upload, but most of them failed so they'll need to be manually registered.

**Comment by cjardine-bsc** [comment] 2019-01-31 17:43
I need the list of mfg_ids that need to be registered and their corresponding BIs, model, and nomFreq. 

Purdy please.

**Comment by cjardine-bsc** [comment] 2019-01-31 18:38
There are 148 in this file but you're original message said 4 were correctly registered. Just want to make sure I don't duplicate any registrations. 

Also can we follow up with the user to double check the BI (ideally from the lotek shipping form)

**Comment by leberrigan** [comment] 2019-01-31 19:17
I originally included two tags that were registered with a BI of 14.9 s, but I no longer think these are correct since the original recordings only had two bursts (instead of three) and the user who registered them said they're supposed to have a BI of 15.1 s.

**Comment by cjardine-bsc** [comment] 2019-01-31 19:56
So...which 9 tags? Are they also in the csv?

We should look at their BIs and make sure they aren't double-registered.

**Comment by leberrigan** [comment] 2019-01-31 22:15
I just measured the BI of 10 or so tags and got some strange results. Every tag I looked at seems to have a BI that alternates between ~15.090-15.99 s and ~14.87-14.92 s, one after the other. Take a look for yourself if you like: 

[Download Tag Recordings](https://drive.google.com/uc?id=1JGBJHvXY3srVVxw0kKn9o_TCfjvhVRSD&export=download)

Maybe this explains why they failed to register

**In response to Jeremy's note:**
Of the 9 tags that were re-registered, only the same 2 tags as before were registered with a BI close to ~15.1 s ([32772](https://motus.org/data/tags/edit?projectID=47&id=32772) and [32774](https://motus.org/data/tags/edit?projectID=47&id=32774)). Two of the other 7 have a BI of 14.900-14.917 s and the other 5 have a BI of ~30 s which can be explained by my results above (14.9 s + 15.1 s). Also note there are now duplicates for all 9 of these tags on Project 47.

**Comment by jbrzusto** [comment] 2019-02-01 12:06
The table below shows two things:
- tags were consistently showing up at a 9.5 kHz frequency offset, rather than
the typical 4 kHz.  **If** this is because the user set their funcube to ~ 8 kHz off nominal
e.g. 166.372 or 166.388 MHz when recording, than that's fine.  But if these were
recorded at the usual 166.376 MHz, then they are generating signal far enough off
the nominal that they won't be detected nearly as often, especially as ambient temperature
varies.  **This should be confirmed with whomever made the recordings.**
- the burst intervals, where they can be measured, are all consistent with 15.1 s, given
that the typical error in these recordings comes from the computer dropping USB packets
from the funcubedongle, resulting in slightly shorter apparent time intervals.  This rarely
affects the detection of individual pulses, or the gaps between them within a burst  (but seems to have done so for some of these recordings).  However during the long 15 second span between bursts, there's plenty of time to accumulate a 50 ms gap from this effect.

So provided the high frequency offset is due to the way tags were recorded, these can be registered with a 15.1 s burst interval.  **But if the frequency offset is what it appears to be, these tags should not be deployed.**

---

Quick analysis of these tag recordings:
```R
library(motusServer)
## where the tag recordings live
setwd("/sgm/done/00191507/00191515")
## generate markdown output
cat("File|Mean(freq)|BI\n---|---|---\n")
## get mean frequency offset and list of BIs for each tag recording
for (f in dir(pattern="*.wav")) {
   a = wavFindTags(f, ltGetCodeset(pathOnly=TRUE))
   cat(sprintf("%s|%.1f|%s\n",
      f,   
      mean(a$freq),
      paste(sprintf("%.3f", diff(a$ts)), collapse=",")))
}
```

gives this:

File|Mean(freq)|BI
---|---|---
Tag 112.wav|9.8|14.877,15.099
Tag005.wav|9.8|15.098,14.872
Tag006.wav|9.6|15.098,14.910
Tag007.wav|9.5|29.991
Tag008.wav|9.6|14.893,15.099,14.915
Tag009.wav|9.8|15.099,14.905,15.099
Tag010.wav|10.2|14.888,15.099,14.828
Tag011.wav|9.5|15.098,14.882,15.098
Tag013.wav|9.9|14.891,15.099
Tag014.wav|10.9|15.099,14.903
Tag015.wav|9.8|14.994,15.098
Tag016.wav|9.8|15.099,14.934
Tag017.wav|9.6|14.910,15.098
Tag018.wav|9.6|14.888,15.098
Tag019.wav|9.5|14.926,15.098
Tag020.wav|9.9|14.863,15.098
Tag021.wav|9.6|14.901
Tag022.wav|9.6|15.098,14.858
Tag023.wav|9.8|15.025,15.099
Tag024.wav|9.6|14.891,15.098
Tag025.wav|9.5|14.875,15.099
Tag026.wav|9.5|29.968
Tag027.wav|9.6|15.098,14.910
Tag028.wav|9.5|14.903,15.098
Tag029.wav|9.9|14.864,15.098,14.880
Tag030.wav|9.5|15.099,14.809,15.099
Tag031.wav|9.5|14.986,15.098
Tag032.wav|9.4|15.098,14.860,15.098
Tag033.wav|9.9|15.100,14.899
Tag034.wav|9.9|15.099,14.893
Tag035.wav|9.5|14.892,15.098
Tag036.wav|9.8|15.099,14.971
Tag037.wav|9.8|15.099,14.873
Tag038.wav|9.6|15.098,14.912
Tag039.wav|9.6|15.098,14.926
Tag040.wav|9.6|15.098,14.873
Tag041.wav|9.6|15.099,14.871
Tag042.wav|9.5|14.917
Tag043.wav|9.5|14.969,15.099
Tag044.wav|9.5|14.863,15.099
Tag045.wav|9.5|14.862,15.098
Tag046.wav|10.4|14.853,15.098
Tag047.wav|9.5|14.901,15.099
Tag048.wav|9.5|15.099,14.880
Tag049.wav|9.8|14.996,15.098
Tag050.wav|9.5|14.902,15.099
Tag051.wav|9.8|15.098,14.922
Tag052.wav|9.6|15.099,14.879
Tag053.wav|9.8|15.011,15.316
Tag054.wav|9.6|15.099,14.845
Tag055.wav|9.4|15.099,14.931
Tag056.wav|9.5|14.878,15.099
Tag057.wav|9.6|15.098,14.904
Tag058.wav|9.2|14.922,15.098
Tag059.wav|9.9|14.847,15.099
Tag060.wav|9.1|14.848,15.098
Tag061.wav|9.6|14.893,15.099
Tag062.wav|9.4|14.867,15.099
Tag063.wav|9.4|15.099,14.848
Tag064.wav|9.5|15.098,14.890
Tag065.wav|9.6|14.894,15.098
Tag066.wav|9.5|15.099,14.859
Tag067.wav|9.5|15.098,14.902
Tag068.wav|9.6|14.924,15.098
Tag070.wav|9.5|14.864,15.098
Tag071.wav|9.5|14.854,15.098,14.930
Tag072.wav|9.2|14.859,15.099
Tag073.wav|9.7|15.098,14.976
Tag074.wav|9.5|15.099,14.787
Tag075.wav|9.5|14.903,15.099
Tag076.wav|9.5|15.098,14.856
Tag077.wav|9.5|15.099,14.869
Tag078.wav|9.5|15.098,14.870
Tag079.wav|9.8|14.889,15.099
Tag080.wav|9.5|14.908,15.098
Tag081.wav|9.6|15.099,14.859
Tag082.wav|9.6|15.099,14.913
Tag083.wav|9.5|14.901,15.099
Tag084.wav|9.8|14.884,15.098
Tag085.wav|9.8|15.099,14.903
Tag086.wav|9.9|
Tag087.wav|9.0|15.100,14.877
Tag088.wav|9.5|14.897,15.099
Tag089.wav|9.6|15.098,14.864
Tag090.wav|9.5|15.099,14.867
Tag091.wav|9.6|15.099,14.755
Tag092.wav|9.6|14.888,15.100
Tag093.wav|9.5|15.098
Tag094.wav|9.5|15.099,14.909
Tag095.wav|9.5|29.991
Tag096.wav|9.7|14.910,15.098
Tag097.wav|9.9|15.099,14.883,15.098
Tag098.wav|10.6|15.098,14.942
Tag099.wav|10.4|15.099,14.892
Tag100.wav|9.5|14.885,15.099
Tag101.wav|9.5|14.890,15.098,14.912
Tag102.wav|9.7|15.099,14.914
Tag103.wav|9.5|15.098,14.911
Tag104.wav|9.5|15.098,14.918
Tag105.wav|9.9|14.880,15.098
Tag106.wav|9.9|14.810,15.100
Tag107.wav|9.5|15.098,14.934
Tag108.wav|9.5|15.099,14.867
Tag109.wav|9.6|15.098,14.884,15.098
Tag110.wav|9.5|14.858,15.099
Tag111.wav|9.9|15.099
Tag113.wav|9.6|14.857,15.099,14.871
Tag114.wav|9.5|30.019
Tag115.wav|9.7|15.098,14.920,15.098,14.520
Tag116.wav|9.6|15.098,14.401,15.099
Tag117.wav|9.6|15.099,14.897
Tag118.wav|9.7|15.099,14.897
Tag119.wav|9.7|14.950,15.099
Tag12.wav|9.9|14.902,15.099
Tag120.wav|9.9|14.925,15.099,14.983
Tag121.wav|9.6|15.099,14.910
Tag122.wav|9.6|14.898,15.098
Tag123.wav|9.6|14.895,15.099
Tag124.wav|9.5|14.940,15.098,14.922
Tag125.wav|9.6|15.098,14.904,15.098
Tag126.wav|9.6|15.099,14.859
Tag127.wav|9.6|15.098,14.818,15.098
Tag128.wav|9.5|14.854,15.099
Tag129.wav|9.5|14.875,15.099
Tag130.wav|9.5|14.901,15.099
Tag131.wav|9.8|15.098,14.915,15.099
Tag132.wav|9.6|15.098,14.846
Tag133.wav|9.6|14.921,15.099
Tag134.wav|9.6|29.989
Tag135.wav|9.6|14.915,15.098
Tag136.wav|9.5|15.099,14.891
Tag137.wav|9.9|15.098,14.894
Tag138.wav|9.8|15.099,14.905
Tag139.wav|9.6|14.902,15.098
Tag140.wav|9.6|14.928,15.099,14.926
Tag141.wav|9.6|15.099,14.859
Tag142.wav|9.6|14.873,15.099
Tag143.wav|9.8|14.875,15.099
Tag144.wav|9.6|15.098,14.860
Tag145.wav|9.8|15.098,14.890
Tag146.wav|9.5|15.099,14.884
Tag147.wav|9.8|14.774,15.098
Tag148.wav|9.7|14.865,15.099,14.879
Tag149.wav|9.7|15.098,14.880
Tag150.wav|9.5|14.922,15.099,14.875
Tag151.wav|9.7|15.099,14.857,15.099
Tag152.wav|9.6|14.911,15.099
Tag153.wav|9.5|14.902,15.098,14.868
Tag154.wav|9.8|15.098,14.856

**Comment by cjardine-bsc** [comment] 2019-02-02 00:47
Thanks Jon, that's helpful. 

Sadly the tags have already been deployed so the best we can do is register them and hope for the best.

I've merged the duplicates of the 9 tags that had already been registered twice and set their nomFreq to 15.1

I've manually registered the remaining tags (changed model to NTQB2-4-2S) 

150 tags now registered to the project, fingers crossed we get detections!

**Comment by Hussell** [comment] 2019-07-03 17:04
After rerunning a lot of receivers, there are now detections for 146 of these tags. Rerunning continues, but I think almost all the receivers active during the lifetime of these tags have been rerun at least once since Feb 1st.

**Closed by Hussell** 2019-07-03 17:04 UTC
Labels: sgdata
