### ISSUE TITLE
166.38 tags on 150.1 receivers

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#236] opened 2018-05-09 15:53 UTC
Receivers in Europe running off of 150.1 MHz were showing detections of 166.380 tags a while back, John dealt with this problem and reran the receivers (https://github.com/jbrzusto/TO_DO/issues/162), but it seems like it's starting to happen again.

Project 123 has some receivers that are getting tags on BOTH frequencies, they're only ever scanning at 150.1:
SG-3615BBBK0DB6: https://sgdata.motus.org/download/123/SG-3615BBBK0DB6-2017_BrustHELGO_18_Sehestedt_hourly_tags.png
SG-2715BBBK0587: https://sgdata.motus.org/download/123/SG-2715BBBK0587-2017_BrustHELGO_10_KWK_hourly_tags.png
SG-1116BBBK0C40: https://sgdata.motus.org/download/123/SG-1116BBBK0C40-2017_BrustHELGO_09_Friedrichskoog_hourly_tags.png
etc.
etc.

**Comment by zcrysler** [comment] 2018-05-16 16:02
related to: https://github.com/jbrzusto/motusServer/issues/397

**Comment by zcrysler** [comment] 2018-06-18 18:42
As an update, running tagme still returns hits for tags at 166.380 being detected on receivers scanning at 150.1. Eg. motusTagID 27413 on SG-4815BBBK0175

**Comment by jbrzusto** [comment] 2018-06-18 18:56
How old are the relevant batches?  I don't know what mechanism is being used to supersede old
batches, as it didn't get implemented on my side.

**Comment by zcrysler** [comment] 2018-06-18 19:02
Tags from project 174 showing up on receivers scanning at 150.1 include batches 159905, and 162174

I'm not sure when they were uploaded

**Comment by denislepage** [comment] 2018-06-18 19:10
3 and 15 May 2018, respectively, so relatively recent.

**Comment by Hussell** [comment] 2018-06-18 19:22
The batches mentioned don't seem to be or have duplicates. They overlap by a couple of minutes with the preceding and following batches, but otherwise cover several weeks each without overlapping with any other batch from the same receiver.

**Comment by jbrzusto** [comment] 2018-06-18 19:45
Get job IDs for boot session 47 from this receiver's DB:

```sql
sqlite3 /sgm/recv/SG-4815BBBK0175.motus
select group_concat(motusJobID) from batches as t1 join motusTX as t2 on t1.batchID=t2.batchID where t1.monoBN=47;
group_concat(motusJobID)
160055,170174,172983,178523,181449,183013,185032,185939
```
Get logs from serverDB for these jobs:
```sql
sqlite3 /sgm_local/server.sqlite
sqlite> select id, data from jobs where id in (160055,170174,172983,178523,181449,183013,185032,185939);
id|data
160055|{"serno":"SG-4815BBBK0175","monoBN":47,"canResume":false,"log_":"Running tag finder on receiver SG-4815BBBK0175 boot session 47\nGot parameter overrides: --default_freq 150.096\nGot 0 (unfiltered) detections.\n"}
170174|{"serno":"SG-4815BBBK0175","monoBN":47,"canResume":true,"log_":"Running tag finder on receiver SG-4815BBBK0175 boot session 47 (resumed)\nGot 4 (unfiltered) detections.\n"}
172983|{"serno":"SG-4815BBBK0175","monoBN":47,"canResume":true,"log_":"Running tag finder on receiver SG-4815BBBK0175 boot session 47 (resumed)\nGot 16 (unfiltered) detections.\n"}
178523|{"serno":"SG-4815BBBK0175","monoBN":47,"canResume":true,"log_":"Running tag finder on receiver SG-4815BBBK0175 boot session 47 (resumed)\nGot 1252 (unfiltered) detections.\n"}
181449|{"serno":"SG-4815BBBK0175","monoBN":47,"canResume":true,"log_":"Running tag finder on receiver SG-4815BBBK0175 boot session 47 (resumed)\nGot 517 (unfiltered) detections.\n"}
183013|{"serno":"SG-4815BBBK0175","monoBN":47,"canResume":true,"log_":"Running tag finder on receiver SG-4815BBBK0175 boot session 47 (resumed)\nGot parameter overrides: --default_freq 150.096 --default_freq 150.096 --default_freq 150.096\nGot 2 (unfiltered) detections.\n"}
185032|{"serno":"SG-4815BBBK0175","monoBN":47,"canResume":true,"log_":"Running tag finder on receiver SG-4815BBBK0175 boot session 47 (resumed)\nGot parameter overrides: --default_freq 150.096 --default_freq 150.096 --default_freq 150.096\nGot 0 (unfiltered) detections.\n"}
185939|{"serno":"SG-4815BBBK0175","monoBN":47,"canResume":true,"log_":"Running tag finder on receiver SG-4815BBBK0175 boot session 47 (resumed)\nGot parameter overrides: --default_freq 150.096 --default_freq 150.096 --default_freq 150.096\nGot 0 (unfiltered) detections.\n"}
sqlite> 
```

So this receiver was being run without the appropriate parameter override until job 183013.  Why?

1. Was a parameter override in place for this project (123)?
```bash
cd /sgm/metadata_history
git blame parameter_overrides.csv | grep ,123,
a342978c (motus_data_server 2018-03-15 08:30:39 +0000 13) 13,123,"SG-1116BBBK0CEB",NA,NA,65,NA,"find_tags_motus","default_freq",150.096,"project frequency for all 2017 tags"
a342978c (motus_data_server 2018-03-15 08:30:39 +0000 14) 14,123,"SG-1315BBBK0102",0,3999999999,0,999999,"find_tags_motus","default_freq",150.096,"project frequency for all 2017 tags; receiver not yet registered"
a342978c (motus_data_server 2018-03-15 08:30:39 +0000 15) 12,123,NA,1483228800,NA,NA,NA,"find_tags_motus","default_freq",150.096,"project frequency for all 2017 tags"
```
So the project-wide parameter override was established on March 15.

2. Was this receiver registered to the project?
```bash
cd /sgm/metadata_history
4643$ git blame receiver_deployments.csv | grep ,862,
410f54f5 (sgdata automatically 2017-11-24 20:06:23 +0000 2173) 123,862,1491782400,NA
```
The receiver was registered to the project last year.

The conclusion is that this receiver had some data processed while a bug was
preventing the tag finder from obtaining the correct parameter override.
I'm going to re-run it fully now:

```bash
/sgm/rerunReceiver.R -c SG-4815BBBK0175
```

**Comment by zcrysler** [comment] 2018-06-18 20:10
I think this applies to more than this receiver though, see original comment. For example looking at https://sgdata.motus.org/download/123/SG-3615BBBK0DB6-2017_BrustHELGO_18_Sehestedt_hourly_tags.png, there are detections of a 166.380 tag from May 2018

let me know if I need to go through all receivers running at 150.1 to check or if there's an easier way to do this, there's quite a few projects in Europe running a different frequency now

**Comment by denislepage** [comment] 2018-06-18 20:34
Ideally, these parameter override values (at least for frequency) would be stored with the metadata for receivers and deployments on the Motus side.

We are looking into adding the antenna frequency as part of the deployment information, to allow hybrid deployments of antennae with different frequencies. I’m not sure how the parameter overrides handle this at the moment? We might store this both at the project level (default value) and the antenna level. Not sure about the deployment levels. That might be a bit overkill to have in 3 places.

We try to should figure out how that information is synchronized with the sgdata server. We can easily add that information to the Motus API for metadata, and that would seem like the most elegant solution. If we have to push it instead, then the receiver may not yet have been registered on sgdata.

**Comment by denislepage** [comment] 2018-06-18 21:31
We’ve only recently started deprecating (functionally hiding) duplicate batches stemming from re-runs. We’re doing this on the basis on batches with the same parameters: motusReceiverID, monoBN and tsBegin.  I think we’re ignoring tsEnd for now.

We found several cases there the tsBegin and/or tsEnd don’t match, and we’re not sure what that means. There’s a pretty wide range of differences. In the majority of cases, the tsBegin is matching, but about 30% of them don’t, with differences ranging from a few minutes to a few years (aside from those with tsBegin = 0 or another very small value presumably caused by the gps).

Can we simply use the batchID and the monoBN? If not, how should we deal with batches re-run that come out with different ts ranges?

**Comment by jbrzusto** [comment] 2018-06-19 16:14
Batches nest within boot sessions.  When re-running historical data (due to bug fixes, formerly missing
metadata, etc.), the tag finder generates one batch per boot session.  When *new* data arrive:
- any files from a previously unseen boot session for the receiver are run as a batch (so, just as if they
were historical data)
- **but** any *new* files from a previously seen batch are run *by themselves* through the tag finder and generate a new batch which is part of the same boot session.  In this case, the tag finder is run with '--resume', so that any pre-existing runs or tag candidates are preserved.  This is an optimization to avoid having to completely re-run a boot session just because we got a few new files for it (e.g. in hourly updates from seldom-rebooted online, AC-powered SGs)

**Comment by cjardine-bsc** [comment] 2018-06-19 16:55
Hi Jon, 

So If I understand correctly: 

1. New boot sessions are run as new batches. This agrees with the concept that any batches with the same deviceID and monoBN are duplicates. 

2. New files (within a boot session) are run by themselves  and generate a new batch with a deviceID and monoBN that are the same as a previous batch, but contain different non-duplicate data. 

Can you describe the behavior of the "--resume" process? Do the batches created with "--resume" contain the data from previous batches for that monoBN? Or just new data that was not in the previous batches? I'm attempting to determine why there are batches with the same deviceID and monoBN that have overlapping tsBegin and tsEnd. 

Perhaps the most pertinent question would be; how do you suggest we most accurately identify duplicate batches in the sg_batches table?

Thanks Jon!

**Comment by Hussell** [comment] 2018-06-19 17:30
I'm a little worried because we have lots of overlapping batches with the same device ID and _different_ monoBN, e.g. batches 155502 and 155515.

**Comment by jbrzusto** [comment] 2018-06-20 16:08
Definitely a problem.  Filed new issue: jbrzusto/motusServer#407

**Comment by zcrysler** [comment] 2018-06-21 15:18
Project 62 has data for receivers that are scanning at different frequencies, can they go ahead and upload or would it be best to wait for this to be sorted out? Their project doesn't currently have any receivers operating at different frequencies. They had tags set to 166.380, 166.360, and 166.320

**Comment by jbrzusto** [comment] 2018-06-21 15:20
They might as well upload and see what happens.

**Comment by Hussell** [comment] 2018-06-27 18:02
I've rerun all the receivers from project 123 which had detections of tags with impossible frequencies.

**Comment by zcrysler** [comment] 2018-07-10 17:21
Project 76 is also on frequency 150.1, there are still detections coming through from 166.380 frequency. For example a silver-haired bat tagged in 2015: 
https://sgdata.motus.org/download/76/SG-4414BBBK0693-2015_Helgoland_FG1fall_hourly_tags.png (tag PADEP#21:7.2@166.38(M.16053)
https://motus.org/data/track?tagDeploymentId=251

I just downloaded the receiver data with tagme(), there are a lot of 166.380 tag detections. Is there a way to search all receivers on a different frequency, re-run them, and get these detections removed?

**Comment by cjardine-bsc** [comment] 2018-07-16 22:18
right, so there are duplicate batches for motusDeviceID 241, but not all of them have been marked as duplicates as they have different tsStart and tsEnd times. Related to #407 where we are in need of a means to identify duplicate batches. For the time being I've manually marked the duplicates for that receiver. There seems to still be a problem however, because the re-run batches all have zero hits. 

For device 984 I've done the same, although the re-run batches on this device do have hits (huzzah!). 

We do need to establish an appropriate an accurate means of identifying duplicate batches globally to fix this across all receivers.

**Comment by zcrysler** [comment] 2018-07-17 05:41
Ok this time I think I have a real example of this problem still showing up: project 123 just uploaded data for receiver SG-4815BBBK0175 today, it's scanning at 150.1 but the last detection on July 4th is of a 166.380 tag (BahiaLomas 27419 to be exact), it's not the only one.

**Comment by Hussell** [comment] 2018-07-17 14:07
Looks like I missed that one when I was rerunning receivers. It's last on the list of receivers for project 123 sorted by serial number. Rerunning now.

**Comment by Hussell** [comment] 2018-07-17 15:31
Ok, this is weird. Rerunning it didn't change anything, and when I went back to look at how John checked the parameter overrides I found that this is the receiver that John used in his example!

**Comment by zcrysler** [comment] 2018-07-18 01:38
The hourly plot doesn't have those 166.380 tags anymore which it did before you did the re-run if that means anything

**Closed** 2018-09-04 18:12 UTC
Labels: bug, done, sgdata
