### ISSUE TITLE
R Package / Book Updates (and adding allruns/allGPS views)

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#900] opened 2021-01-13 16:25 UTC
Discussion in Motus list - see [https://groups.google.com/g/motus-wts/c/-docXi3EUEA]

Are there any changes or improvements we can make in the R package to help resolve this issue?

Issue Cleanup Note: Closed #706 in order to post this issue.

**Comment by denislepage** [comment] 2021-01-13 16:44
Not realllyl that I can see, blut they need to subset the data, both by column and row before converting to data frame.

Also make sure that they use the gps free version.

It it probably a case where they need to merge data from the table and customize it for their needs. It's hard to anticipate what people need, but there may be a simplified version of the view that may cover basic needs that is worth looking into.





-------- Original message --------

**Comment by StuMackenzie** [comment] 2021-01-14 13:37
Excellent discussion, solution, and sample scripts within google group - see https://groups.google.com/g/motus-wts/c/-docXi3EUEA

We could consider adding more documentation to the RBook as outlined by Denis in the group.

**Comment by denislepage** [comment] 2021-01-15 03:13
I have asked @steffilazerte to create the allruns view. We should try to have a look at the R book for easy changes to explain the purpose of this.

**Comment by denislepage** [comment] 2021-01-15 03:19
@steffilazerte there also seems to be several unpublished changes in the R book only in the beta branch. We need a bit of a system to track this better, I think. I'm going to work from beta for my changes (which is where all/most changes should be initially made). Hoping things haven't diverged.

**Comment by StuMackenzie** [comment] 2021-01-15 14:18
This is a little longer-term objective, but after we've implemented this change, @eg46 will start to go through the book with a fresh perspective and then we can decide whether edits, additions and rewrites are needed,or if a clean slate is better. We've started to document potential changes and discussion here -https://motuswts.slack.com/archives/C01JHRTRY22/p1610631524001400

**Comment by denislepage** [comment] 2021-01-16 00:03
I started making a few edits in Chapter 3 on the beta branch, but saved it to a different file for now. I’m not sure that the approach I started is the best one. Many of the examples could be done using alltags or allruns with only minor changes, but we’d have to keep digging down the rest of the chapter and the following ones to see if that makes sense, or if presenting both options in parallel will be too confusing. Perhaps a better/cleaner way would be to mention allruns in chapter three similar to what I did, but then have a chapter focused on examples directly based on that view.

I’ll push the draft changes I made so far on the beta branch of motusRBook.

**Comment by StuMackenzie** [comment] 2021-01-16 13:32
Re. Next steps., @ajmacdonald3 - do you mind looking through Denis's changes and see what you think, and how it may translate elsewhere in the book? Given that a larger review/ reorganization may be in the works, I think we should try and focus on a simple path forward for now to integrate the view and examples.

**Comment by ajmacdonald3** [comment] 2021-01-21 01:09
I looked through the R book and here is a brief summary of how the addition of an allruns view would have downstream effects in the book:

**Minor revisions**

- Sections 3.5.6, 3.5.8, 3.6, 3.12, 3.13, 4.3.4
- These sections all use `tbl.alltags` or `df.alltags`, but converting them to use `allruns` would be straightforward since they don't use any variables that are uniquely linked to hitID
- We could add `allruns` in parallel or replace `alltags`

**Major overhaul**

- Chapters 5 and 6
- These chapters rely heavily on variables at the hitID level like timestamp and signal strength
- A lot of the early filtering steps are done at the run level (like anything relying on the motusFilter), so those could be modified to work with allruns
- Many of the functions that are part of the motus package would need to be modified because they rely on ts and sometimes sig (i.e. `fun.getPath`, `siteTrans`, `sunRiseSet`, `getGPS`). This is also the case for Appendix C.
- Section 5.7 on figuring out ambiguous tags isn't possible without signal strength which is at the hit level, and I don't think it can be meaningfully summarized at the run level
- Similarly the signal strength plots wouldn't be possible with allruns and they're very useful for identifying false positives
- If we're overhauling, it might be worth updating the mapping in the book to use the sf package - it's good for working with spatial data and fits into tidyverse syntax

**Path forward**

I think there are parts of the motus data cleaning and analyzing process that require information at the hit level (namely ts and sig), so I think the best option for folks with large datasets would be to use the allruns view as an intermediate step towards the alltags view. Folks with large datasets could do a lot of the preliminary filtering that relies on run length using the allruns view (as a simple example, removing any runs with motusFilter = 0). Then they could pull all the runIDs they want to keep based on the run level filtering, and do a filter on tbl.alltags to keep only those runIDs before converting it to a flat file. I think this would cut the size of df.alltags down significantly. Then they could move forward with making signal strength plots and maps to identify false positives that made it past the initial filter.

For folks who don't have large datasets, it's probably simpler to just stick with alltags rather than using multiple views if they don't have to. So maybe a separate chapter on working with large datasets/using the allruns view would work best.

**Comment by leberrigan** [comment] 2021-01-21 18:25
What about doing things in parallel?
```
alltags.tbl <- tagme(projRecv = ...) %>% tbl('alltags')

getTracks <- function(x) { alltags.tbl %>% filter(tagDeployID == x) %>% collect() %>% as.data.frame() }

cl <- makeCluster(numCores, type = 'PSOCK')

clusterEvalQ(cl,  library(motus))
clusterExport(cl, 'alltags.tbl')

allDetections.df <- parLapply(cl, tagDeps, getTracks) %>% bind_rows()

stopCluster(cl)
```

**Comment by ajmacdonald3** [comment] 2021-01-21 20:22
That would definitely help speed things up, but would it help with RAM issues folks are having when trying to convert large datasets into flat files? I was thinking if they could filter out a lot of the short run false positives before converting to a flat file it might help avoid errors due to memory limits.

**Comment by denislepage** [comment] 2021-01-22 00:42
Yeah, I think that trying to constantly going back and forth in the same chapter between the 2 data sources will be confusing. Having a separate chapter should be easier (perhaps an appendix, but I see no reason to go that way). We can still cross-reference the 2 chapter and have a short section that helps people determine which of the two sources they should use under what circumstances.

The allruns table doesn’t provide any details that alltags doesn’t have, so the only real benefit is efficiency. A chapter focused on solutions for large dataset is probably most appropriate, although it will potentially overlap with some aspects of the previous chapter.

Here’s a quick skeleton start for the chapter. Very very drafty brain dump:

Solutions for working with large motus files.

There are 2 common issues when working with large motus files: slow queries and lack of memory. The alltags view was created mainly as a convenience for users as a way to combine in a single table most of the relevant data parts related to tag detections, but it isn’t well suited to work with large datasets. The alltags view is simply a script that joins different tables together, rather than a table containing data. As your motus file grows bigger, this causes 2 main problems: joining tables become much slower, and the resulting table could eventually exceed the memory available on your computer. Here, we are proposing some solutions to try to address those 2 challenges.


1.       Apply a filter to the data in dplyr before converting it into a dataframe

2.       Create your own table join statements based on smaller subsets of the data

3.       Use the GPS function to join the GPS and the hits data

4.       Pick your filters carefully.

5.       Use the allruns view instead of the alltags view



1.       Apply a filter to the data in dplyr before converting it into a dataframe

This solution was already introduce in chapter 3. A number of R packages such as dplyr and data.table allow you to apply filters to the data before they are actually loaded in memory. Rather than load the entire detection table, you can instead create loops that load only data for a single tag at a time, restrict the data for only one season, or remove the hits associated with short runs. The earlier you apply the filters, the faster the rest of the operations should be.


2.       The alltags virtual table is joining about a dozen different tables in the database, some of which you may not need. You can in theory replicate the same result as the alltags view by using a package such as data.table or dplyr, or even the standard R merge function. To be able to combine the data using the original table requires a good understanding of the motus data structure (needs documentation). <Ideally provide a full example that replicates alltags, and then some examples that filter the data prior to merging, and exclude some tables>



3.       The previous version of the alltags view (now renamed alltags_with_gps?) was trying to determine the close GPS reading available for every single detection. This is a very intensive function requiring potentially billions of operations on a large dataset. To get around this problem, we are providing a separate function that assigns the closest GPS reading using a few different alternative approaches. Most of the time, you should be able to rely directly on the GPS positions provided by the metadata, but such a join may be necessary with mobile deployments (e.g. airplane-mounted antennae).



a.       filter the data by tag and receiver

b.      apply the merge function depending on the level of resolution you need



4.       The filters that you use in your code may have a significant impact on the response time. For instance filters applied to the largest table (hits) may take longer to complete than those on smaller tables (batches or runs). <needs some examples>


5.       The runs table, which provides a single record for every run (single tag, on a single antenna or node, over an uninterrupted period of time) may often provide ample details for some type of data analysis of visualization. It is also much smaller than the hits table which is included in the altags view (a record for every burst). Instead of a timestamp (ts) for every hit, the allruns table provides the start and end timestamp of every run, as well as the number of hits within the run. The allruns virtual table can thus be used as a replacement to use the alltags in some circumstances, particularly when you are looking at movements of animals among receivers and are potentially less interested in local small-scale movements. The allruns table does not include information about signal strengths for instance, which you may need to help you identify false detections, but may be useful to help you quickly identify outliers by plotting the movements on a continental map. The allruns table can still allow you to measure arrival and departure time, travel speed, etc. <insert an example that takes allruns to plot track(s) on a map>

**Comment by jsayers-bsc** [comment] 2021-01-26 14:05
Related issues/conversations to this one include #721, #767, and #847

**Comment by jsayers-bsc** [comment] 2021-01-28 15:40
The allruns view definitely makes a birds-eye overview possible for large datasets. For Project 279 for example, collecting into a data frame/table just isn't possible on most computers. The allruns view however takes only 25 seconds (on a .motus file >8gb in size). Then with the allruns, batches/runs/date ranges can be identified for further filtering. The majority of projects probably won't need or use it, but for some it will be indispensable.

The Lotek UTC offset doesn't seem to be accounted for in the times. We should probably have a tsStartCorrected or similar here as well?

**Comment by denislepage** [comment] 2021-01-28 21:44
I’m going through the SQL code now. My allruns table was based on an older version of alltags, so I am now aligning them to be consistent, including adding the tsBeginCorrected and tsEndCorrected. I used the SQL version of alltags from the master, and confirmed that it was the same as the sandbox version.

My earlier version was including the gpsLat and gpsLon based on the start of the fix closest to the tsBegin value. We already have metadata coordinates, so I’m thinking that the default allruns view should not try to match the GPS table. For consistency, I can create an allrunsGPS view as well.

@steffilazerte, I am attaching the 2 scripts that we should implement for creating the new views, if you could add (or update?) them to the package. We’ll need new createAllRunsView.R and createAllRunsGPSView.R functions, and a way to update the previous databases.

If you can also confirm that the only difference in output fields with the alltags view version are those relevant to the hits table in both cases, that would be helpful.

The fields removed from alltags compared to allruns should be (runID and batchID are still there, but taken from other tables)

   t1.hitID as hitID,
   t1.runID as runID,
   t1.batchID as batchID,
   t1.ts as ts,
   CASE WHEN t6.utcOffset is null then t1.ts else t1.ts - t6.utcOffset * 60 * 60 end as tsCorrected,
   t1.sig as sig,
   t1.sigSD as sigsd,
   t1.noise as noise,
   t1.freq as freq,
   t1.freqSD as freqsd,
   t1.slop as slop,
   t1.burstSlop as burstSlop,

And the added fields should be:

   t2.tsBegin as tsBegin,
   t2.tsEnd as tsEnd,
   CASE WHEN t6.utcOffset is null then t2.tsBegin else t2.tsBegin - t6.utcOffset * 60 * 60 end as tsBeginCorrected,
   CASE WHEN t6.utcOffset is null then t2.tsEnd else t2.tsEnd - t6.utcOffset * 60 * 60 end as tsEndCorrected,

I don’t think there should be any other differences in the output. My earlier version had failed to include some of the more recent changes we had made in various places and was both missing some important fields and using deprecated names, so you should ignore my earlier version which was meant to demonstrate the feasibility of using allruns.

I changed also the condition in allrunsGPS to look the the first GPS record after the start of the run, not before. It’s a minor change, but we should still confirm that it works. The demo project is returning no values in those fields at the moment, and I don’t know if they should be.

**Comment by denislepage** [comment] 2021-01-28 21:47
Sorry, attachments now included.

[
[create allruns.txt](https://github.com/MotusDev/Motus-TO-DO/files/5890157/create.allruns.txt)
[create allrunsGPS.txt](https://github.com/MotusDev/Motus-TO-DO/files/5890158/create.allrunsGPS.txt)

](url)

**Comment by steffilazerte** [comment] 2021-01-28 21:59
I'll try to get this figured out tomorrow, but I'm still running into sandbox issues, and I'd really really like to finalize some other work in sandbox (just need to run the tests and make sure it's all good), before getting too embedded on a new big thing :) But at least the problem (#905) seem to be only with receivers so I should be able to start working with projects at least.

**Comment by denislepage** [comment] 2021-01-28 22:48
I would support deploying any other outstanding issues before tackling allruns. It isn't an urgent addition for most people.

**Comment by StuMackenzie** [comment] 2021-03-20 12:21
- Should we just integrate Yolanda's note into the introduction? 

fyi... I wrote a short script to help new users get going with their Motus data analysis. This contains a subset of the code in the detailed Motus R Book, which should still be used as the ultimate authority. It shows how you can efficiently download your data, convert a subset of it to a data frame, and save it offline as an *.rds file. It also shows how to generate some date & time variables using functions in lubridate.

Yolanda

https://groups.google.com/g/motus-wts/c/suNn0uN7EwI

**Comment by denislepage** [comment] 2021-03-20 21:58
I started exploring a little while back having a chapter or a section of the book for dealing with larger datasets. That would seem like the best place to put this.

As discussed back then, I think we can go through the same or similar examples to the main chapter and provide ideas for how to deal with large projects.

**Comment by steffilazerte** [comment] 2021-04-06 22:35
I have added the two new views (allruns, allrunsGPS) and the new field (attachment) to tagDeps. 

I think I've managed to avoid having to add an entry to the update database list because:

- Views are always added/recreated/updated when the database is opened with tagme, so these don't have to be added to an updater. 
- I added a function called `createFields()` that compares the fields in every table to the field list in the package. If any fields are missing, they are silently added.
    - The field list is a dataframe created when I release the package, built from the server list). This should mean that when new fields are added, all I need to do is re-create the field list adn they should be silently (or not silently?) added to existing tables.
    - If they need to be re-downloaded we can figure that out more explicitly.

**Comment by steffilazerte** [comment] 2021-04-14 15:35
It should be already there...? Which project were you testing with?

On the sample project I get `tsBeginCorrected` and `tsEndCorrected`
```
tags <- tagme(projRecv = 176, new = TRUE, update = TRUE)

dplyr::tbl(tags, "allrunsGPS")
# Source:   table<allrunsGPS> [?? x 57]
# Database: sqlite 3.35.2 [/home/steffi/Projects/Business/BSC/MOTUS/project-176.motus]
#    runID batchID  done motusTagID ambigID port  runLen    tsBegin    tsEnd tsBeginCorrected tsEndCorrected bootnum tagProjID
#    <int>   <int> <int>      <int>   <int> <chr>  <int>      <dbl>    <dbl>            <dbl>          <dbl>   <int>     <int>
# 1   8886      53     1      16047      NA 3          5     1.45e9   1.45e9      1445858390.    1445858565.      11       176
# 2  23305      64     1      16047      NA 1         11     1.45e9   1.45e9      1445857924.    1445858487.       4       176
# 3  23306      64     1      16047      NA 3          6     1.45e9   1.45e9      1445858341.    1445858623.       4       176
# 4  23307      64     1      16047      NA 2          5     1.45e9   1.45e9      1445858497.    1445858720.       4       176
# 5  23308      64     1      16047      NA 2          5     1.45e9   1.45e9      1445858826.    1445859050.       4       176

dplyr::tbl(tags, "allruns")
# Source:   table<allruns> [?? x 53]
# Database: sqlite 3.35.2 [/home/steffi/Projects/Business/BSC/MOTUS/project-176.motus]
#    runID batchID  done motusTagID ambigID port  runLen    tsBegin    tsEnd tsBeginCorrected tsEndCorrected bootnum tagProjID
#    <int>   <int> <int>      <int>   <int> <chr>  <int>      <dbl>    <dbl>            <dbl>          <dbl>   <int>     <int>
# 1   8886      53     1      16047      NA 3          5     1.45e9   1.45e9      1445858390.    1445858565.      11       176
# 2  23305      64     1      16047      NA 1         11     1.45e9   1.45e9      1445857924.    1445858487.       4       176
# 3  23306      64     1      16047      NA 3          6     1.45e9   1.45e9      1445858341.    1445858623.       4       176
# 4  23307      64     1      16047      NA 2          5     1.45e9   1.45e9      1445858497.    1445858720.       4       176
# 5  23308      64     1      16047      NA 2          5     1.45e9   1.45e9      1445858826.    1445859050.       4       176

```

**Comment by steffilazerte** [comment] 2022-05-06 17:56
Going to close this as I'm 99% sure it's been resolved (@j-sayers let me know if you think otherwise):

```
library(motus)
packageVersion("motus")
# [1] ‘5.0.0’

m <- tagme(1, new = FALSE, update = FALSE, dir = "..")

dplyr::tbl(m, "allruns") %>% dplyr::select(dplyr::contains("ts"))

# Source:   lazy query [?? x 5]
# Database: sqlite 3.38.3 [project-1.motus]
       tsBegin       tsEnd tsBeginCorrected tsEndCorrected tagDepComments
         <dbl>       <dbl>            <dbl>          <dbl> <chr>         
 1 1406445343. 1406445383.      1406445343.    1406445383. NA            
 2 1408406814. 1408406894.      1408406814.    1408406894. NA            
 3 1408674735. 1408674815.      1408674735.    1408674815. NA            
 4 1434550609. 1434550889.      1434550609.    1434550889. NA            
 5 1434550729. 1434550889.      1434550729.    1434550889. NA            
 6 1434550769. 1434550889.      1434550769.    1434550889. NA            
 7 1460761566. 1460761667.      1460761566.    1460761667. NA            
 8 1460761566. 1460761667.      1460761566.    1460761667. NA            
 9 1504431155. 1504445592.      1504431155.    1504445592. NA            
10 1503956275. 1503956575.      1503956275.    1503956575. NA  

dplyr::tbl(m, "allrunsGPS") %>% dplyr::select(dplyr::contains("ts"))

# Source:   lazy query [?? x 5]
# Database: sqlite 3.38.3 [project-1.motus]
       tsBegin       tsEnd tsBeginCorrected tsEndCorrected tagDepComments
         <dbl>       <dbl>            <dbl>          <dbl> <chr>         
 1 1406445343. 1406445383.      1406445343.    1406445383. NA            
 2 1408406814. 1408406894.      1408406814.    1408406894. NA            
 3 1408674735. 1408674815.      1408674735.    1408674815. NA            
 4 1434550609. 1434550889.      1434550609.    1434550889. NA            
 5 1434550729. 1434550889.      1434550729.    1434550889. NA            
 6 1434550769. 1434550889.      1434550769.    1434550889. NA            
 7 1460761566. 1460761667.      1460761566.    1460761667. NA            
 8 1460761566. 1460761667.      1460761566.    1460761667. NA            
 9 1504431155. 1504445592.      1504431155.    1504445592. NA            
10 1503956275. 1503956575.      1503956275.    1503956575. NA     
```

**Closed by steffilazerte** 2022-05-06 17:56 UTC
Labels: Testing needed, R package, Action and Assignment Required, Old Issue - Needs Re-evaluation
