### ISSUE TITLE
Duplicate registration of identical tag was permitted

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#684] opened 2020-02-25 16:49 UTC
I tried to register a tag that has already been registered, with the same ID and wav file. To my surprise the tag registered properly without an error or warning. 

In the case of identical names, but different BI, the [recommendation ](https://archived.sensorgnome.org/VHF_Tag_Registration/)is to append the ID to make it unique:

`If there are duplicate tagIDs with different burst intervals use the addition of ".1" for duplicates; eg. tag123.wav and tag123.1.wav could be present if there were two tag IDs 123 with different burst intervals. `

(I'm not sure if this is just a recommendation or whether there is an error or warning if the same ID is used twice during registration.)

But in this case, not only was the ID identical, but the BI, and indeed the wav file were also identical. So it really seems like there should have been an error during registration (or at least a warning)

Original tag [43245](https://motus.org/data/tags/edit?projectID=1&id=43245)
Duplicate tag [44023](https://motus.org/data/tags/edit?projectID=1&id=44023)

**Comment by Hussell** [comment] 2020-02-25 19:38
We prevent the registration of the same tag in the same quarter of the year, but because Lotek sells exact copies of the same tags later, after the batteries from the earlier ones should have run out, we don't prevent the registration of the same tag in different quarters of the year.

You will get a warning or error on the project's data issues page if you try to deploy these at the same time.

**Comment by jsayers-bsc** [comment] 2020-02-26 16:26
Ok good to know... 

Would it be worth using time elapsed rather than quarter (which could, in theory, be only a few days apart)? 

Then again, maybe this whole topic becomes obsolete entirely once the registration process moves over to Lotek, which hopefully isn't too far in the future!

**Comment by cjardine-bsc** [comment] 2020-02-27 18:02
Jeremy is correct about the cause and Josh is correct that there is no point addressing it separately since the problem will be resolved best by moving to Lotek registering tags. Closing

**Closed by cjardine-bsc** 2020-02-27 18:02 UTC
