### ISSUE TITLE
/api/receivers/deployments is missing test deployments

### ISSUE THREAD

**Issue by tve** [MotusDev/Motus-TO-DO#1049] opened 2021-11-15 22:27 UTC
The `/api/receivers/deployments` response is missing test deployments. This causes issues in sensorgnome.org, which uses this API call. The symptom is that SGs in test deployments are listed on the status page but clicking on them results in a 403, which comes from the the fact that sensorgnome.org cannot determine which project the SG belongs to, which is needed to authorize the user...

**Comment by Hussell** [comment] 2021-11-16 19:50
/api/receivers/deployments returns a list of public receiver deployments. So you're correct, no test deployments, by design. SensorGnome.org should expect that some receivers have no public deployments, and thus won't be in the list.

What's the URL returning 403?

**Comment by tve** [comment] 2021-11-16 19:54
That seems like a bad design: having sensorgnomes registered with sensorgnome.org but it can't fetch the relevant info in the bg...
The 403 is from clicking the left link in the table for a SG that is in a test deployment. Just take any SG, toggle the "test deployment" flag in the Motus deployment web page, go back to sensorgnome.org and click on that link. Hmmm, maybe once it has the info in memory it works, so you may have to register a new SG.
As it is now, the SG user guide should say in bold not to use test deployments because they prevent verifying that everything works.

**Comment by Hussell** [comment] 2021-11-16 20:15
SensorGnome.org can fetch information about receivers which don't have any public deployments through Motus' API, but it shouldn't expect to find that every receiver has deployments.

The purpose of test deployments is to verify that everything works, so yes, that's a problem. First time it's been reported, though.

**Comment by tve** [comment] 2021-11-16 20:30
> SensorGnome.org can fetch information about receivers which don't have any public deployments through Motus' API

How? Sensorgnome.org uses `https://motus.org/api/receivers/deployments` and that does not return non-public deployments. Is there a different API call it should use instead?

**Comment by Hussell** [comment] 2021-11-16 20:49
It should use `https://motus.org/api/receivers`, I think.

**Comment by tve** [comment] 2021-11-16 20:52
That's now what it's doing, though...
https://github.com/sensorgnome-org/sensorgnome-server/blob/master/sensorgnomeServer.go#L49

**Comment by denislepage** [comment] 2021-11-16 20:59
If I recall correctly, it’s the same API, but the list returned depends on user permissions. The motusServer user is assigned to a superuser group that can see everything.  However, assuming the receiver belong to your own project, you should be able to see it.

This is the function that motusServer calls to refresh it’s metadata cache.
https://github.com/MotusWTS/motusServer/blob/master/R/refreshMotusMetaDBCache.R

I think the key here is that new receivers need to be attached to a project by the user, which is a step that the project user has to do on the Motus site.

**Comment by Hussell** [comment] 2021-11-16 20:59
Yes, I know. There's a pull request already in to change exactly that.

**Comment by Hussell** [comment] 2021-11-16 21:01
@denislepage motusServer isn't involved in this, it's a request from sensorgnome.org directly to the motus.org API.

**Comment by leberrigan** [comment] 2022-03-25 11:29
Do we know if this issue has been resolved?

**Comment by Hussell** [comment] 2022-04-19 13:55
The minor fix hasn't been merged into the sensorgnome-server code. And the issue of how to deal with receivers which have no deployments (test or otherwise) hasn't been dealt with. Nonetheless, I am closing this because it's a sensergnome-server issue, not a MotusDev issue.

**Closed by Hussell** 2022-04-19 13:55 UTC
Labels: Bug, SensorGnome.org, Old Issue - Needs Re-evaluation
