### ISSUE TITLE
Error while registering a new receiver

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#251] opened 2018-05-31 15:33 UTC
Trying to register an SRX 800 to project 74 as "Lotek-313" and I'm getting the error: "Receiver ID was not saved, as it does not match the expected pattern for this receiver type."

According to the instructions that's the correct format: "Lotek SRX 800: "Lotek-XXX", where X is a numeral"

Is this a bug or am I doing something wrong?

**Comment by cjardine-bsc** [comment] 2018-05-31 19:04
I suspect this issue might be associated with the change to use double backslashes in the regex field of lk_receiver_type. 

I can't find the tool that reloads that cached lookup values to test my changes to the regex. I even tried changing the regex to NULL and it still wont register the receiver, so I know I need to reload the cache. I'm not seeing a tool to do so on the admin page, did this get created?

**Comment by Hussell** [comment] 2018-05-31 20:57
There's a bit missing from the SRX 800 regex. It should be:
^Lotek-([0-2]\\d{2}|3[0-8]\\d{2}|390)$

**Comment by cjardine-bsc** [comment] 2018-05-31 20:59
This receiver is actually a SRX 800D, so that's not the issue.

**Comment by Hussell** [comment] 2018-06-01 13:29
Also, I was mistaken about the regex being wrong. I guess I shouldn't try to fix things in the last five minutes at the end of a work day.

If this is an SRX 800D, then the serial number should be of the form Lotek-DXXXXXX. Lotek-313 is the correct form for an SRX 800.

**Comment by Hussell** [comment] 2018-06-01 13:37
Reloading the error codes actually reloads all the lookup tables.

**Comment by cjardine-bsc** [comment] 2018-06-01 15:58
Yes, we know the correct regex form is Lotek-D000313. that is what we are uploading. Sorry we're not putting all the details here, Zoe and I are sitting next to each other so we sorted all that out between ourselves. 

I just needed the question about the lookup tables answered.

**Comment by cjardine-bsc** [comment] 2018-06-01 16:22
Changing the regex to remove the double backslash allows the receiver to be registered correctly (Zoe this is now complete). 

^Lotek-D\\d{6}$  Registration fails
^Lotek-D\d{6}$ Registration successful

Jeremy, I'm assuming you needed these changed to double backslashes to allow registration through the the API (I'm making assumptions)? Unfortunately that results in the registrations failing through the webpage. I know the syntax for regex changes slightly depending on the configuration of the environment where it's being run, so it looks like we have a mismatch.  

Looking at sandbox, the regex syntax used to be ^Lotek-D[0-9]{6}$ which I believe (?) worked for both purposes (at least I wasn't aware of either of them failing). Do we know why this was changed?  

We can either address the conflicting needs between the web page and John's api or we can try and revert the regex syntax to something that works for both.

**Comment by Hussell** [comment] 2018-06-01 18:53
#213 has the discussion where the regex strings were changed. It looks like I was testing using the API there, and assumed it would work for the website too.

**Comment by pmorrill** [comment] 2018-06-01 19:05
I will take a look at the website procedure. Not sure why it would not work there as well.

**Comment by pmorrill** [comment] 2018-06-04 14:15
In the web-based receiver type validation, the doubled-backslashes in fact prevent proper regex matching. (As reported by C. above).

In the api receiver registration proc [prInsertSensorsHashKeys] there is a validation of the receiver TYPE, but not of the serial number. That is, a check is made to ensure the type (eg: 'LOTEKSRX800') exists in the lk_receiver_type table. But I am not seeing any validation of the serial number itself. Catherine - can you confirm that?

There is also no validation of serNo in the api java code, during recv registration.,

If this is so, then the double slashes should be left out of the regex expressions. I am unclear on why we added them (https://github.com/MotusDev/Motus-TO-DO/issues/213). Or, I am completely missing a serial number validation  during API registration of receivers?

**Comment by cjardine-bsc** [comment] 2018-06-04 18:17
Like you say Paul, there isn't anything I can see in the database procs that validated the serial number.

Jeremy mentions in #213 that it is the java processing that needs the double backslash, but if it isn't in the api java then maybe its something John does before passing to the api?

At the moment I've removed the double backslash so things are working on the website. I've updated sandbox to have the double backslashes so Jeremy can do some testing and figure out where the problem is located. 

We might want to re-visit my comment above. It might be the simplest solution: 

Looking at sandbox, the regex syntax used to be ^Lotek-D[0-9]{6}$ which I believe (?) worked for both purposes (at least I wasn't aware of either of them failing). Do we know why this was changed?

**Comment by pmorrill** [comment] 2018-06-04 18:43
John would have never tested a tag registration against the sandbox. But I don't think that John would have used our regex strings in any way, would he have?? If we don't validate in our side of the api, then how could our api regex's affect the process, if he does not query for them? 

There is a lookup entrypoint in our java api, that returns the lk_receiver_type table records...is he maybe calling that and getting the regex from us? News to me if so. In that case, we do have a possible mismatch.

Maybe Jeremy could tell us if that entrypoint is being used by John's code anywhere. Search for 'api/receivertypes'. It's the only way he could be getting our stored values to use in the SG environment,

**Comment by cjardine-bsc** [comment] 2018-06-04 18:54
yeah, that's what I was thinking, that maybe John pulled the regex into his copy of the database. As you say we're not sure that is happening.

I suspect Jeremy might already know where the processing is located, since he asked me to change these to double backslashes in the first place. Fingers crossed he'll be able to locate it easily!

**Comment by Hussell** [comment] 2018-06-05 14:23
I've gone through looking for the places where the regexes are used, and tested with and without backslashes. John doesn't use the regexes, and the strings in the database don't need double backslashes. I suspect I was not reloading the MotusLookup tables correctly when I was testing #213.

**Comment by jbrzusto** [comment] 2018-06-05 14:40
FWIW, I can't see how registering a receiver on motus.org would touch any code on sgdata.motus.org, but for future reference, here are some notes.

From https://github.com/jbrzusto/motusServer/blob/master/R/motusConstants.R, the only motus.org
APIs used on sgdata.motus.org are:
```R
MOTUS_API_REGISTER_TAG          = "https://motus.org/api/tag/register"
MOTUS_API_DEPLOY_TAG            = "https://motus.org/api/tag/deploy"
MOTUS_API_SEARCH_TAGS           = "https://motus.org/api/tags/search"
MOTUS_API_USER_VALIDATE         = "https://motus.org/api/user/validate"
MOTUS_API_REGISTER_RECEIVER     = "https://motus.org/api/receiver/register"
MOTUS_API_LIST_PROJECTS         = "https://motus.org/api/projects"
MOTUS_API_LIST_SENSORS          = "https://motus.org/api/receivers/list"
MOTUS_API_LIST_SENSOR_DEPS      = "https://motus.org/api/receiver/sensordeployments"
MOTUS_API_LIST_SPECIES          = "https://motus.org/api/species"
```

The `receiver/register` API is only called when a `deviceID` is needed for a receiver from which no data
have been seen before.   When it does so for a Lotek receiver, it uses the function [motusServer::getRecvModel](https://github.com/jbrzusto/motusServer/blob/master/R/getRecvModel.R)
to calculate a receiver type from its serial number, according to rules supplied by Lotek.

e.g. depending on what is right for the receiver at the start of this thread:
```R
> getRecvType("Lotek-313")
[1] "LOTEKSRX800"
> getRecvType("Lotek-D000313")
[1] "LOTEKSRX800D"
```
The serial number is obtained directly from the .DTA file being processed.  So one potential problem might be that users are generating .DTA files from an older version of the Lotek software that doesn't know
the difference between SRX800 and SRX800D.

**Comment by cjardine-bsc** [comment] 2018-06-19 19:09
I've removed the double backslashes from both DBs. 

Closing this now, with the note that #274 suggests we need to address the issues with lotek receivers and SRX800 and SRX800Ds. I'll open a separate issue just for that.

**Closed by cjardine-bsc** 2018-06-19 19:09 UTC
Labels: bug
