### ISSUE TITLE
Login Credentials Rejected when Using Motus Function 'tellme'

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#503] opened 2019-06-13 16:24 UTC
When checking to see if new data exist for a given database it produces the following error:
```
> tellme(projRecv = 28)

# Error in srvQuery(API = Motus$API_SIZE_OF_UPDATE_FOR_TAG_PROJECT, params = list(projectID = projectID,  : 
#  Authentication failed : Authentication token was absent, invalid or expired. 
```

I tried the same using _beta_ and the server timed out

```
 Error in function (type, msg, asError = TRUE)  : 
  Operation timed out after 300000 milliseconds with 0 bytes received 
```

The _tagme_ function works as expected.

**Comment by adamdsmith** [comment] 2019-06-13 16:31
Thanks Lucas.

I provided a `tellme` example for simplicity. I get the same error with `tagme`.

For example, the following two commands produce the same error:

``` r
library(motus)
rcv <- "SG-CE03RPI23C18"
Motus$userLogin <- "adamdsmith"
Motus$userPassword <- "**"
tmp <- tellme(projRecv = rcv, new = TRUE)
#> Error in value[[3L]](cond): The motus data server rejected your login credentials
tmp2 <- tagme(projRecv = rcv, new = TRUE)
#> Error in value[[3L]](cond): The motus data server rejected your login credentials
```

**Comment by leberrigan** [comment] 2019-06-13 16:49
I think I sorted out the issue - the account you are using does not have the necessary permissions. Your other account (user: 'adam') is an administrator account and should work with these functions

**Comment by adamdsmith** [comment] 2019-06-13 16:55
I get the same problems with my admin account (see below). Plus, user `adamdsmith` should have these permissions. It's worked without issue until the last week. Plus, I can still access the summaries for these projects with `adamdsmith` on sgdata.motus.org.

``` r
library(motus)
rcv <- "SG-CE03RPI23C18"
Motus$userLogin <- "adam"
Motus$userPassword <- "**"
tmp <- tellme(projRecv = rcv, new = TRUE)
#> Error in value[[3L]](cond): The motus data server rejected your login credentials
tmp2 <- tagme(projRecv = rcv, new = TRUE)
#> Error in value[[3L]](cond): The motus data server rejected your login credentials
```

**Comment by leberrigan** [comment] 2019-06-13 17:18
Hmm.. strange! I can't seem to replicate your issue using the example code you provided: 
```
> library(motus)
> rcv <- "SG-CE03RPI23C18"
> Motus$userLogin <- "adam"
> Motus$userPassword <- "***"
> tmp2 <- tagme(projRecv = rcv, new = TRUE)

updateMotusDb started (9 rows)
 - Create new view allambigs that converts ambig columns into rows
 - remove previous version of alltagswithambigs view
 - Remove empty gps detections
 - Add a new column "siteName" to table "recvDeps".Error in result_create(conn@ptr, statement) : 
  duplicate column name: siteName

 - Create (or modify previous version of) filters
 - Create (or modify previous version of) runsFilters
 - Create new table for custom tag metadataError in result_create(conn@ptr, statement) : not an error

 - Remove previous version of alltags
 - Create new version of alltags that includes additional deployment fields

> tmp2
src:  sqlite 3.22.0 [C:\Users\leber\Documents\BSC\Motus\R\Landowner Reports\SG-CE03RPI23C18.motus]
tbls: admInfo, allambigs, alltags, antDeps, batches, batchRuns, clarified, filters, gps, hits, meta, projAmbig, projs, pulseCounts, recvDeps, recvs, runs,
  runsFilters, species, tagAmbig, tagDeps, tagProps, tags


> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] motus_1.0.0     motusClient_1.0 ggplot2_3.1.0   lubridate_1.7.4 maptools_0.9-5  sp_1.3-1        dbplyr_1.3.0    dplyr_0.8.0.1   RSQLite_2.1.1  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0       plyr_1.8.4       pillar_1.3.1     compiler_3.5.2   tools_3.5.2      digest_0.6.18    bit_1.1-14       memoise_1.1.0    tibble_2.0.1    
[10] gtable_0.2.0     lattice_0.20-38  pkgconfig_2.0.2  rlang_0.3.1      DBI_1.0.0        rstudioapi_0.9.0 yaml_2.2.0       withr_2.1.2      stringr_1.4.0   
[19] bit64_0.9-7      grid_3.5.2       tidyselect_0.2.5 glue_1.3.0       R6_2.4.0         foreign_0.8-71   purrr_0.3.0      blob_1.1.1       magrittr_1.5    
[28] scales_1.0.0     assertthat_0.2.0 colorspace_1.4-0 stringi_1.3.1    lazyeval_0.2.1   munsell_0.5.0    crayon_1.3.4    
```

**Comment by adamdsmith** [comment] 2019-06-13 17:24
That is weird. I've upgraded all relevant packages, so it's not that.

As I said, this is a new development using code that has worked many times before...

**Comment by Hussell** [comment] 2019-06-14 15:22
I'm also seeing normal behaviour (using my own login and password). The error message you're seeing is given when anything at all fails to work during Motus login, so it could be anything from a mis-typed password to the server being down.

I've changed motusClient to display a more informative error message, so if this is still happening you should at least be able to see whether this is a problem with connecting to the server vs. a problem with your credentials.

**Comment by adamdsmith** [comment] 2019-06-14 17:28
Thanks. Looks like an SSL certificate issue. I take it the "unable to get local issuer certificate" means it's probably something I'll have to resolve on my end...

``` r
tmp <- tellme(projRecv = rcv, new = TRUE)
#> Error in value[[3L]](cond): Motus login failed with error message: Error in function (type, msg, asError = TRUE) : SSL certificate problem: unable to get local issuer certificate
```

Created on 2019-06-14 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by denislepage** [comment] 2019-06-14 20:07
Adam,

This could be helpful.
https://stackoverflow.com/questions/46331066/quantmod-ssl-unable-to-get-local-issuer-certificate-in-r

Sounds like it is a client issue. I think we may be moving away from rCurl in our upcoming package release.

We’re looking into posting the release shortly, but you can also give it a try now.
https://github.com/MotusWTS/motus/tree/staging

**Comment by adamdsmith** [comment] 2019-06-17 15:31
Thanks Denis. 

Didn't try the winSSL "fix" yet. I may do so for completeness sake, but the process is working as expected using the staging branch.

**Comment by adamdsmith** [comment] 2019-06-17 16:58
Guess I spoke too soon. It processes all of Project 4's receivers well enough but errors out at the end:

`Error: Failed to generate activities for tag project.`

Maybe this being a new table (I *think*) has something to do with it...

In any case, I also moved back to the master branch and tried the winSSL and suppressing SSL verification options, but with the same "local issuer certificate" error...

**Comment by denislepage** [comment] 2019-06-17 17:59
Steffi, could you look into this error?

**Comment by steffilazerte** [comment] 2019-06-17 19:00
Will do

**Comment by steffilazerte** [comment] 2019-06-17 19:28
Hmm, I'm not sure exactly what's going on, but it might be related to conflict between the old `motus` & `motusClient` packages vs. the new `motus` package (combining the two old packages).

@adamdsmith if you're willing to do some more trouble shooting, could you try the following:

1. `remove.packages(c("motus", "motusClient"))`
2. `devtools::install_github("motusWTS/motus@staging")` (or use the `remotes` package)
3. Start a fresh R session
4. Try out your download again

If you have no problems, hooray! 

If you still have problems, could you try with the `motus.sample` user, and let me know how that goes?

`my_tags <- tagme(176, new = TRUE, update = TRUE)`

**Comment by adamdsmith** [comment] 2019-06-17 20:17
Thanks Steffi.

Still no luck with with the new `motus` package:

``` r
library(motus)
rcv <- "SG-CE03RPI23C18"
motus_vars$userLogin <- "adam"
motus_vars$userPassword <- "SadieMae2010"
test <- tagme(projRecv = rcv, new = TRUE)
#> Error: The motus data server rejected your login credentials
```

What is the `motus.sample` user password?

**Comment by adamdsmith** [comment] 2019-06-17 20:23
FWIW, my attempt to download project 176 also failed with admin credentials:

``` r
library(motus)
motus_vars$userLogin <- "adam"
motus_vars$userPassword <- "***"
my_tags <- tagme(176, new = TRUE, update = TRUE)
#> Warning: `overscope_eval_next()` is deprecated as of rlang 0.2.0.
#> Please use `eval_tidy()` with a data mask instead.
#> This warning is displayed once per session.
#> Warning: `overscope_clean()` is deprecated as of rlang 0.2.0.
#> This warning is displayed once per session.
#> updateMotusDb started (11 versions updates)
#>  - Create new view allambigs that converts ambig columns into rows
#>  - Remove previous version of alltagswithambigs view
#>  - Remove empty gps detections
#>  - Add a new column 'siteName' to table 'recvDeps'.
#>  - Create (or modify previous version of) filters
#>  - Create (or modify previous version of) runsFilters
#>  - Create new table for custom tag metadata
#>  - Remove previous version of alltags
#>  - Create new version of alltags that includes additional deployment fields
#>  - Create new 'activity' table
#>  - Add 'utcOffset' field to 'recvDeps' table
#> Error: The motus data server rejected your login credentials
```

**Comment by steffilazerte** [comment] 2019-06-17 20:36
Hmm, this looks like back to the credentials problem (not the activities problem).

Could you try with `motus.sample` (`motus.sample` is both the username and password, sorry about that!)

**Comment by adamdsmith** [comment] 2019-06-17 21:11
Same credentials error with `motus.sample`. 

But I can get around it by suppressing SSL verification.

``` r
library(motus)
httr::set_config(httr::config(ssl_verifypeer = FALSE))
motus_vars$userLogin <- "motus.sample"
motus_vars$userPassword <- "motus.sample"
my_tags <- tagme(176, new = TRUE, update = TRUE)
#> Warning: `overscope_eval_next()` is deprecated as of rlang 0.2.0.
#> Please use `eval_tidy()` with a data mask instead.
#> This warning is displayed once per session.
#> Warning: `overscope_clean()` is deprecated as of rlang 0.2.0.
#> This warning is displayed once per session.
#> Project   176:    132 batch records to check
#> batchID       53 (#     1 of    132): got     15 activity records
#> batchID       64 (#     2 of    132): got    155 activity records
...
#> batchID   102773 (#   131 of    132): got     43 activity records
#> batchID   102776 (#   132 of    132): got     35 activity records
```

However, applying this "fix" to my original problem (i.e., updating an existing database for Project 4) generates the `failed to generate activities for tag project` error. So it looks like the issue is related to an existing database.

**Comment by steffilazerte** [comment] 2019-06-17 21:30
Hmm, I'm not sure why you're getting an SSL verification error, perhaps, as mentioned above, it's related to an local configuration issue.

As for the data base error, I agree, looks like the issue is adding a new data base to an existing database. 

Could you let me know which version of the database you have:
`dplyr::tbl(my_tags$con, "admInfo")`

And give me the output from `devtools::session_info()`?

**Comment by adamdsmith** [comment] 2019-06-17 21:48
``` r
library(motus)
my_tags <- tagme(176, new = TRUE, update = FALSE)
dplyr::tbl(my_tags$con, "admInfo")
#> # Source:   table<admInfo> [?? x 2]
#> # Database: sqlite 3.22.0
#> #   [C:\Users\adsmith\AppData\Local\Temp\3\RtmpCsXP92\project-176.motus]
#>   key        value              
#>   <chr>      <chr>              
#> 1 db_version 2019-04-22 00:00:00
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.1 (2018-07-02)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/New_York            
#>  date     2019-06-17                  
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version     date       lib
#>  assertthat    0.2.1       2019-03-21 [1]
#>  backports     1.1.4       2019-04-10 [1]
#>  bit           1.1-14      2018-05-29 [1]
#>  bit64         0.9-7       2017-05-08 [1]
#>  blob          1.1.1       2018-03-25 [1]
#>  callr         3.2.0       2019-03-15 [1]
#>  cli           1.1.0       2019-03-19 [1]
#>  colorspace    1.4-1       2019-03-18 [1]
#>  crayon        1.3.4       2017-09-16 [1]
#>  DBI           1.0.0       2018-05-02 [1]
#>  dbplyr      * 1.4.1       2019-06-05 [1]
#>  desc          1.2.0       2018-05-01 [1]
#>  devtools      2.0.2       2019-04-08 [1]
#>  digest        0.6.19      2019-05-20 [1]
#>  dplyr       * 0.8.1.9000  2019-06-17 [1]
#>  evaluate      0.13        2019-02-12 [1]
#>  fansi         0.4.0       2018-11-07 [1]
#>  foreign       0.8-70      2017-11-28 [1]
#>  fs            1.3.1       2019-05-06 [1]
#>  ggplot2     * 3.2.0       2019-06-16 [1]
#>  glue          1.3.1       2019-03-12 [1]
#>  gtable        0.3.0       2019-03-25 [1]
#>  highr         0.8         2019-03-20 [1]
#>  htmltools     0.3.6       2017-04-28 [1]
#>  knitr         1.22        2019-03-08 [1]
#>  lattice       0.20-35     2017-03-25 [1]
#>  lazyeval      0.2.2       2019-03-15 [1]
#>  lubridate   * 1.7.4       2018-04-11 [1]
#>  magrittr      1.5         2014-11-22 [1]
#>  maptools    * 0.9-5       2019-02-18 [1]
#>  memoise       1.1.0       2017-04-21 [1]
#>  motus       * 1.5.0       2019-06-17 [1]
#>  munsell       0.5.0       2018-06-12 [1]
#>  pillar        1.4.1.9000  2019-06-04 [1]
#>  pkgbuild      1.0.2       2018-10-16 [1]
#>  pkgconfig     2.0.2       2018-08-16 [1]
#>  pkgload       1.0.1       2018-10-11 [1]
#>  prettyunits   1.0.2       2015-07-13 [1]
#>  processx      3.3.1       2019-05-08 [1]
#>  ps            1.3.0       2018-12-21 [1]
#>  purrr         0.3.2       2019-03-15 [1]
#>  R6            2.4.0       2019-02-14 [1]
#>  Rcpp          1.0.1.3     2019-06-04 [1]
#>  remotes       2.0.4       2019-04-10 [1]
#>  rlang         0.3.99.9003 2019-06-17 [1]
#>  rmarkdown     1.12        2019-03-14 [1]
#>  rprojroot     1.3-2       2018-01-03 [1]
#>  RSQLite     * 2.1.1       2018-05-06 [1]
#>  scales        1.0.0       2018-08-09 [1]
#>  sessioninfo   1.1.0       2018-09-25 [1]
#>  sp          * 1.3-1       2018-06-05 [1]
#>  stringi       1.4.3       2019-03-12 [1]
#>  stringr       1.4.0       2019-02-10 [1]
#>  testthat      2.0.0       2017-12-13 [1]
#>  tibble        2.1.3.9000  2019-06-17 [1]
#>  tidyselect    0.2.5       2018-10-11 [1]
#>  usethis       1.4.0       2018-08-14 [1]
#>  utf8          1.1.4       2018-05-24 [1]
#>  vctrs         0.1.0.9004  2019-06-17 [1]
#>  withr         2.1.2       2018-03-15 [1]
#>  xfun          0.6         2019-04-02 [1]
#>  yaml          2.2.0       2018-07-25 [1]
#>  zeallot       0.1.0       2018-01-28 [1]
#>  source                           
#>  CRAN (R 3.5.3)                   
#>  CRAN (R 3.5.3)                   
#>  CRAN (R 3.5.0)                   
#>  CRAN (R 3.5.0)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.3)                   
#>  CRAN (R 3.5.3)                   
#>  CRAN (R 3.5.3)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.3)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.3)                   
#>  CRAN (R 3.5.1)                   
#>  Github (tidyverse/dplyr@b357118) 
#>  CRAN (R 3.5.3)                   
#>  Github (brodieG/fansi@ab11e9c)   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.3)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.3)                   
#>  CRAN (R 3.5.3)                   
#>  CRAN (R 3.5.3)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.3)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.3)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.3)                   
#>  CRAN (R 3.5.1)                   
#>  Github (motusWTS/motus@974f3d1)  
#>  CRAN (R 3.5.1)                   
#>  Github (r-lib/pillar@c017f20)    
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.3)                   
#>  CRAN (R 3.5.3)                   
#>  CRAN (R 3.5.3)                   
#>  CRAN (R 3.5.2)                   
#>  Github (RcppCore/Rcpp@6062d56)   
#>  CRAN (R 3.5.3)                   
#>  Github (r-lib/rlang@96a69a2)     
#>  CRAN (R 3.5.3)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.3)                   
#>  CRAN (R 3.5.3)                   
#>  CRAN (R 3.5.1)                   
#>  Github (tidyverse/tibble@cb6ff6a)
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  Github (r-lib/vctrs@4f06a6d)     
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.3)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.3)                   
```

**Comment by steffilazerte** [comment] 2019-06-17 21:53
Sorry @adamdsmith, I meant `dplyr::tbl(my_tags$con, "admInfo")` for your older database (project 4?)

**Comment by adamdsmith** [comment] 2019-06-17 22:29
I wondered. :) I checked it too and it, surprisingly, was the same. I'll note that this database is actually ~ 20 individual receiver databases that I loop through and then consolidate.

**Comment by adamdsmith** [comment] 2019-06-18 13:26
Following up. Seems my last note about cycling through receivers was relevant. I've isolated the issue to a single receiver. And it doesn't appear to matter whether I update an existing version of the database or start a fresh one. Here's my attempt to start fresh. Seems to create the database OK (though not sure if it's populating it), but fails when updating it:

``` r
rcv <- "SG-3021RPI2BBB8"
test <- tagme(projRecv = rcv, new = TRUE)
#> Warning: `overscope_eval_next()` is deprecated as of rlang 0.2.0.
#> Please use `eval_tidy()` with a data mask instead.
#> This warning is displayed once per session.
#> Warning: `overscope_clean()` is deprecated as of rlang 0.2.0.
#> This warning is displayed once per session.
#> updateMotusDb started (11 versions updates)
#>  - Create new view allambigs that converts ambig columns into rows
#>  - Remove previous version of alltagswithambigs view
#>  - Remove empty gps detections
#>  - Add a new column 'siteName' to table 'recvDeps'.
#>  - Create (or modify previous version of) filters
#>  - Create (or modify previous version of) runsFilters
#>  - Create new table for custom tag metadata
#>  - Remove previous version of alltags
#>  - Create new version of alltags that includes additional deployment fields
#>  - Create new 'activity' table
#>  - Add 'utcOffset' field to 'recvDeps' table
dplyr::tbl(test$con, "admInfo")
#> # Source:   table<admInfo> [?? x 2]
#> # Database: sqlite 3.22.0
#> #   [C:\Users\adsmith\AppData\Local\Temp\3\RtmpQ7uapj\SG-3021RPI2BBB8.motus]
#>   key        value              
#>   <chr>      <chr>              
#> 1 db_version 2019-04-22 00:00:00
test <- tagme(projRecv = rcv, update = TRUE)
#> Error: Failed to generate activities for tag project.
```

**Comment by steffilazerte** [comment] 2019-06-18 14:08
That's great! This will really help me narrow in on the specific problem, I'll see about getting access to this receiver and will let you know once I've figured it out.

**Comment by steffilazerte** [comment] 2019-06-18 18:47
Of course after all that it was a simple fix! That receiver has no detected tags, and therefore no batches. I added a catch for the activities function to skip receivers with no batches and we should be good to go. 
Can you confirm that it solves the activities problem? Thanks!

**Comment by adamdsmith** [comment] 2019-06-18 18:53
How anticlimactic... So what fork should I be using?

**Comment by steffilazerte** [comment] 2019-06-18 18:54
`staging`, thanks

**Comment by adamdsmith** [comment] 2019-06-18 20:03
Can confirm that it is operational again. Thanks!

**Comment by denislepage** [comment] 2019-06-18 20:04
woohoo.

**Comment by steffilazerte** [comment] 2019-09-17 19:08
I think this is done, can someone close the issue?

**Closed** 2019-09-20 13:26 UTC
Labels: bug
