### ISSUE TITLE
Private receivers displayed on Receiver map; pop up displays array of receiver metadata

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#849] opened 2020-11-09 14:38 UTC
Recently the receiver map has been behaving oddly. When not logged in, receivers that should not be displayed (Receiver deployment data set to User; e.g. Project 203) are still being displayed. However the popup for them, and any other receivers whose access level should not allow them to be shown on the map without being logged in simply displays the array of all the receiver metadata. 

![image](https://user-images.githubusercontent.com/55001144/98554955-5522f280-226f-11eb-9c90-b42d6c63192d.png)

**Comment by Hussell** [comment] 2020-11-09 19:30
I'm unable to reproduce this. The test receiver in your screenshot is hidden when I'm logged out, and has a normal popup when I'm logged in.

**Comment by jsayers-bsc** [comment] 2020-11-09 19:34
Strange... I don't see it now either. I've noticed this a few times in the last week with that Test receiver as well as Project 203's receivers (which are also just hidden now whether or not I'm logged out). Also oddly, when I viewed the page source previously when seeing the weird popup, it consisted of just one very very long line: that array and nothing else. No html or anything else in the source! I'll make a note when I see it again...

**Comment by cjardine-bsc** [comment] 2020-11-09 19:55
The database was locked this morning. I reset it when I got to the office and then went into a string of meetings (actually I did it while I was in a meeting....shhhhh). I'll try and sleuth out what went wrong now. 

Denis, SP_WHO and SP_WHO2 were not returning anything in live. So I did a server restart.

**Comment by Hussell** [comment] 2020-11-11 19:00
Still working for me, so I'm closing this on the assumption it was a temporary thing due to the service outage.

**Closed by Hussell** 2020-11-11 19:00 UTC
Labels: couldn't reproduce
