### ISSUE TITLE
Tag deployments template: speciesName vs. speciesCode

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#782] opened 2020-08-24 13:01 UTC
It looks like the tag deployment template only accepts the column '**speciesName**', which can be English, French, or Scientific, according to the master 'MotusSpeciesList.csv' file (see #781). However, I noticed our friend from project 123 has been using species IDs under the header '**speciesCode**' in their tags template--is this wrong?

Are we also accepting species IDs and 4-letter codes? If no, why not? If yes, what header must they be under? '**speciesName**' or '**speciesCode**'?

Species IDs and codes also exist in 'MotusSpeciesList.csv' the same file, but it's not listed in 'MotusFieldDescriptions.csv'.

**Comment by denislepage** [comment] 2020-08-24 23:34
There is no speciesCode field in the db table (nor a speciesID field), and I am pretty sure we don’t support it. Presumably we give users a warning if they are trying to import data in unsupported field names?
However, I am almost positive that we do support matching species codes, when they are entered in the speciesName field. The SQL code seems to confirm this.

I don’t think we are supporting numeric speciesID. Perhaps we should, since we are converting their names or codes into speciesID’s internally.

I just noticed also a “test” column in the tag deployment template. That presumably is a mistake, or is this meant to represent test tag? It just looks odd, but probably too late to change it to testTag.

**Comment by StuMackenzie** [comment] 2021-01-24 16:37
Can an action be identified? Otherwise  please close.

**Comment by leberrigan** [comment] 2022-03-24 22:03
I have confirmed that many tag deployments have `speciesName` that is a 4-letter species code like "MYWA" or "LOWA", like [12659](https://motus.org/data/tag/deployment/edit?projectID=50&id=12659)

**Comment by denislepage** [comment] 2022-03-24 22:38
The main field that matters in the deployment table is species_id. 

The species_name field is not visible in R, only the species_id, which they can resolve against the table of species we also provide.

The species_name I think is a placeholder for whatever people have used to find the species. Not sure it matters what is in that field, as long as the species ID is resolved. A question for @cjardine-bsc : can we confirm that species codes are accepted as a valid way to submit the deployment file? 

If they use the search option in the web deployment page, we copy the scientific name to that field and resolve the species ID. However, species codes do not seem to be a valid way to search for species at the moment, which likely needs fixing. The proc prSearchSpecies was ignoring species codes because we used a language parameter, so I took at out, and added a bit more logic.

Now, the search will return names if your search matches the 4 (atlas) or 6 letter codes (eBird codes). The first covers North America, the latter covers all birds. The 6 letter codes can be used in any languages. The 4 letter codes will only match in the language you are using (e.g. MODO in English = Mourning Dove, MODO in French = Moineau domestique, but moudov is the same in both, and I don't have 6 letter codes for French names).

I've made the change in both servers, but that should be tested.

```
EXEC dbo.[prSearchSpecies] 'COYE', 15, null, 'EN'
EXEC dbo.[prSearchSpecies] 'COYE', 15, null, 'FR'
EXEC dbo.[prSearchSpecies] 'PAMA', 15, null, 'FR'
EXEC dbo.[prSearchSpecies] 'COYE', 15, null, null
EXEC dbo.[prSearchSpecies] 'PAMA', 15, null, null
EXEC dbo.[prSearchSpecies] 'comyel', 15, null, 'EN'
EXEC dbo.[prSearchSpecies] 'comyel', 15, null, 'FR'
EXEC dbo.[prSearchSpecies] 'comyel', 15, null, null

EXEC dbo.[prSearchSpecies] 'MODO', 15, null, 'EN'
EXEC dbo.[prSearchSpecies] 'MODO', 15, null, 'FR'

```
The latter 2 return a bunch of furry critters in addition to either MODO. I turned off that feature for scientific name match in NatureCounts, but the benefit of trimming down the result on a checklist are greater than a single deployment. It's probably best to keep providing more results than fewer and have people try to clarify their search.

**Comment by denislepage** [comment] 2022-03-24 22:39
Once tested, I think we can close this?

**Closed** 2022-03-24 23:44 UTC
Labels: Bug, Followup Required - Resolved?, Oustanding Tasks to be completed

**Comment by cjardine-bsc** [comment] 2022-05-05 23:20
Re: A question for @cjardine-bsc : can we confirm that species codes are accepted as a valid way to submit the deployment file? 

Confirmed. 

I suspect the initial question was related to the bulk tag deployment upload tool. The species field would accept English, French, Scientific and species code, but not species_id. 

I've changed that so it will. Deployed to sandbox. 

UPDATE #temp_speciesID
SET speciesID_fromName = species_id 
FROM #temp_speciesID a inner join lk_species b 
on concat_species_name = species_id  
WHERE species_status in (1,3) and species_id is not null and taxon_group IN ('BATS', 'BEETLES',
'BIRDS', 'BUTTERFL', 'HYMENOPTERA', 'MAMMALS', 'MOTHS', 'ODONATA','ORTHOPTERA','REPTILES' )

Can sync to live once tested.
