### ISSUE TITLE
Clicking on Data Issues from dropdown does not redirect to login page

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#473] opened 2019-04-08 20:40 UTC
From the motus homepage if you click on Data Issues in the Manage data drop down it just refreshes the home page, it should redirect to the login page. 

https://motus.org/data/issues

**Comment by Hussell** [comment] 2019-04-08 20:51
Duplicate of #419. Bumped higher on my priority list.

**Closed by Hussell** 2019-04-08 20:51 UTC
Labels: bug, duplicate
