### ISSUE TITLE
End date not saving in new deployments

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#67] opened 2017-09-12 18:36 UTC
I created a new deployment, entered a start date, clicked "save", entered an end date, clicked "save" again.  All looked fine but to be sure I clicked "save and close" when I was taken back to the receivers page (https://motus.org/data/receivers/edit?projectID=1&id=395) there were no dates entered for the deployment.  Opened the deployment and tried again with same issue.  To get the dates to stick I had to save a start date, close the deployment, re-open the deployment, and then enter and end date.

**Comment by Hussell** [comment] 2017-09-14 13:21
Confirmed on sandbox.

**Comment by pmorrill** [comment] 2017-09-20 18:13
I have posted a fix for this bug, into sandbox as well as beta3. Not sure how long beta3 is going to be the 'live' software, but this is critical so a fix needs to be tested there (tomorrow?) then pushed to live.

**Comment by zcrysler** [comment] 2017-09-21 19:01
Works in beta for receivers.  For tags, I can enter a start date and save, but I'm not allowed to enter an end date until I enter more info (I added species, lat/lon and saved again) but there is no warning about this so it's not clear what's preventing the ability to enter end date.  Once I add additional info then saving end dates works fine.

**Comment by pmorrill** [comment] 2017-10-10 15:48
Zoe: as of the next beta release, you will be able to enter start and end dates at the same time on new or pending deployments. But, with tags there is a wrinkle, since for a tag deployment to be considered active, there must be a valid species id present. Therefore - for tags - you must enter a start date, end date AND a species id for a successful save of the metadata.  If the species id is missing, a new error message will be presented to explain the problem.

(If you are not entering an end date, then nothing changes from the current behaviour).

**Comment by zcrysler** [comment] 2017-10-10 18:31
Sounds great, thanks!

**Closed** 2017-10-25 16:40 UTC
Labels: bug
