### ISSUE TITLE
bulk tag upload issue

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#240] opened 2018-05-14 20:32 UTC
project 143 had a number of tags that were deployed as the wrong species (Francolinus clappertoni instead of Rallus crepitans), so I downloaded the tag metadata, and changed all the incorrect speciesName fields to "Rallus crepitans", exactly as was already there for the correct existing tag deployments.  When I tried to upload the saved .csv file, I got a message at the top of the page that said "Your template file appears to be empty", but then there were the usual warnings for every line that I had tried to change the period.  Since it seemed like the upload had in fact worked, I clicked "complete upload".  Now the tag page for that project (https://motus.org/data/project/tags?projectID=143) has nothing listed for Species for any tag deployments even though there were species listed before.  When I download all tags the .csv file I have has the speciesName filled in correctly as I had uploaded (ie every species deployed as Rallus crepitans).  Maybe the speciesName I entered isn't correct? But it's what all the other Clapper Rails were listed as in the existing deployments for that project.  Species are showing up correctly here: https://motus.org/data/projectTagDeployments?id=143

**Comment by cjardine-bsc** [comment] 2018-06-19 17:46
Ah, This was caused by multiple speciesIDs matching the same species name. I've altered the procedure to take the minimum speciesID when matching based on name. 

This was also causing the error "Your data file appears to be empty" because the query was not making it to completion and passing back the "count" output parameter. With the fix to the query the error is not being returned any more. 

I've re-uploaded your template file and these deployments all resolved to valid species IDs.

**Comment by denislepage** [comment] 2018-06-19 17:57
The lowest speciesID isn't the solution. If there are multiple ID for the same name, there should only be one marked as valid (status > 0). The matching rules should be based on the status. If the lk table has multiple matches with status > 0, then the lk table should be fixed.

**Comment by cjardine-bsc** [comment] 2018-06-19 18:59
Sorry, I misspoke. The problem was that users were not able to upload subspecies using this tool because the validation we used to do excluded species_status =3.

i.e.

UPDATE #temp_speciesID
SET speciesID_fromName = species_id 
FROM #temp_speciesID a inner join lk_species b 
on concat_species_name = concat_english_name
WHERE species_status = 1 and  species_id is not null

So when a user downloaded their template of deployments on Ipswich Savannah Sparrows they were getting an error that their species didn't exist. We therefore needed to allow both status = 1 and status 3 in the query. 

i.e. 

UPDATE #temp_speciesID
SET speciesID_fromName = species_id 
FROM #temp_speciesID a inner join lk_species b 
on concat_species_name = concat_english_name
WHERE species_status in (1,3) and  species_id is not null

That's implemented. As long as the names are distinct between species and subspecies, which looks to be the case, this should allow for both.

**Closed by cjardine-bsc** 2018-06-19 18:59 UTC
Labels: bug
