### ISSUE TITLE
Tag registration: failed to load plugin "findpulsefdbatch"

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#239] opened 2018-05-11 20:45 UTC
jobID 179916 failed to register tags, the full Summary is:
File uploaded: 2751_2018-05-11T19-06-46.527_jbacon_projID152_2018.7z
Error: Error in safeSys("/sgm/bin/vamp-host", pars = paste0("-a ", names(pdpars), : Error 1 from '/sgm/bin/vamp-host -a minsnr=8 -a minfreq=0 -a maxfreq=24 -a plen=2.5 '/sgm/bin/lotek-plugins.so:findpulsefdbatch:pulses' '/sgm/queue/2//00179916/00179924/tag233.wav' '-o' '/tmp/RtmpC4GUNA/filee6224f831068'':

vamp-host: Running...
Reading file: "/sgm/queue/2//00179916/00179924/tag233.wav", writing to "/tmp/RtmpC4GUNA/filee6224f831068"
Vamp::HostExt::PluginLoader: No library found in Vamp path for plugin "lotek-plugins:findpulsefdbatch"
vamp-host: ERROR: Failed to load plugin "findpulsefdbatch" from library "/sgm/bin/lotek-plugins.so"

**Comment by zcrysler** [comment] 2018-05-14 15:05
Same with JobID 180139

These are all tags that are being put out very soon - can this be looked into ASAP?

**Comment by pmorrill** [comment] 2018-05-15 19:36
Can you try uploading one of the files (not already uploaded) by the old interface? We need to rule out the possibility that the new tools are causing an issue here.

**Comment by zcrysler** [comment] 2018-05-15 20:02
uploaded two more tag registrations to https://sgdata.motus.org/upload/upload-process-form.php, got the same error messages for jobID 181716:

"Thank-you for the upload - it has been processed.  Any product(s) are listed here:

  
Processing Summary:

File uploaded: 545_2018-05-15T19-55-44.436_tagTest_230_231.rar
Error: Error in safeSys("/sgm/bin/vamp-host", pars = paste0("-a ", names(pdpars), : Error 1 from '/sgm/bin/vamp-host -a minsnr=8 -a minfreq=0 -a maxfreq=24 -a plen=2.5 '/sgm/bin/lotek-plugins.so:findpulsefdbatch:pulses' '/sgm/queue/2//00181716/00181724/tag230.wav' '-o' '/tmp/RtmpiYgFkA/filed65e3590cce1'':

vamp-host: Running...
Reading file: "/sgm/queue/2//00181716/00181724/tag230.wav", writing to "/tmp/RtmpiYgFkA/filed65e3590cce1"
Vamp::HostExt::PluginLoader: No library found in Vamp path for plugin "lotek-plugins:findpulsefdbatch"
vamp-host: ERROR: Failed to load plugin "findpulsefdbatch" from library "/sgm/bin/lotek-plugins.so""

**Comment by Hussell** [comment] 2018-05-16 14:40
Caused by restarting the servers as the wrong user. Will be fixed soon.

**Comment by Hussell** [comment] 2018-05-28 14:43
John put in some (untested, so far as I know) code to prevent this from happening again.

**Comment by zcrysler** [comment] 2018-05-28 15:45
Can the uploads be re-run? job ID 181646 at least still doesn't have those tags registered

**Comment by zcrysler** [comment] 2018-05-31 18:57
job 181288 also hasn't gone through - I don't think any have. These tags were registered weeks ago, tags are already deployed or being deployed at this point, if these can be re-run let me know, if I need to contact users and ask them to re-upload all their recordings I can try that too

**Comment by jbrzusto** [comment] 2018-06-06 12:55
IDs of jobs affected by this problem were obtained like so:
```sql
sqlite3 /sgm_local/server.sqlite
sqlite> select distinct t1.id from jobs as t1 join jobs as t2 on t1.id=t2.stump where t1.mtime >= 1522540800 and t1.data||t2.data glob "*findpulse*";
```
I've re-run those jobs after fixing ownership of the unpacked files, like so:
```bash
for j in 178951 179306 179328 179793 179916 180021 180030 180139 180943 180952 181288 181646 181679 181716 183211
do 
   sudo chown -R sg:sg /sgm/done/00$j
   /sgm/bin/retryJob.R $j
done
```
Results of rerunning need to be checked by hand to check for any tags which failed to register.
Scroll down to the last of the "Log for XXXXXX" headings then check for messages about
tags.

Links to the jobs status:

- [ ] [178951](https://sgdata.motus.org/status?jobID=178951)
- [ ] [179306](https://sgdata.motus.org/status?jobID=179306)
- [ ] [179328](https://sgdata.motus.org/status?jobID=179328)
- [ ] [179793](https://sgdata.motus.org/status?jobID=179793)
- [ ] [179916](https://sgdata.motus.org/status?jobID=179916)
- [ ] [180021](https://sgdata.motus.org/status?jobID=180021)
- [ ] [180030](https://sgdata.motus.org/status?jobID=180030)
- [ ] [180139](https://sgdata.motus.org/status?jobID=180139)
- [ ] [180943](https://sgdata.motus.org/status?jobID=180943)
- [ ] [180952](https://sgdata.motus.org/status?jobID=180952)
- [ ] [181288](https://sgdata.motus.org/status?jobID=181288)
- [ ] [181646](https://sgdata.motus.org/status?jobID=181646)
- [ ] [181679](https://sgdata.motus.org/status?jobID=181679)
- [ ] [181716](https://sgdata.motus.org/status?jobID=181716)
- [ ] [183211](https://sgdata.motus.org/status?jobID=183211)

**Comment by Hussell** [comment] 2018-06-28 13:09
Many registrations failed with this error: "registration-failed: Tag registration failed - tag-exists".

**Comment by jbrzusto** [comment] 2018-06-28 13:42
Likely because users re-tried the uploads.  That error is on the motus.org side, and flags
double-registrations.

**Comment by Hussell** [comment] 2018-10-02 13:36
- Job 178951 rerun as job 224344, had one tag (364) apparently mislabeled (should be 365), all others registered.
- Jobs 179328 and 179793 both had just one tag (123) apparently mislabeled (should be 122).
- Job 179916 rerun as job 224335, all tags registered.
- Job 180943 rerun as job 224362, results identical to job 178951 (looks like another duplicate file).
- Job 180952 rerun as job 224371, results identical to jobs 178951 and 180943 (duplicate upload).
- Job 183211 is still an invalid zip file.

**Comment by Hussell** [comment] 2018-10-04 19:27
Receivers for project 152 have been rerun (there were only 3, and 1 of them had no data).

**Closed** 2018-10-18 22:01 UTC
Labels: bug, sgdata
