### ISSUE TITLE
Motus Website Latency

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#742] opened 2020-06-22 15:35 UTC
I've heard complaints from several people outside of Ontario that the Motus website is very slow all the time, and sometimes it's unusable. For example, it takes me 7 seconds to load the home page in Chrome (with cache) before I can start using the navigation menus. In FireFox, it takes an average of10 seconds. I think the culprit here is the Receivers Map, with the base map request taking 3 to 7 seconds to _initiate_. I'm not sure what's happening beforehand as it's not reported in my Network Monitor. The resource loaded immediately before the base map is the Google Maps Api script 'poly.js'.

Page | Resource | Chrome | FireFox
-- | -- | -- | --
Home | All | ~7 s | ~10 s
Home | HTML page | 75-200 ms | 500-800 ms
Home | /data/receiversMap?json | 0.5-1.5 s | 0.5-1.5 s
Home | StaticMapService.GetMapImage?etc… | 3.5-4.5 s* | 6-7 s*
* Time to initiation

The Receivers Map page takes about the same amount of time to load. In addition, it can take several seconds to load information for the tooltip when one of the receivers are clicked.

Other pages that take a long time to load are the Manage Data pages, taking 2-5 seconds on a good day, 30 seconds to several minutes on a bad one. Given the amount of navigation necessary for metadata management, this is understandably frustrating.

**Comment by denislepage** [comment] 2020-06-22 18:14
I just restarted the web server. The main bsc site was also slow. Not sure if that will help. If not, I can look more closely at the database.

**Comment by leberrigan** [comment] 2020-06-25 16:44
I've run the same tests again and am still getting the same results. The Upload Data page took 26 seconds to load, but the other Manage Data pages were fine.

**Comment by leberrigan** [comment] 2020-07-08 12:21
I have figured out where the code is slowing down page load times. In '[receiversMap.js](https://motus.org/scripts/receiversMap.js)', lines 215:282 there is a `foreach` loop that goes through each receiver deployment in the database and adds a marker to the map, setting the visibility according to the date selected on the slider and resolution selected in the dropdown menu. This code also loops through each antenna for each deployment and adds a polygon to the map. Loading this data is not important for the home page which can only display currently active receivers and no polygons. It should also be possible to add markers as they are needed instead of all at once.

Since this is JS, we're going to see variable load times according to the device and browser used. On cell phones it can be especially slow which is very annoying when trying to look up information while in the field.

**Comment by denislepage** [comment] 2020-07-09 01:22
I’d support removing the antenna shapes for the home page. Can we make this a toggle and disable it only on the home page by default?

**Comment by leberrigan** [comment] 2020-08-28 13:20
Uploading Data
---

I uploaded several files and got the following results. 

- The initial step is to unpack the file and then create a hash for verification. This step is actually relatively quick, but speed depends on file size. 
- The next step sends this hash to SGDATA and awaits a response - **this usually takes about a minute**, regardless of file size.
Once the file is verified it can be uploaded. This often takes many seconds to send the first 'chunk'. 
  - I noticed that for a file which was already partially uploaded, it took longer to send the first chunk, with a ~14 second send time and 22 second wait. The second chunk of that file took 0.6 seconds to send and 60 seconds of waiting. It then followed a similar pattern to other uploads, which was an average of 0.3 seconds sending and 1 second waiting for a response for each 256 KB chunk.
- Lastly, placing a file on the queue also took many seconds - over a minute for some. This did not appear to vary based on file size (as it shouldn't).


Action  | Average   of Time - Send | Average   of Time - Wait
-- | -- | --
Placing file on queue | 0 | 25,157
Refresh page | 0 | 1,345
Upload file | 287 | 1,037
Upload file (resumed) | 681 | 2,971
Verify file: FILE IS NEW | 0 | 20,418
Verify file: PARTIAL FILE   EXISTS | 0 | 53,033


Action | Min of Wait Time | Median | Max
-- | -- | -- | --
Placing file on queue | 2,832 | 12,201 | 84,695
Refresh page | 1,305 | 1,345 | 1,385
Upload file | 85 | 432 | 19,952
Upload file (resumed) | 285 | 417 | 59,885
Verify file: FILE IS NEW | 0 | 15,773 | 51,662
Verify file: PARTIAL FILE   EXISTS | 50,950 | 53,033 | 55,115

**Comment by denislepage** [comment] 2020-08-29 00:18
Ah, and another possible cause of latency, which is the one I started looking for when I started, is simply slow database queries on non-indexed fields of large tables. Definitely not the issue in this case, but something to watch for.

**Comment by denislepage** [comment] 2020-08-29 00:18
Just a preliminary report, but I think I know why the main project page is sluggish, and that can potentially apply elsewhere.

When I use a database trace on sandbox and load the main project page, I get a very high number of database requests when I am logged as myself (more than 650), which may well explain the long response time. There’s a loop making 2 calls for each project:

SELECT * FROM projects WHERE id = @P0
select b.user_id from user_status a left join projects_users b on b.user_id = a.user_id and b.project_id = @P0 where a.user_id = @P1 and a.user_status > 0

When I try to emulate another user (e.g. 15), who only has 5 projects, the page load is almost instant (170 ms), so that seems to be the root of the issue.

I dug a bit in the code, and I believe that for each project during the page load, a new ProjectBean is instantiated to access some of the properties. Because each project bean makes at least 2 database calls, this becomes very inefficient where there are more than a few projects.

The outer loop should be changed for it makes a single call to access the properties it needs with a single database call. I suspect the second line is only an artifact that is loaded when the bean instantiate, but that is not really needed on the project landing page.

I suspect that this problem is probably happening in several places, and resolving this could greatly help with the latency problems. I will look into whether there’s an elegant way by which I can create a way to output all the sql statements sent to the SQLWrapper object, so we can more easily identify what is happening.

There’s definitely some major efficiencies that can be gained by redesigning the code where there are a high number of database calls. In cases where you have 2 table levels, then you are better off making 1 call on the first, storing your results in memory, and then making a second single call to the child table, and appending the results to your object, as opposed to loop through your results and then make a call to the child table for each parent row.

**Comment by denislepage** [comment] 2020-08-29 01:25
OK, I just added some features to the SQLWrapper class in bscbase to allow extensive logging of SQL commands on a local file.  This is optional and is only turned on explicitly. After you create a (preferably static) ProjInfo, you can set the log on SQLWrapper as projInfo.getDB().setDebugLog(filename, showTimestamp, onlyErrors). I would prefer that you only do this on your local environments, but we can test in sandbox or elsewhere if there is a need. I also added a new option in the motus SetupFilter where the static defaultProjInfo is created, as a example of how this could be used. The filter will look for specific init parameters in the web.xml file, and initiate logging on the default projInfo if applicable. You can either set it to log all SQL commands, which would be necessary to identify the kinds of issues listed above, or only errors, if you are trying to narrow down a database problem. 

Note that if you create a distinct ProjInfo, the SQLWrapper object (and thus the logging) are not static. If you are using the same filename, I think it will run into conflicts, or perhaps delete and overwrite the previous file. A workaround would be to add a timestamp to the file name in the SetupFilter and elsewhere to ensure they are unique. I haven't dealt with this, but we will likely need to.

Finally, if you try to set the log on a static ProjInfo that was already enabled for logging, it will close the previous log and initiate a new one if the file path is different, or simply return silently if the file path is the same, and continue writing to the same file.

I haven't tested any of it. The log should be working the same, whether you are calling query, exec, sqlpreparedstmt or sqlcallablestmt. There is currently no support to log the parameters of statements as part of the same log file.

**Comment by denislepage** [comment] 2020-08-29 01:26
Note that the sandbox branch will be broken until you recompile the bscbase class.

**Comment by pmorrill** [comment] 2020-08-29 12:19
Instantiating objects to build the list of accessible projects is pretty inefficient - it is time for some code review in areas like that. I intend on Monday to start doing a bit of that.

On the data upload page, it is important to remember that we are  using javascript and an asynchronous process to upload the data, in chunks. The gain is that we can present a meaningful progress bar, and also that we can allow the user to 'pause' the process. When I implemented this, the standard blocking upload process (ie: relying on the browser and servlets alone) was faster than this 'fancy' jscript approach we adopted. I may do some experiments with reverting back to the simpler approach, for comparison.

Another possible bottleneck is the file save operation on the server: every partial chunk gets saved to a drive, that I believe is remote (a network drive) - Denis can confirm that. Writing data over a network connection is much slower than writing it locally. maybe we need to add local drive space for the partial file bits.

But in any case, I will definately try breaking down the slow steps to see if the issue is the calls to the sgserver, or something in our own handling.

**Comment by denislepage** [comment] 2020-08-30 20:45
Great, thanks.

One addition feature that may help slightly, but perhaps not, is that I have added some native Tomcat libraries that are recommended on a production environment. In all likelihood, we won't see an impact, as I don't expect we get enough concurrent traffic on tomcat to make a difference, but we should keep an eye on new unexpected behaviour. I have nothing to suggest that the libraries are likely to cause issues. They have been implemented on all 3 servers.

**Comment by denislepage** [comment] 2020-08-30 22:01
It's quite possible that uploads are being throttled by the network drive. I certainly see some latency when even just trying to browse the directories, but they are also very large, and a simple write may not suffer the same issues.

It'd be worth testing though. I created a folder called C:\temp\uploads, which you can use to compare the speed uploading large files with the network drive. The files will then have to be moved to the network folder and deleted locally, but the copying could be done asynchronously from the user thread by creating a runnable thread that handles that and is called after the user has seen the confirmation.

As a first step, lets simply allow testing in sandbox, by adding a radio button to determine the file destination, and perhaps on a test that is not pushing files to sgdata. 

I can also run some local copying tests to compare. If there's a big difference, I may ask Kwic for suggestions. I think we have a 1 GB network connection, and I don't know if there are options to improve that. The disk themselves should be of comparable speeds.

**Comment by denislepage** [comment] 2020-08-30 22:27
I ran a quick test to compare copying a large file hosted on the C drive to the same C drive, and the same file from the C drive to the network drive. The file was 8 GB in size. To my surprise, the network copy was faster. About 2.5 minutes on the local drive vs. 1.43 minutes on the network drive. One possible reason is that the local copy has to do both the reading and writing on the same drive. We should probably still test it on the actual upload, but it's possible we won't see a substantial difference. Of course, there may be times when the network I/O is being more heavily utilized creating bottlenecks, which could give different results at another time. No smoking gun so far anyway.

**Closed** 2022-03-24 20:23 UTC
Labels: Bug, Motus website
