### ISSUE TITLE
Wrong receiver serial number of SensorGnome status page, but remote web interface is correct

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#812] opened 2020-09-28 22:23 UTC
See it here: https://sg-e55brpi3d04c.sensorgnome.org/

The serial number on the remote web interface _correctly_ reads **62E1RPI31AB3**, yet the URL and SensorGnome status page _falsely_ say **e55brpi3d04c**. 

The only receiver that's actually deployed is  **62E1RPI31AB3**, yet no data has been allocated to that receiver's deployment: https://motus.org/data/receiver/deployment/plot?id=5011

The information displayed on the SensorGnome Status page for the receiver deployment is for an old deployment of **e55brpi3d04c**, #5570.

A search for issues related to either serial number only turns up something for the incorrect serial number: #527 . Could this in any way be related?

**Comment by dfloer** [comment] 2020-09-30 05:11
I haven't dug into this deeply yet, but this seems like the Motus API call's result is being cached somewhere on the Sensorgnome Server side. I'll update when I know more.

**Comment by leberrigan** [comment] 2020-09-30 19:50
In the mean time, can someone look into where the data is going?  My assumption is that these data are being uploaded as if they are from receiver "SG-e55brpi3d04c", I just don't know what happens after that. 

There should be a backlog of data starting from **14 January 2020** and I can't seem to find where it is from my end.

**Comment by dfloer** [comment] 2020-09-30 22:33
I see data starting from January 14th 2020 stored on the Sensorgnome itself, so it's there at least. Nothing on the Sensorgnome itself appears to be broken or set up wrong, so now I'm looking at what's going on with sensorgnome.org.

Has this been a problem with other Sensorgnomes that were redeployed on a new project?

**Comment by leberrigan** [comment] 2020-10-01 13:45
I noticed a similar thing with Cape Jourimain (SG-6938RPI31CE2), but this is no longer active so it's not a working example. I initially thought it was just slow to update, but now I believe it's the same problem.

**Comment by Hussell** [comment] 2020-10-02 17:40
Using the jobsForSerno parameter triggers an infinite-loop bug in the status server, one which I've been struggling to track down. No luck yet.

The sync jobs are showing up for SG-E55BRPI3D04C, but failing with the message "No new files obtained for receiver SG-E55BRPI3D04C", presumably because all the files are for receiver SG-62E1RPI31AB3. (That's the correct serial number, right? Not SG-6938RPI31CE2?)

So when it connects with the correct serial number it'll probably process several months worth of data all at once.

**Comment by leberrigan** [comment] 2020-10-15 17:45
@dfloer, Have you made any progress on this. We should push this up on the list as it's been nearly a year since this collaborator has deployed their receiver without seeing any data.

**Comment by dfloer** [comment] 2020-10-15 19:39
Without any insight into what's happening on the Motus or sgdata side, I'm blocked on what I can do with this. As far as I can tell, everything on the Sensorgnome side of things is correct, so it might be/have been bad data coming in.

**Comment by Hussell** [comment] 2020-10-15 19:56
SGData is being told to look for files from SG-E55BRPI3D04C, but all it's finding are files from SG-62E1RPI31AB3, so it does nothing.  The SensorGnome status page at https://sg-e55brpi3d04c.sensorgnome.org/ says "My machine ID is 62E1RPI31AB3." so the mismatch is somewhere on that end, @dfloer.

**Comment by dfloer** [comment] 2020-10-15 19:58
> SGData is being told to look for files from SG-E55BRPI3D04C, but all it's finding are files from SG-62E1RPI31AB3, so it does nothing. The SensorGnome status page at https://sg-e55brpi3d04c.sensorgnome.org/ says "My machine ID is 62E1RPI31AB3." so the mismatch is somewhere on that end, @dfloer.

sg.org gets data from motus.org's API, so the bad data had to have originated there, not on sg.org. Can you confirm that the data is correct there? I would, but I don't have access.

**Comment by Hussell** [comment] 2020-10-15 20:00
What's the API call, and what are the values being passed to it?

**Comment by dfloer** [comment] 2020-10-15 20:07
I think it was probably populated from: `https://motus.org/api/receivers/deployments?json={"date": <fillme>,"status":2}`. If the issue was since fixed upstream, I don't think there's a way to update sg.org presently.

**Comment by Hussell** [comment] 2020-10-15 20:25
Alright, that's a list of all receiver deployments. Possibly relevant ones, I guess, are:

2022	
motusRecvID	2810
recvProjectID	48
receiverID	"SG-62E1RPI31AB3"
receiverType	"SENSORGNOME"
recvDeployID	5011
deploymentStatus	"active"
deploymentName	"Westtown School Observatory"
siteName	"Westtown School"
dtStart	"2018-11-07 17:30:00 +00:00"
dtEnd	null
tsStart	1541611800
tsEnd	null
latitude	39.9482
longitude	-75.5383
elevation	126
isMobile	false
macAddress	"0"
locationPrecision	"Exact"

2040	
motusRecvID	3214
recvProjectID	48
receiverID	"SG-E55BRPI3D04C"
receiverType	"SENSORGNOME"
recvDeployID	5570
deploymentStatus	"terminated"
deploymentName	"Rushton To PARC workshop"
siteName	null
dtStart	"2019-08-23 14:00:00 +00:00"
dtEnd	"2019-08-23 20:10:00 +00:00"
tsStart	1566568800
tsEnd	1566590999.9999998
latitude	null
longitude	null
elevation	null
isMobile	true
macAddress	"0"
locationPrecision	"Exact"

The 2nd deployment seems to be what's displayed on https://sensorgnome.org/status/, but the linked receiver seems to be the 1st deployment. The question is, how does this deployment data get matched up with a physical receiver? (Also, why's it matched up wrong, how can it be fixed, what's 41027, etc.)

**Comment by dfloer** [comment] 2020-10-15 20:37
I see two different things here:
1. How to fix this specific receiver,
2. What happened in the first place to cause this, and how we can prevent it happening again.

For 1: I can change the serial number in the sqlite database on sg.org, but I have concerns about changing anything in production like that, because I don't know if sg.org will cleanly restart, and documentation is very light on how to start/troubleshoot it.
I also don't know if that'll actually work, because I don't understand how the problem occurred in the first place.

For 2: My working theory is that something went wonky when it was redeployed.
@Hussell if I'm reading the data correctly, the "wrong" Sensorgnome was deployed after the "right" one? What is the expected behaviour in this case, because it's not clear to how it should have "reverted" back to the old deployment. I also note that the "wrong" deployment appears to have existed for 6h10m, which seems odd to me.

**Comment by Hussell** [comment] 2020-10-15 20:59
The short deployment is of type "Automobile" (note isMobile = true), which means a short deployment makes sense.

The expected behaviour is that there should have been an entry for SG-62E1RPI31AB3 on the sensorgnome status page, then there should have been entries for both, with the entry for SG-E55BRPI3D04C soon disconnecting. (Or, there never should have been an entry for SG-E55BRPI3D04C, if it was never connected.) They never should have gotten merged or mixed together in the first place. So, it's not unexpected that there's nothing in place to fix this except manual intervention.

**Comment by dfloer** [comment] 2020-10-15 21:21
Unfortunately, none of the logs sg.org produces are timestamped, so I can't be sure when the problem started, but the SSH key it's using was generated on 21-Jun-2019, which is after the `2022` deployment started, hence why the receiver looks like it was redeployed at some point.

>They never should have gotten merged or mixed together in the first place.

Wouldn't the receiver need to be redeployed back to the `2022` deployment after being set to the `2040` one? I can attempt to fix this on the sg.org side, but I'd like to keep this from happening in the future.
I'm still not clear what happened here, was this receiver ever redeployed at some point?

**Comment by Hussell** [comment] 2020-10-16 14:42
The two deployments are recorded as being for different physical receivers. Assuming the deployment records are correct, the receiver was never redeployed. The receiver never should have been set to the 2040 one. (Note that 2022 and 2040 are just the row numbers in the list returned by the API. The recvDeployIDs are 5011 and 5570 respectively. I probably shouldn't have copied the row numbers, but now we've referred to them...)

I've browsed our backup tables, where we archive past states of deployments. Lucas mentioned that the backlog of data goes back to January 14th, 2020. Deployment 5011 was edited on that day, changing the start date from 2017-08-16 to 2018-11-07?!? That's weird, but 2018-11-07 is the first date from which we have data from that receiver. I don't see any other edits which seem like they could be relevant. Certainly the serial numbers were never changed.

Presumably 2020-01-14 is also the day the receiver was first connected. I'm guessing there was a data entry error and the wrong serial number was entered? (I'm not familiar with the process for setting up a connected receiver, so I may be way off here.)

**Comment by dfloer** [comment] 2020-10-16 18:46
I'm also not familiar with the process for setting up a connected receiver, maybe @leberrigan can comment. I'll also note `network.txt` was last edited on 14-Jan-2020, but I don't have any way to see the old version of it.

**Comment by leberrigan** [comment] 2020-10-17 12:51
Setting up a networked receiver only requires configuring the Sensorgnome by modifying the `network.txt` file. This involves entering 'WifiClient = yes' and setting a username and password for the Wi-Fi network. Everything else happens in the background. 
[network.txt](https://github.com/MotusDev/Motus-TO-DO/files/5395603/network.txt)

Like Jeremy mentioned, receivers are separated by serial number ("SG-4005BBBK3230") on Motus.org, with each having their own set of deployments. The only way receivers can be related to one another is if one or more _deployments_ share the same **siteName**. I wonder if the problem is the way its getting the site name or serial number?  @dfloer, do you know how that's done?

I just checked the receivers I currently have online and noticed that **SG-4005BBBK3230** should be reading "Clam Bay" as of 15-SEP-2020 (online 06-OCT-2020), but it's still showing "Louisbourg" under it's previous deployment that ended on 9-SEP-2020. The issue I had before with Cape Jourimain (currently offline) was similar to the original one in this thread in that the serial number displayed on Sensorgnome Status page was the old deployment whereas it showed the correct serial number if you viewed the web interface.

This is the original message from the person who notified me about this:

> Project 48 receiver SG-62E1RPI31AB3 (Deployment ID:  5011) has been running connected to the internet via wifi connection since January 14, 2020 and shows no new data since that time and does not appear on the sensorgnome status page.  Instead, receiver SG-E55BRPI3D04C (which is not currently deployed) appears on the status page under its previous deployment (Deployment ID:  5570.), and when I click on the ID to go to the "I am your sensorgnome" (https://sg-e55brpi3d04c.sensorgnome.org/) page, am brought to the webpage for a running SG-62E1RPI31AB3 as I would expect to see it.

**Comment by denislepage** [comment] 2020-10-17 18:55
To be clear, Motus.org ignores the siteName of SG and we strictly rely on serial numbers. Both values are part of the file names, but the site name is never shared with motus.org.

Receivers and deployments in Motus are linked based on the serial number, the ts of each hit, and the date of the deployment.

If there are some wires crossed, that is likely on sensorgnome.org, which I know nothing about.

Seems like the information about frequency should ideally be passed from sg.org to sgdata or Motus when new settings are detected by sg.org. is that possible?

**Comment by dfloer** [comment] 2020-10-19 19:35
It doesn't look like sg.org has any concept of the serial number of a SG just changing without a re-registration of it on sg.org, so it'd be interesting to understand why there's this mismatch.

sg.org relies on the SSH key that was used to authenticate a SG, not the serial number reported, and the SSH keys weren't changed here.

> Seems like the information about frequency should ideally be passed from sg.org to sgdata or Motus when new settings are detected by sg.org. is that possible?

@denislepage There isn't anything in the existing server to do this, but the SG's at least seem to be logging messages of the form `1561251912.6485|SG-E55BRPI3D04C|S,1561251912.475,1,frequency,166.376,0,` which shows the frequency it's tuned to.
As a quick fix, I could get you all of those messages and you could see about adding/updating any that need it, without needing to add that functionality to the existing server.

**Comment by Hussell** [comment] 2020-10-21 13:57
I'm getting 502 Bad Gateway errors when I try to visit individual sensorgnome pages (e.g. https://sg-e55brpi3d04c.sensorgnome.org/), and hourly uploads stopped on Monday evening. Is this related to the attempt to update? (I hope not!)

**Comment by dfloer** [comment] 2020-10-21 16:02
That's not good. No, I didn't start doing anything yet this week because of the annual staff meeting and not having time to fix things if they broke. I'll look ASAP.

**Comment by Hussell** [comment] 2020-10-21 17:59
OK, I can access the SensorGnome pages, and a long list of new syncReceiver jobs have just showed up on sgdata.motus.org.

**Comment by dfloer** [comment] 2020-10-21 18:21
Status page also appears to be updating properly.

**Comment by Hussell** [comment] 2020-10-22 00:10
Whatever happened just now has fixed #785.

**Comment by dfloer** [comment] 2020-12-17 22:30
I've changed `SG-E55BRPI3D04C` in the database to `SG-62E1RPI31AB3`. I no longer see the "E55" Sensorgnome on the status page, however, I don't see the "62E" either. It's still there and still collecting data.

**Comment by dfloer** [comment] 2020-12-17 22:38
Now it looks like the "E55" one is back (showing on the status page). I'm not sure where that's coming from, because It was confirmed not in the database.

**Comment by cjardine-bsc** [comment] 2020-12-17 22:58
It could be re-added in the metadata sync from the motus database?

'SG-E55BRPI3D04C' is in the sensors_hash_keys and sensors table. 

I can remove it from those tables if it is a bad serial number? Should it (and all the batches currently associated with it) be replaced with 'SG-62E1RPI31AB3'?

**Comment by dfloer** [comment] 2020-12-17 23:40
@cjardine-bsc I don't have a good understanding of how things work once they leave sg.org, but there is still a metadata mistmatch happening somewhere external to it. I think the "E55" SG was correct at one point, but isn't anymore, so I'm not sure how that affects things. Updating it to the current correct serial number seems like the best way to fix this.

**Comment by Hussell** [comment] 2020-12-18 14:16
Over on sgdata I'm now seeing behaviour for SG-E55BRPI3D04C which is similar to #785: repeated connection attempts on port 0. If sensorgnome.org wasn't restarted as part of the database update, perhaps try that? It may re-initialize the connection or clear cached data.

If sensorgnome.org was restarted, then I'll dig into the databases on sgdata to see whether there's an additional misconfiguration there.

**Comment by dfloer** [comment] 2020-12-19 02:56
Was definitely restarted, I wasn't going to change modifying the database under the running software. In the sg.org database, there isn't a port mapping for that SG anymore as I changed the serial number in the database.

This makes me wonder if the Sensorgnome itself wasn't set up properly, because I'm not sure why it'd think it still had the old serial number.

**Comment by cjardine-bsc** [comment] 2020-12-22 00:07
Okay, I've read through the above. 

From what I can interpret here (some of this is guesswork! If anyone has more info please let me know) :

SG-E55BRPI3D04C is a real receiver that physically exists somewhere, has a historic deployment and should be allowed to stay in the motus live database and the tagfinder database. It is registered in the sensors table twice (bad) once in project 0, once in project 48. (sensor Ids 3214 and 3421) both registered in Aug 2019. The project 0 sensor has no deployments and can probably be deleted. 

The project 48 receiver has two deployments, from summer 2019, both terminated. 

The deployments were short mobile deployments having the following comments: 

-Testing wireless automatic data download.  Use as mobile SG during installation trips.
-6 hour drive leaving Rushton Woods traveling to Town Hill FT in Green Ridge State Forest MD and Powdermill Avian Research Center.


SG-62E1RPI31AB3 is a different real receiver that physically exists and is currently deployed at Westtown School Observatory since 2018-present. This is an active deployment that overlaps the two SG-E55BRPI3D04C deployments. 

Based on this deployment information in the motus live database, both receivers should be registered to motus. We could have @leberrigan or @jsayers-bsc contact project 48 and confirm that they have two receivers that match these two serial numbers and that the deployments I describe above are correct? But I don't think thats the real question here. 

I thought the problem was that data collected using SG-62E1RPI31AB3 (device ID 1218) is being uploaded to the database under the device ID for SG-E55BRPI3D04C ( device ID 1502) but looking at the batch table that's not the case. The historic data seems correct. The problem (as described above) being that new data for SG-62 hasn't arrived for a year. 

batchID | sgBatchID | source | projectID | motusDeviceID | monoBN | (No column name) | (No column name) | numHits | motusUserID | motusJobID | ts | tsMotus | batchUID | batchFilter | version | is_new
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
739029 | 736969 | sg | 48 | 1218 | 2 | 18:20.1 | 18:20.5 | 0 | 347 | 2159372 | 1.58E+09 | 1.58E+09 | NULL | 0 | 2 | 1
739030 | 736970 | sg | 48 | 1218 | 3 | 55:19.8 | 04:52.0 | 2 | 347 | 2159373 | 1.58E+09 | 1.58E+09 | NULL | 0 | 2 | 1
809051 | 806560 | sg | 48 | 1218 | 4 | 24:53.9 | 31:27.9 | 0 | 2510 | 2472718 | 1.58E+09 | 1.58E+09 | NULL | 0 | 2 | 1
809052 | 806561 | sg | 48 | 1218 | 5 | 35:37.7 | 04:43.0 | 0 | 2510 | 2472719 | 1.58E+09 | 1.58E+09 | NULL | 0 | 2 | 1
809053 | 806562 | sg | 48 | 1218 | 6 | 08:11.2 | 12:58.1 | 2 | 2510 | 2472720 | 1.58E+09 | 1.58E+09 | NULL | 0 | 2 | 1
1323234 | 1268712 | sg | 48 | 1218 | 7 | 16:44.2 | 19:40.6 | 119 | 347 | 4447461 | 1.6E+09 | 1.6E+09 | NULL | 0 | 2 | 0
1323235 | 1268713 | sg | 48 | 1218 | 8 | 23:21.2 | 22:43.0 | 69 | 347 | 4447462 | 1.6E+09 | 1.6E+09 | NULL | 0 | 2 | 0
1323236 | 1268714 | sg | 48 | 1218 | 9 | 25:53.5 | 02:36.0 | 0 | 347 | 4447463 | 1.6E+09 | 1.6E+09 | NULL | 0 | 2 | 1
1323237 | 1268715 | sg | 48 | 1218 | 10 | 06:06.8 | 05:39.6 | 0 | 347 | 4447464 | 1.6E+09 | 1.6E+09 | NULL | 0 | 2 | 1
1323238 | 1268716 | sg | 48 | 1218 | 11 | 09:37.5 | 05:44.9 | 0 | 347 | 4447465 | 1.6E+09 | 1.6E+09 | NULL | 0 | 2 | 1
1323239 | 1268717 | sg | 48 | 1218 | 12 | 09:00.7 | 53:48.6 | 0 | 347 | 4447466 | 1.6E+09 | 1.6E+09 | NULL | 0 | 2 | 1
1323240 | 1268718 | sg | 48 | 1218 | 13 | 58:00.6 | 23:54.4 | 0 | 347 | 4447467 | 1.6E+09 | 1.6E+09 | NULL | 0 | 2 | 1
1323241 | 1268719 | sg | 48 | 1218 | 14 | 26:51.4 | 52:27.8 | 0 | 347 | 4447468 | 1.6E+09 | 1.6E+09 | NULL | 0 | 2 | 1
1164955 | 1138680 | sg | 48 | 1218 | 15 | 55:58.0 | 41:13.0 | 14 | 347 | 3915668 | 1.59E+09 | 1.59E+09 | NULL | 0 | 2 | 0
1164956 | 1138681 | sg | 48 | 1218 | 16 | 45:34.3 | 41:53.2 | 98 | 347 | 3915669 | 1.59E+09 | 1.59E+09 | NULL | 0 | 2 | 0
1164957 | 1138682 | sg | 48 | 1218 | 17 | 47:43.4 | 02:06.0 | 0 | 347 | 3915670 | 1.59E+09 | 1.59E+09 | NULL | 0 | 2 | 1
1164958 | 1138683 | sg | 48 | 1218 | 18 | 06:27.1 | 59:08.4 | 2 | 347 | 3915671 | 1.59E+09 | 1.59E+09 | NULL | 0 | 2 | 0
1164959 | 1138684 | sg | 48 | 1218 | 19 | 03:42.3 | 26:51.2 | 0 | 347 | 3915672 | 1.59E+09 | 1.59E+09 | NULL | 0 | 2 | 1
1233553 | 1203411 | sg | 48 | 1218 | 20 | 30:19.7 | 32:07.7 | 16 | 347 | 4144454 | 1.6E+09 | 1.6E+09 | NULL | 0 | 2 | 0
1233554 | 1203412 | sg | 48 | 1218 | 21 | 37:43.4 | 04:20.4 | 38 | 347 | 4144455 | 1.6E+09 | 1.6E+09 | NULL | 0 | 2 | 0
1233555 | 1203413 | sg | 48 | 1218 | 22 | 10:31.7 | 30:40.3 | 2 | 347 | 4144456 | 1.6E+09 | 1.6E+09 | NULL | 0 | 2 | 0
1536109 | 1364408 | sg | 48 | 1502 | 7 | 02:16.1 | 04:13.4 | 0 | 347 | 4826118 | 1.61E+09 | 1.61E+09 | NULL | 0 | 2 | 1

So there, I made a nice summary of stuff the rest of you already knew (me=helpful). 

I guess I don't fully understand where we would/should replace SG-55E with SG-62. SG-55E should not be a networked receiver but it should be in the DB.

**Comment by dfloer** [comment] 2021-01-05 22:44
@cjardine-bsc Thanks for looking into this. `62` is definitely still running and still collecting data.

Before we move on, probably a good idea for @leberrigan or @jsayers-bsc to figure out what actual physical SGs are doing what.

**Comment by jsayers-bsc** [comment] 2021-01-06 17:14
> @cjardine-bsc Thanks for looking into this. `62` is definitely still running and still collecting data.
> 
> Before we move on, probably a good idea for @leberrigan or @jsayers-bsc to figure out what actual physical SGs are doing what.

Will do; stay tuned

**Comment by StuMackenzie** [comment] 2021-01-14 19:34
Discussed on Motus call - @leberrigan  to resolve.

**Closed by StuMackenzie** 2021-01-14 19:34 UTC
Labels: Bad data, SensorGnome
