### ISSUE TITLE
Remove all detections from CompuData testing

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#212] opened 2018-04-16 20:28 UTC
All detections happening at CompuData can be assumed to be receiver testing prior to actual deployment.  Would it be possible to remove these detections from the database entirely - or hide them from users and the error page - so that we don't need to create test deployments repeatedly for instances like this?  I'm guessing a large portion of the 83 error warnings for detections outside of deployments for project 1 are at CompuData, making that many test deployments will be time consuming and result in a very messy deployments page.  An alternative is to ignore them but that doesn't deal with the underlying issue of unassigned detections. Compudata is located at 42.930307, -81.185039.  A 200 m circle around that point would likely catch the vast majority of CompuData testing and would not interfere with any nearby stations

**Comment by denislepage** [comment] 2018-04-17 01:53
OK, I have now set the batchFilter flag to 1 for batches that relate to CompuData location.

I have currently 3 possible values: 0 batch OK, 1 test batch and 2 deprecated batch (e.g. re-run). There may be other values needed. If we need to use that field in various ways (e.g. different for download than web output), we’ll probably need to set new flags in the lookup table.

There will be many follow-up steps needed to remove those batches from the outputs, including probably changing the indexes to include that field. I have changed the field to NOT NULL in sg_batches and added 0 as the default.

For example the vwBase views will probably need to add a condition for batchFilter = 0, and those records will probably need to be excluded from some of the cache tables (e.g. sg_taghits_deploy_id).

We’ll need a process to flag invalid batches. CompuData issue is only one of the types of issues to deal with. Noisy batches is the other main one.

We’ll need to proceed carefully.

**Comment by StuMackenzie** [comment] 2018-04-17 11:15
Compudata does not have any real stations contributing data to the network.

They have test tags which are on continuously - ID's 1,2 or 3 - I'm not sure of their burst rate or if they're registered. If they are registered they are duplicates of the same IDs in one of the Motus projects, test tags.

____________________

On Apr 16, 2018, at 21:53, denislepage <notifications@github.com<mailto:notifications@github.com>> wrote:

OK, I have now set the batchFilter flag to 1 for batches that relate to CompuData location.

I have currently 3 possible values: 0 batch OK, 1 test batch and 2 deprecated batch (e.g. re-run). There may be other values needed. If we need to use that field in various ways (e.g. different for download than web output), we'll probably need to set new flags in the lookup table.

There will be many follow-up steps needed to remove those batches from the outputs, including probably changing the indexes to include that field. I have changed the field to NOT NULL in sg_batches and added 0 as the default.

For example the vwBase views will probably need to add a condition for batchFilter = 0, and those records will probably need to be excluded from some of the cache tables (e.g. sg_taghits_deploy_id).

We'll need a process to flag invalid batches. CompuData issue is only one of the types of issues to deal with. Noisy batches is the other main one.

We'll need to proceed carefully.

-

**Comment by denislepage** [comment] 2019-07-06 03:46
I found that a relatively small number of batches at the Compudata site are not being correctly filtered. Our threshold of 200 m based on an average position is probably a bit too short. 

There are 175 batches with min(distance) up to about 1 km from Compudata that we have failed to flag, then a handful (10) that are between 1 and 10km.  A few of those are exceeding 1 week in duration. Some among them have mixed positions (a few close to CD, and some very far), but at least 10 are  between 7 and 1000 days long

```
WITH DTE AS (select a.batchID, tsBegin, tsEnd, lat, lon, dbo.distance(b.lat, b.lon, 42.930307, -81.185039) as dist  from motus.dbo.sg_batches a inner join motus.dbo.sg_gps b on a.batchID = b.batchID where a.batchFilter = 0 and lat <> 0 and lon <> 0) SELECT batchID, avg(tsBegin), avg(tsEnd), AVG(tsEnd - tsBegin) / (3600 *24) as durDays, MIN(dist) as minDist, MAX(dist) as maxDist, AVG(dist) as avgDist from DTE  group by batchID 
having MIN(dist) < 10000 and MAX(dist) < 5000
order by AVG(tsEnd - tsBegin) desc

```
There are only 2 batches among those that are very long that seem to overlap with an active receiver deployment:  BatchID 440586 and 440588 and deployment 4684. I am not sure how we can explain those. Perhaps caused by the boot number issue.


We can probably safely flag anything with at least 1 detection within 1 km (or 1.5 km) of Compudata as a test and none greater than 5 km.  Or, as below, flag anything where the min(distance) and the max(distance) to Compudata are both < 5 km.

We can keep the week-long duration criterion for now.

```
update sg_batches set batchFilter = 1 where batchID in (
SELECT batchID from (select a.batchID, tsBegin, tsEnd, lat, lon, dbo.distance(b.lat, b.lon, 42.930307, -81.185039) as dist  from sg_batches a inner join sg_gps b on a.batchID = b.batchID where a.tsMotus > 0 and (a.tsEnd - a.tsBegin) < 7 * 24 * 3600 and a.batchFilter = 0 and lat <> 0 and lon <> 0) DTE  group by batchID  having MIN(dist) < 5000 and MAX(dist) < 5000)

```

It still seems strange though that some of those batches are so long and/or contain that much data.

**Comment by Hussell** [comment] 2019-07-08 15:33
Batches 440586 and 440588 are indeed victims of the boot number issue.

Some of the longest batches with at least one GPS hit less than 5km from CompuData, which have not been filtered out:

| batchID | serial number | notes |
| - | - | - |
| 451231, 451233 | SG-2616BBBK1111 | The troublesome duplicated serial number receiver. Merged batches which haven't been deleted yet. #502 |
| 297086 | SG-4515BBBK0438 | Boot number reset. |
| 438674, 438675 | SG-4452RPI3CF82 | Boot number reset. |
| 303100 | SG-1253RPI32253 | Boot number reset. |
| 440586, 440588, 440589 | SG-91EBRPI3E583 | Boot number reset. |
| 279995 | SG-4002BBBK1530 | Boot number reset. |
| 279057, 279058, 279059 | SG-3214BBBK7260 | Boot number reset. |
| 280782, 280783 | SG-3214BBBK7228 | Boot number reset. |
| 235751 | SG-3115BBBK1375 | A real CompuData test which lasted 8 days. |
| 65267 | SG-5113BBBK3017 | A CompuData test with a couple of GPS hits 10 km away and the other 36 close. Average distance just over 500m, but ~125m without the two anomalous hits. |
| 421827 | SG-4414BBBK0737 | A CompuData test. I don't understand why this one isn't already filtered out. |
| 251733 | SG-5113BBBK2919 | Boot number reset. |
| 421611 | SG-DA8ARPI33476 | Boot number reset. |
| 56582, 56583 | SG-5113BBBK2819 | Boot number reset. |
| 281384 | SG-3214BBBK5594 | Boot number reset. |
| 83949 | SG-1215BBBK1163 | A CompuData test with an anomalous hit ~4km away, increasing the average distance to ~300m. Avg. distance ~60m without the anomalous hit. |

So, most long ones seem to be batches which got merged due to boot number resets. A few are due to anomalous GPS hits. One unfiltered batch (ID 421827) I don't understand.

**Comment by denislepage** [comment] 2019-07-08 21:55
OK, this argues for using both the min and max distance from the Compudata site as suggested earlier. (e.g. min < 5km and max < 10 km of the site, max < 5km alone), rather than simply the min.

**Comment by StuMackenzie** [comment] 2020-03-20 18:31
I think this was resolved?

**Comment by cjardine-bsc** [comment] 2020-03-20 18:37
Yup. *Steals the close*

**Closed by cjardine-bsc** 2020-03-20 18:37 UTC
Labels: enhancement
