### ISSUE TITLE
'translateCharUTF8' errors

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#230] opened 2018-05-03 22:07 UTC
Project 74, failed tag registration "Error: Error in dir(dst): 'translateCharUTF8' must be called on a CHARSXP" jobID 178951

**Comment by zcrysler** [comment] 2018-05-04 18:07
Another user is getting the same error message for a station data upload: jobID 179267

**Comment by Hussell** [comment] 2018-05-04 18:44
This error has happened for several jobs. I've looked into it, and my tentative guess is that it's something to do with the sgdata trash directory having so many files in it that the R call to list the files (That's what "dir(dst)" is about) is crashing. I've filed an issue for John to look at it, because I'm having trouble testing whether my guess is correct or not. I can't seem to list the contents of that directory or even check how much space it's using.

**Comment by zcrysler** [comment] 2018-05-07 17:08
Just adding so it's documented, another user had the same issue: jobID 179267 for project 120

**Comment by Hussell** [comment] 2018-05-15 17:41
I think I've finally figured out what's going on here and fixed it for most people. The bug occurs when R tries to read a list of files when there are filenames with accented characters in them. Project 125 has a receiver at Bahía de Asunción, and the temporary files went into the trash directory and triggered this bug for a lot of other projects. I've cleaned out the trash directory, so other projects are no longer affected. I'm working on a fix for project 125's receiver and to prevent this from happening again.

**Comment by zcrysler** [comment] 2018-05-15 21:26
Have they been re-run? Some of them seem ok, but there still seem to be some problems:

It looks like SG-1914BBBK0833 in project 174 is missing data in the hourly plot, there should be data from early may and late april: https://sgdata.motus.org/download/173/SG-1914BBBK0833-2017_Italian%20Islands_Ventotene--Punta%20dell'Arco_hourly_tags.png, looks like the reboot goes fro 3 to 5 and skips 4.

jobID 179880 Nanticoke in project 1 has no hourly plot, the link given leads to "Not Found": https://sgdata.motus.org/download/1/SG-4001BBBK2690-2017_Motus_Nanticoke_hourly_tags.png

jobID 179889 Tip in project 1 doesn't have any recent data in the hourly plot: https://sgdata.motus.org/download/1/SG-5113BBBK2674-2017_Motus_Long_Point_Tip_hourly_tags.png, should have data up to 2018-04-27

**Comment by jbrzusto** [comment] 2018-05-16 00:06
The problem isn't accented characters *per se*, it's that some R code is expecting UTF-8 strings but 
the  "short labels" for some sites (as entered into the deployment.txt file on the sensorgnome and cleverly included in every datafile name) are in another character encoding, such as Windows Latin-1.
One fairly clean approach to dealing with this is to recode filenames as soon as they're uploaded 
or extracted from an uploaded archive, before feeding them into the processing queue.

**Comment by zcrysler** [comment] 2018-06-21 20:32
I'm still  unclear about if this has been fixed, I haven't gone through all the files mentioned above, but jobID 179880, receiver SG-4001BBBK2690 should have data at least until Jan 14 2018 (according to this: https://sgdata.motus.org/status?serno=SG-4001BBBK2690), but there's no hourly plot, and tagme() doesn't return any gps hits past 2017-03-15 so I assume nothings getting into Motus.

Is it possible to confirm if this issue has been dealt with, and if so, can all receivers that had this error be re-run? I don't have a good way to check for these errors so I don't know how to come up with a comprehensive list of affected stations.

**Comment by Hussell** [comment] 2018-06-22 13:57
You can get a list of jobs affected at https://sgdata.motus.org/status by searching for "jobs with logs matching" "translateCharUTF8".

It's not fixed. The files with unexpected file-name encodings have been removed from the directory where they were causing trouble for everyone else, but if the upload which caused this problem is rerun then the bad files will be back. No fix has been checked in for this issue. (I close bugs which I'm confident have been fixed, so if you're looking at an issue I'm assigned to, and it's open, you can be reasonably certain it isn't done.)

Something has changed so I can't rerun receivers anymore, so until I figure out how to do that again we're entirely reliant on John. Last I heard, he's planning to rerun every receiver that had an upload job between ~March 20th and ~May 20th, which includes every receiver which was affected by this bug. I'm not sure when that's going to happen. Presumably he'll have to fix the filename bug before rerunning the receiver with the bad file names, or skip rerunning that one.

**Closed** 2019-02-22 15:03 UTC
Labels: bug, done, sgdata
